--DEFINE h_trdt = '20091117'
select MACN, CIF, TENKH, SOTK, KYHAN, LOAITIEN, LAISUAT, NGAYMO, NGAYDAOHAN, SDNGUYENTE, SDQUYDOI
from
(SELECT A.BRCD MACN, A.CUSTSEQ CIF ,NMLOC TENKH, A.REFNO SOTK,DECODE(C.TIMEDPTP,'001',TO_NUMBER(C.CNTRMMTRM) ||' Ngay', '002' ,TO_NUMBER(C.CNTRMMTRM) ||' Thang','Khong Ky Han') KYHAN, CCY LOAITIEN,DECODE(C.TIMEDPTP,'',0,INTRT) LAISUAT,DECODE(SIGN(OPNDT-RENWDT), 1, to_char(to_date(OPNDT, 'yyyymmdd'), 'dd/mm/yyyy'), to_char(to_date(RENWDT, 'yyyymmdd'), 'dd/mm/yyyy')) NGAYMO,
DECODE(MATDT,'00000000',MATDT,to_char(to_date(MATDT, 'yyyymmdd'), 'dd/mm/yyyy')) NGAYDAOHAN, CLRBAL SDNGUYENTE,CS1.EXCROSSCAL(A.brcd,'VND',&h_trdt,A.CCY,NVL(A.clrbal,0),'01','VND','01') SDQUYDOI
FROM GL1.TBGL_BALDD A, CM1.TBCM_GENERAL B ,TBDP_DPTP C
WHERE A.TRDT = &h_trdt
AND A.BRCD=B.BRCD
AND A.CUSTSEQ = B.CUSTSEQ
AND B.CUSTTPCD <> '100'
AND BUSCD='DP'
AND A.BRCD = C.BRCD
AND A.TRREF = C.DPTPCD
AND A.TRREF NOT IN ('6D1','6D2','6D3','6D4')
union all
SELECT A.BRCD MACN, A.CUSTSEQ CIF ,NMLOC TENKH, A.REFNO SOTK,DECODE(C.TIMEDPTP,'001',TO_NUMBER(C.CNTRMMTRM) ||' Ngay', '002' ,TO_NUMBER(C.CNTRMMTRM) ||' Thang','Khong Ky Han') KYHAN, CCY LOAITIEN,DECODE(C.TIMEDPTP,'',0,INTRT) LAISUAT,DECODE(SIGN(A.OPNDT-RENWDT), 1, to_char(to_date(A.OPNDT, 'yyyymmdd'), 'dd/mm/yyyy'), to_char(to_date(RENWDT, 'yyyymmdd'), 'dd/mm/yyyy')) NGAYMO,
DECODE(A.MATDT,'00000000',A.MATDT,to_char(to_date(A.MATDT, 'yyyymmdd'), 'dd/mm/yyyy')) NGAYDAOHAN, CLRBAL SDNGUYENTE,CS1.EXCROSSCAL(A.brcd,'VND',&h_trdt,A.CCY,NVL(A.clrbal,0),'01','VND','01') SDQUYDOI
FROM GL1.TBGL_BALDD A, CM1.TBCM_GENERAL B ,TBDP_DPTP C, DP1.TBDP_SAVMST D
WHERE A.TRDT = &h_trdt
AND A.BRCD=B.BRCD
AND A.CUSTSEQ = B.CUSTSEQ
AND B.CUSTTPCD <> '100'
AND BUSCD='DP'
AND A.BRCD = C.BRCD
AND A.TRREF = C.DPTPCD
AND A.TRREF IN ('6D1','6D2','6D3','6D4')
AND A.BRCD = D.BRCD
AND A.TRREF = D.DPTPCD
AND A.TRSEQ = D.ACCTSEQ)
ORDER BY MACN, CIF, SOTK
