--define h_trdt = '20120920'

SELECT
	APLID,
	DECODE(SUBSTR(APLID,1,3), 'LDS', 'DISBURSEMENT', 'REPAYMENT') SUB_TYPE,
	A.BRCD,
	CUSTSEQLN CIF,
	DSBSSEQ,
	NMLOC COUNTER_PARTY,
	DEAL_DATE,
	VALUE_DATE,
    DECODE(APLID, 'LDS', DECODE(COUNTER_CCY, 'VND', 'BUY', DECODE(DEAL_CCY, 'VND', 'BUY', 'SELL')),
    	DECODE(SUBSTR(APLID,4,1), 'P', DECODE(COUNTER_CCY, 'VND', 'SELL', DECODE(DEAL_CCY, 'VND', 'SELL', 'BUY')),
    			'I', DECODE(COUNTER_CCY, 'VND', 'SELL/BUY', DECODE(DEAL_CCY, 'VND', 'SELL', 'BUY')))) BUY_SELL,
	DEAL_CCY,
	DEAL_AMOUNT,
	COUNTER_CCY,
	COUNTER_AMOUNT,	        
	RATE,
	A.USRIDOP,
	DYSEQ,
	0 CLX,
	EXRT,
	A.REM,
	DECODE(LN1.CHK_LNCUSTTP(A.BRCD, '', '', A.CUSTSEQLN, 'IND'), 'Y', 'CN', 'DN') CUST_TYPE,
	A.DEPTCD DEPT_CODE,
	C.DEPTNM DEPT_NAME
FROM
(
	/* GIAI NGAN */
	SELECT
		A.BRCD,
		B.CUSTSEQLN,
		A.APLID,
		B.DSBSSEQ,
		A.TRDT DEAL_DATE,
		B.DSBSDT VALUE_DATE,
		CCYCDTR DEAL_CCY,
		TRAMT	DEAL_AMOUNT,
		CCYCDSTL COUNTER_CCY,
		STLAMT	COUNTER_AMOUNT,
		0 INTAMT_EX,
		0 RPMTAMT_EX,
	    EXRT RATE,
	    B.USRIDOP,
	    A.DYSEQ,
	    LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', B.FNDPRPSTPCD||B.FNDPRPSUNIT, 'DECODE') EXRT,
	    A.REM,
	    B.DEPTCD
	FROM
		TBLN_STL A, TBLN_DSBS B
	WHERE
		A.TRDT = &h_trdt
		AND CCYCDTR <>  CCYCDSTL
		AND CCYCDTR <> 'GD1'
		AND CCYCDSTL <> 'GD1'
		AND A.BRCDAPL = B.BRCD
		AND A.APLID = B.DSBSID
		AND A.APLSEQ = B.DSBSSEQ
		AND B.STSCD IN ('01', '05')
		AND B.BUSCD = 'LN'

	UNION ALL

	SELECT
		BRCD, CUSTSEQLN, APLID,
		DSBSSEQ, DEAL_DATE, VALUE_DATE,
		DEAL_CCY, DEAL_AMOUNT, COUNTER_CCY, COUNTER_AMOUNT,
		INTAMT_EX, RPMTAMT_EX, RATE, USRIDOP, DYSEQ, EXRT, REM, DEPTCD
	FROM
	(
		SELECT
			BRCD, CUSTSEQLN, DECODE(FLG, 1, 'LRPI', 'LRPP') APLID, DSBSSEQ, DEAL_DATE, VALUE_DATE,
			DEAL_CCY, DECODE(FLG, 1, INTAMT_EX, RPMTAMT_EX) DEAL_AMOUNT,
			COUNTER_CCY, COUNTER_AMOUNT, INTAMT, RPMTAMT,
			DECODE(FLG, 1, INTAMT_EX, 0) INTAMT_EX,
			DECODE(FLG, 2, RPMTAMT_EX, 0) RPMTAMT_EX, RATE, USRIDOP, DYSEQ, EXRT, REM, DEPTCD
		FROM
		(
			SELECT
				A.BRCD,
				B.CUSTSEQLN,
				A.APLID,
				B.DSBSSEQ,
				A.TRDT DEAL_DATE,
				C.RPMTDT VALUE_DATE,
				CCYCDTR DEAL_CCY,
				TRAMT	DEAL_AMOUNT,
				CCYCDSTL COUNTER_CCY,
				STLAMT	COUNTER_AMOUNT,
				C.INTAMT,
				C.RPMTAMT,
				DECODE(SIGN(TRAMT - C.RPMTAMT - C.INTAMT), 1, C.INTAMT, DECODE(SIGN(TRAMT - C.RPMTAMT), 1, TRAMT - C.RPMTAMT, 0)) INTAMT_EX,
				DECODE(SIGN(TRAMT - C.RPMTAMT), -1, TRAMT, C.RPMTAMT) RPMTAMT_EX,
			    EXRT RATE,
			    C.USRIDOP,
			    A.DYSEQ,
			    LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', B.FNDPRPSTPCD||B.FNDPRPSUNIT, 'DECODE') EXRT,
			    A.REM,
		        B.DEPTCD
			FROM
				TBLN_STL A, TBLN_DSBS B,
				(
					SELECT BRCD, RPMTID, RPMTSEQ, RPMTDT, BRCDDSBS, DSBSID, DSBSSEQ,
							USRIDOP, SUM(NVL(INTAMT,0) + NVL(PSTINTAMT,0)) INTAMT, SUM(NVL(RPMTAMT,0)) RPMTAMT
					FROM TBLN_RPMT
					WHERE STSCD = '01'
					AND TRDT = &h_trdt
					AND ACMODE = 0
					GROUP BY BRCD, RPMTID, RPMTSEQ, RPMTDT, USRIDOP, BRCDDSBS, DSBSID, DSBSSEQ
				)C
			WHERE
				A.TRDT = &h_trdt
				AND (CCYCDTR <>  CCYCDSTL OR (C.INTAMT > 0 AND CCYCDTR <> 'VND' AND CCYCDSTL <> 'VND'))
				AND CCYCDTR <> 'GD1'
				AND CCYCDSTL <> 'GD1'
				AND A.BRCDAPL = C.BRCD
				AND A.APLID = C.RPMTID
				AND A.APLSEQ = C.RPMTSEQ
				AND C.BRCDDSBS = B.BRCD
				AND C.DSBSID = B.DSBSID
				AND C.DSBSSEQ = B.DSBSSEQ
				AND B.STSCD IN ('01', '05')
				AND B.BUSCD = 'LN'
		) A, (SELECT 1 FLG FROM DUAL UNION ALL SELECT 2 FLG FROM DUAL) B
	)
	WHERE
		INTAMT_EX > 0 OR RPMTAMT_EX > 0
		AND (DEAL_CCY <>  COUNTER_CCY OR (INTAMT_EX > 0 AND DEAL_CCY = COUNTER_CCY))
) A, TBCM_GENERAL B, TBCS_DEPTCD C
WHERE
	A.BRCD = B.BRCD
	AND A.CUSTSEQLN = B.CUSTSEQ
	AND NVL(A.DEPTCD,'XXX') = C.DEPTCD(+)
ORDER BY APLID, BRCD, CUSTSEQLN

