--DEFINE h_trdt = '20121013'

SELECT T.BRCD AS MA_CN,
       (SELECT BRCD.LCLBRNM
	FROM   TBCS_BRCD BRCD
	WHERE  BRCD.BRCD = T.BRCD) AS TEN_CN,

       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', NULL, T.PLGAMT_VND), NULL)) AS NHADAT_NT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', NULL, T.DSBSBAL_VND), NULL)) AS NHADAT_NT_DU_NO_QD,

       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', T.PLGAMT_VND, NULL), NULL)) AS DATNN_NT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', T.DSBSBAL_VND, NULL), NULL)) AS DATNN_NT_DU_NO_QD,

       SUM(DECODE(T.CLPOSTP, '01', DECODE(T.CLDTLTPCD, '128', T.PLGAMT_VND, NULL), NULL)) AS DATNN_DT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '01', DECODE(T.CLDTLTPCD, '128', T.DSBSBAL_VND, NULL), NULL)) AS DATNN_DT_DU_NO_QD,

       SUM(T.PLGAMT_VND) AS TONG_GIA_TRI_TSDB_QD,
       SUM(T.DSBSBAL_VND) AS TONG_DU_NO_QD

FROM   (

	SELECT A.BRCDOWNR,
		A.CUSTSEQOWNR,
		A.BRCDCL || '-' || A.CLID || '-' || A.CLSEQ CLSEQ,
		A.CLDTLTPCD,
		B.CLSTSCD,
		B.GNTERLTNTPCD,
		B.GNTERLTNDESC,
		B.TRSPTSTSCD,
		B.MGRDT,
		B.CLQTYSZ,
		A.CLCCYCD,
		B.UNTFCAMT,
		A.PLGAMT,
		DECODE(A.CLCCYCD, 'VND', A.PLGAMT, CS1.EXCROSSCAL(A.BRCDCL, 'VND', &h_trdt, A.CLCCYCD, A.PLGAMT, '01', 'VND', '01')) PLGAMT_VND,
		A.BRCDLN,
		A.CUSTSEQLN,
		A.BRCDAPPR || '-' || A.APPRID || '-' || A.APPRSEQ APPRSEQ,
		A.BRCD,
		A.BRCD || '-' || A.DSBSID || '-' || A.DSBSSEQ DSBSSEQ,
		A.FNDPRPSTPCD,
		A.FNDPRPSUNIT,
		C.OTHRTPCD,
		A.CCYCD,
		A.DSBSBAL,
		DECODE(A.CCYCD, 'VND', A.DSBSBAL, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSBAL, '01', 'VND', '01')) DSBSBAL_VND,
		SUBSTR(A.ACCTCD, 4, 1) BALGRP,
		DECODE(NVL(A.ACCTCD, '000000'), '211100', '1.Ng¾n h¹n', '211101', '1.Ng¾n h¹n', '211200', '1.Ng¾n h¹n', '211201', '1.Ng¾n h¹n', '211300', '1.Ng¾n h¹n', '211301', '1.Ng¾n h¹n', '211400', '1.Ng¾n h¹n', '211401', '1.Ng¾n h¹n', '211500', '1.Ng¾n h¹n', '211501', '1.Ng¾n h¹n', '222100', '1.Ng¾n h¹n', '222200', '1.Ng¾n h¹n', '222300', '1.Ng¾n h¹n', '222400', '1.Ng¾n h¹n', '222500', '1.Ng¾n h¹n', '241100', '1.Ng¾n h¹n', '241200', '1.Ng¾n h¹n', '241300', '1.Ng¾n h¹n', '241400', '1.Ng¾n h¹n', '241500', '1.Ng¾n h¹n', '212100', '2.Trung h¹n', '212200', '2.Trung h¹n', '212300', '2.Trung h¹n', '212400', '2.Trung h¹n', '212500', '2.Trung h¹n', '223100', '2.Trung h¹n', '223200', '2.Trung h¹n', '223300', '2.Trung h¹n', '223400', '2.Trung h¹n', '223500', '2.Trung h¹n', '213100', '3.Dµi h¹n', '213200', '3.Dµi h¹n', '213300', '3.Dµi h¹n', '213400', '3.Dµi h¹n', '213500', '3.Dµi h¹n', A.ACCTCD) LNTPCD,
		A.ACCTCD,
		D.NM,
		E.PIVID || E.PIVSEQ PIVSEQ,
		E.BUSREGNO,
		E.INVRNM,
		E.PRJNM,
		B.REM,
		B.CRDTOFC,
		B.CLLOC,
		B.CLPOSTP
	FROM   LN1.TBLN_CLBAL A,
		LN1.TBLN_DSBS C,
		LN1.TBLN_CL B,
		(

		 SELECT A1.BRCD,
			 CLID,
			 CLSEQ,
			 DECODE(NVL(A1.NM, ' '), ' ', B1.NMLOC, A1.NM) NM
		 FROM   LN1.TBLN_CLREF A1,
			 TBCM_GENERAL   B1
		 WHERE  A1.STSCD = '01'
			AND NVL(QTY, 0) = 0
			AND A1.BRCD = B1.BRCD(+)
			AND TRIM(A1.REFNO) = B1.CUSTSEQ(+)

		 ) D,
		(

		 SELECT PIVID,
			 PIVSEQ,
			 BUSREGNO,
			 INVRNM,
			 PRJNM
		 FROM   LN1.TBLN_PROJINVR A1,
			 LN1.TBLN_PROJECT  B1
		 WHERE  A1.PRJID = B1.PRJID
			AND A1.PRJSEQ = B1.PRJSEQ
			AND A1.STSCD = '01'
			AND B1.STSCD = '01'

		 ) E
	WHERE  A.TRDT = &h_trdt
	       AND A.BRCD = C.BRCD(+)
	       AND A.DSBSID = C.DSBSID(+)
	       AND A.DSBSSEQ = C.DSBSSEQ(+)
	       AND A.BRCDAPPR = C.BRCDAPPR(+)
	       AND A.APPRID = C.APPRID(+)
	       AND A.APPRSEQ = C.APPRSEQ(+)
	       AND A.BRCDCL = B.BRCD(+)
	       AND A.CLID = B.CLID(+)
	       AND A.CLSEQ = B.CLSEQ(+)

	       AND B.BRCD = D.BRCD(+)
	       AND B.CLID = D.CLID(+)
	       AND B.CLSEQ = D.CLSEQ(+)
	       AND B.PIVID = E.PIVID(+)
	       AND B.PIVSEQ = E.PIVSEQ(+)

	       AND A.STSCD = '01'
	       AND (B.CLPOSTP = '02' OR
	       (B.CLPOSTP = '01' AND A.CLDTLTPCD = '128'))
	       AND
	       LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND') = 'Y'

	) T

GROUP  BY T.BRCD

ORDER  BY T.BRCD
