--define h_trdt = '20111031'

SELECT
	A.BRCD MA_CN,
	B.LCLBRNM TEN_CN,
	A.DEPTCD MA_PGD,
	(SELECT DEPTNM FROM TBCS_DEPTCD WHERE A.DEPTCD = DEPTCD) TEN_PGD,
--	DECODE(SUBSTR(NVL(A.DEPTCD, 'XXX'), 3, 1), 'O', A.DEPTCD) MA_PGD,
--	DECODE(SUBSTR(NVL(A.DEPTCD, 'XXX'), 3, 1), 'O', E.DEPTNM) TEN_PGD,
	A.CUSTSEQLN CIF,
	C.NMLOC TEN_KH,
	A.DSBSSEQ KHE_UOC,
	A.DSBSDT NGAY_GIAI_NGAN,
	A.MATDT NGAY_DAO_HAN,
	LN1.GET_TCODE('LNLNTPCD', 'CC', A.LNTPCD, 'DECODE') LOAI_VAY,
	DECODE(LENGTH(A.FNDPRPSTPCD), 5, LN1.GET_TCODE('LNFNDPRBRLEV1', 'CC', SUBSTR(A.FNDPRPSTPCD, 1, 2), 'DECODE')) MDV_CAP1,
	LN1.GET_TCODE('LNFNDPRPSTPCD', 'CC', A.FNDPRPSTPCD, 'DECODE') MDV_CAP2,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||SUBSTR(A.FNDPRPSUNIT, 1, 2), 'DECODE') MDV_CAP3,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||A.FNDPRPSUNIT, 'DECODE') MDV_CAP4,
	A.CCYCD LOAI_TIEN,
	SUBSTR(A.LNSBTPCD, 2, 1) NHOM_NO,
	D.TRDT NGAY_THU_NO,
	SUM(D.RPMTAMT) THU_NO,
	SUM(DECODE(A.CCYCD, 'VND', D.RPMTAMT, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, D.RPMTAMT, '01', 'VND', '01'))) THU_NO_QUI_DOI
FROM
	TBLN_DSBS A, TBCS_BRCD B, TBCM_GENERAL C, TBLN_RPMT D

WHERE
	A.STSCD IN ('01', '05')
	AND A.BUSCD = 'LN'
	AND A.BRCD = D.BRCDDSBS
	AND A.DSBSID = D.DSBSID
	AND A.DSBSSEQ = D.DSBSSEQ
--	AND D.TRDT BETWEEN SUBSTR(&h_trdt, 1,4)||'0101' AND &h_trdt
	AND D.TRDT BETWEEN SUBSTR(&h_trdt, 1,6)||'01' AND &h_trdt
	AND D.STSCD = '01'
	AND D.ACMODE = 0
	AND D.RPMTAMT > 0
	AND A.BRCD = B.BRCD
	AND A.BRCDLN = C.BRCD
	AND A.CUSTSEQLN = C.CUSTSEQ
	--AND LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, '', 'IND') = 'Y'
	AND SUBSTR(C.CUSTTPCD,1,1) <> '1'
GROUP BY
	A.BRCD, B.LCLBRNM, A.DEPTCD, A.CUSTSEQLN, C.NMLOC,
	A.DSBSID, A.DSBSSEQ, A.DSBSDT, A.MATDT, A.LNTPCD, A.FNDPRPSTPCD, A.FNDPRPSUNIT, A.CCYCD, A.LNSBTPCD, D.TRDT
ORDER BY
	A.BRCD, A.CUSTSEQLN, A.DSBSSEQ

