--define h_trdt = '20121002'
SELECT
	SUBSTR(A.CODE,1,4) BRCD,
	D.LCLBRNM CHI_NHANH,
	B.CUSTSEQ CIF,
	C.SHRTNM KHACH_HANG,
	A.CODE SO_KHE_UOC,
	E.APPRSEQ SO_HOP_DONG,
	E.DSBSDT NGAY_GIAI_NGAN,
	E.MATDT NGAY_DAO_HAN,
	E.DSBSAMT SO_TIEN_GN,
	E.CCYCD LOAI_TIEN,
	E.DSBSBAL DU_NO,
	DECODE(E.CCYCD, 'VND', E.DSBSBAL, CS1.EXCROSSCAL (E.BRCD, 'VND', E.BKDT, E.CCYCD, E.DSBSBAL, '01', 'VND', '01')) DU_NO_VND,
	SUBSTR(E.LNSBTPCD, 2,1) NHOM_NO,
	ACRAMT DU_THU,
	BCEQA DU_THU_VND,
	ACRFMDT DU_THU_TU,
	ACRTODT DU_THU_DEN,
	B.INTRT LAI_SUAT,
	DECODE(ACRFMDT,'00000000',0,TO_DATE(ACRTODT,'YYYYMMDD') - TO_DATE(ACRFMDT,'YYYYMMDD')+1) SO_NGAY_DU_THU

FROM
	(SELECT CODE
	FROM LN1.TBLN_TCODELN X
	WHERE STSCD = '01'
	AND NVL(UPDTTPCD,'00') = '03'
	AND SEQ = (SELECT MAX(SEQ) FROM LN1.TBLN_TCODELN WHERE BRCD = X.BRCD AND CODE = X.CODE)
	)A, GL1.TBGL_STLDD B, TBCM_GENERAL C, TBCS_BRCD D, LN1.TBLN_DSBSHIST E
WHERE
	B.TRDT = &h_trdt
	AND B.BUSCD = 'LN'
	AND SUBSTR(B.ACRPAC,1,1)='2'
	AND B.TRDRCR = 'C'
	AND SUBSTR(A.CODE,1,4) = B.BRCD
	AND SUBSTR(A.CODE,5,3) = B.TRREF
	AND SUBSTR(A.CODE,8,9) = B.TRSEQ
	AND B.BRCD = C.BRCD
	AND B.CUSTSEQ = C.CUSTSEQ
	AND B.BRCD = D.BRCD
	AND E.BKDT = &h_trdt
	AND B.BRCD = E.BRCD
	AND B.TRREF = E.DSBSID
	AND B.TRSEQ = E.DSBSSEQ
ORDER BY BRCD, CIF
