--define h_trdt = '20110216'

SELECT
	BRCD CHI_NHANH,
	LCLBRNM TEN_CN,
	CUSTSEQLN CIF,
	SHRTNM TEN_KH,
	LNSBTPCD NHOM_NO_HIEN_TAI,
	PSTAMT DOANH_SO_NQH,
	DSBSBAL DUNO_VND,
	RATE TY_LE
FROM
(
	SELECT
		B.BRCD,
		D.LCLBRNM,
		B.CUSTSEQLN,
		E.SHRTNM,
		B.DSBSSEQ,
		SUM(CS1.EXCROSSCAL(B.BRCD, 'VND', &h_trdt, B.CCYCD, NVL(B.PSTAMT,0), '01', 'VND', '01')) PSTAMT,
		A.DSBSBAL DSBSBAL,
		SUBSTR(F.LNSBTPCD,2,1) LNSBTPCD,
		ROUND(SUM(CS1.EXCROSSCAL(B.BRCD, 'VND', &h_trdt, B.CCYCD,
				NVL(B.PSTAMT,0), '01', 'VND', '01'))/A.DSBSBAL * 100,2) RATE
	FROM LN1.TBLN_PSTADMLN B, CS1.TBCS_BRCD D, CM1.TBCM_GENERAL E,
		( SELECT BRCDLN, CUSTSEQLN,
			SUM(CS1.EXCROSSCAL(BRCD, 'VND', &h_trdt, CCYCD, DSBSBAL, '01', 'VND', '01')) DSBSBAL
		 FROM LN1.TBLN_DSBSHIST
		 WHERE
		     BKDT = &h_trdt
			 AND BUSCD = 'LN'
			 AND STSCD = '01'
			 AND NVL(DSBSBAL,0) > 0
		GROUP BY BRCDLN, CUSTSEQLN ) A, LN1.TBLN_DSBS F
	WHERE
		B.TRDT BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt,'YYYYMMDD'), -3), 'YYYYMMDD') AND &h_trdt
		AND B.CNTPSTDAY < 10
		AND B.PSTTPCD IN ('01', '02')
		AND B.TRDT = (SELECT MAX(TRDT)
					FROM LN1.TBLN_PSTADMLN
					WHERE
						TRDT BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt,'YYYYMMDD'), -3), 'YYYYMMDD') AND &h_trdt
						AND CNTPSTDAY < 10
						AND PSTTPCD IN ('01','02')
						AND PSTTPCD = B.PSTTPCD
						AND PSTDT = B.PSTDT
						AND BRCD = B.BRCD
						AND DSBSSEQ = B.DSBSSEQ
					)
		AND B.BRCD = A.BRCDLN(+)
		AND B.CUSTSEQLN = A.CUSTSEQLN(+)
		AND NVL(A.DSBSBAL,0) > 0

		AND B.BRCD = F.BRCD
		AND F.DSBSID = 'LDS'
		AND B.DSBSSEQ = F.DSBSSEQ
		AND F.STSCD = '01'
		AND F.BUSCD = 'LN'
		AND F.DSBSBAL > 0

		AND B.BRCD = D.BRCD
		AND B.BRCD = E.BRCD
		AND B.CUSTSEQLN = E.CUSTSEQ
	GROUP BY B.BRCD, D.LCLBRNM, B.CUSTSEQLN, E.SHRTNM, F.LNSBTPCD, A.DSBSBAL
)
WHERE RATE > 30  -- > DOANH SO NQH > 30% DU NO
ORDER BY BRCD, CUSTSEQLN, SHRTNM


