-- DEFINE h_trdt = '20110730'

SELECT
	ITEM1, ITEM2,
	SUM(T0) T0,
	SUM(T1) T1,
	SUM(T2) T2,
	SUM(T3) T3,
	SUM(T4) T4,
	SUM(T5) T5,
	SUM(T6) T6,
	SUM(T7) T7,
	SUM(T8) T8,
	SUM(T9) T9,
	SUM(T10) T10,
	SUM(T11) T11,
	SUM(TC) TONG_CONG
FROM
(
	SELECT
		DECODE(SUBSTR(A.FNDPRPSUNIT, 1, 2), '01', 'I. Xu t kh»u', '02', 'II. NhÀp kh»u') ITEM1,
		DECODE(LNTPCD,
			'100', '1. Ngæn hπn', '300', '1. Ngæn hπn', '105', '1. Ngæn hπn',
			'160', '1. Ngæn hπn', '163', '1. Ngæn hπn', '166', '1. Ngæn hπn',
			'510', '1. Ngæn hπn',
			'2. Trung, dµi hπn') ITEM2,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(&h_trdt, 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T0,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 1),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T1,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 2),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T2,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 3),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T3,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 4),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T4,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 5),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T5,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 6),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T6,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 7),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T7,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 8),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T8,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 9),  'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T9,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 10), 'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T10,
		DECODE(SUBSTR(C.RPMTSCHDDT, 1, 6), SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 11), 'YYYYMMDD'), 1, 6), C.RPMTSCHDAMT - C.RPMTAMT) T11,
		(C.RPMTSCHDAMT - C.RPMTAMT) TC
	FROM
		LN1.TBLN_DSBS A, LN1.TBLN_SCHDMAS B, LN1.TBLN_SCHDSB C
	WHERE
		C.RPMTSCHDDT	BETWEEN &h_trdt AND TO_CHAR(LAST_DAY(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'), 11)), 'YYYYMMDD')
		AND A.BRCD			= B.BRCDDSBS
		AND A.DSBSID		= B.DSBSID
		AND A.DSBSSEQ		= B.DSBSSEQ
		AND B.BRCD			= C.BRCD
		AND B.RPMTSCHDID	= C.RPMTSCHDID
		AND B.RPMTSCHDSEQ	= C.RPMTSCHDSEQ
		AND A.STSCD			= '01'
		AND TRIM(LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||SUBSTR(A.FNDPRPSUNIT, 1, 2), 'DECODE')) IN
			('Tµi trÓ xu t kh»u', 'Tµi trÓ nhÀp kh»u')
		AND A.CCYCD			= 'VND'
		AND A.BUSCD			= 'LN'
		AND B.STSCD			= '01'
		AND C.RPMTAMT		<> C.RPMTSCHDAMT
)
GROUP BY
	ITEM1, ITEM2
ORDER BY
	ITEM1, ITEM2