--DEFINE h_trdt = '20100104'

SELECT
	ITEM1 KY_HAN_VAY, ITEM NHOM_NO,
	BRCD, CUSTSEQ, SHRTNMLOC KHACH_HANG, CCY,
	SUM(DRAMT) DOANH_SO_NO, SUM(CRAMT) DOANH_SO_CO
FROM
(
	SELECT
		DECODE(SUBSTR(A.ACCTCD, 1, 3), '212', 'II.TRUNG HAN',
					  '213', 'III.DAI HAN',
					  'I.NGAN HAN') ITEM1,
	   	DECODE(SUBSTR(A.ACCTCD, 4, 1),
	   				'2', '1.NO CAN CHU Y',
	   				'3', '2.NO DUOI TIEU CHUAN',
			   	  	'4', '3.NO NGHI NGO',
					'5', '4.NO CO KHA NANG MAT VON'
		) ITEM,
		A.BRCD,
	   	B.CUSTSEQ CUSTSEQ,  B.SHRTNMLOC SHRTNMLOC,
	   	SUM(A.DRAMT) DRAMT, SUM(A.CRAMT) CRAMT,
	   	A.CCY CCY, A.ACCTCD ACCTCD
	FROM
		TBGL_MAST A, TBCM_GENERAL B
	WHERE
		A.TRDT BETWEEN LN1.GET_BUSDAYCAL('%', &h_trdt, -1, '1') AND &h_trdt
		AND A.BRCD = B.BRCD
		AND A.CUSTSEQ = B.CUSTSEQ
		AND SUBSTR(A.ACCTCD,1,3) IN ( '201', '203', '205',
						 '211', '221', '222', '223', '231', '241',
						 '251', '252', '253', '271', '272',
						 '273', '275',
						 '212', '213', '201')
		AND SUBSTR(A.ACCTCD,4,1) <> '1'
		AND (A.DRAMT > 0 OR A.CRAMT > 0)
	GROUP BY
		B.SHRTNMLOC,A.CCY,A.BRCD, B.CUSTSEQ, A.ACCTCD

	UNION ALL

	SELECT
		'IV.NO KHOANH, NO CHO XU LY' ITEM1,
		DECODE(SUBSTR(A.ACCTCD, 1, 2), '28', '1.NGAN HAN',
				DECODE(ACCTCD, '291000', '1.NGAN HAN',
			     	               '292000', '2.TRUNG HAN',
			     	               '293000', '3.DAI HAN')
		)ITEM,
		A.BRCD,
		B.CUSTSEQ CUSTSEQ, B.SHRTNMLOC SHRTNMLOC,
		SUM(A.DRAMT) DRAMT, SUM(A.CRAMT) CRAMT,
		A.CCY CCY, A.ACCTCD ACCTCD
	FROM
	 	TBGL_MAST A,TBCM_GENERAL B
	WHERE
		A.TRDT BETWEEN LN1.GET_BUSDAYCAL('%', &h_trdt, -1, '1') AND &h_trdt
		AND A.BRCD = B.BRCD
		AND A.CUSTSEQ = B.CUSTSEQ
		AND SUBSTR(A.ACCTCD, 1, 2) IN ('28', '29')
		AND (A.DRAMT > 0 OR A.CRAMT > 0)
	GROUP BY
		B.SHRTNMLOC, A.BRCD, B.CUSTSEQ, A.CCY, A.ACCTCD
)
WHERE
	(DRAMT > 0 OR CRAMT > 0)
GROUP BY
	BRCD,ITEM1, ITEM, SHRTNMLOC, CUSTSEQ, CCY
