--define h_trdt = '20120926'
SELECT
	A.BRCD CHI_NHANH,
	C.LCLBRNM TEN_CN,
	A.CUSTSEQLN CIF,
	B.NMLOC TEN_KH,
	A.APPRSEQ SO_HOP_DONG,
	LN1.GET_APPRDT(A.BRCD, A.APPRID, A.APPRSEQ) NGAY_HOP_DONG,
	A.CCYCD LOAI_TIEN,
	A.APPRAMT GIA_TRI,
	A.DSBSTRMLMT NGAY_HET_HAN_GIAI_NGAN

FROM
	LN1.TBLN_APPR A, CM1.TBCM_GENERAL B, CS1.TBCS_BRCD C
WHERE
	A.STSCD = '01'
	AND A.CRDTLINETPCD = '01'
	AND A.DSBSTRMLMT BETWEEN &h_trdt AND TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt, 'YYYYMMDD'),1), 'YYYYMMDD')
	AND A.BRCD = B.BRCD
	AND A.CUSTSEQLN = B.CUSTSEQ
	AND A.BRCD = C.BRCD
ORDER BY A.BRCD, A.CUSTSEQLN, A.APPRSEQ
