-- DEFINE h_trdt = '20100405'

SELECT
	&h_trdt TRDT, KHACH_HANG, CCYCD, SUM(DUNG_HAN) DUNG_HAN, SUM(TRUOC_HAN) TRUOC_HAN, SUM(TRE_HAN) TRE_HAN
FROM
(
	SELECT /*+ INDEX (A PKLN_RPMT) */
		DECODE(LN1.CHK_LNCUSTTP(A.BRCDDSBS, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND'), 'Y', 'CA NHAN', 'DOANH NGHIEP') KHACH_HANG,
		C.CCYCD,
		DECODE(SIGN(B.RPMTSCHDDT - A.TRDT), 0, B.RPMTAMT) DUNG_HAN,
		DECODE(SIGN(B.RPMTSCHDDT - A.TRDT), 1, B.RPMTAMT) TRUOC_HAN,
		DECODE(SIGN(B.RPMTSCHDDT - A.TRDT), -1, B.RPMTAMT) TRE_HAN
	FROM
		LN1.TBLN_RPMT A, LN1.TBLN_RPMTDTL B, LN1.TBLN_DSBS C
	WHERE
		A.TRDT = &h_trdt
		AND A.BRCD = B.BRCD
		AND A.RPMTID = B.RPMTID
		AND A.RPMTSEQ = B.RPMTSEQ
		AND A.STSCD = '01'
		AND A.ACMODE = 0
		AND A.BRCDDSBS = C.BRCD
		AND A.DSBSID = C.DSBSID
		AND A.DSBSSEQ = C.DSBSSEQ
		AND NVL(B.RPMTAMT, 0) > 0
		AND C.CCYCD IN ('VND', 'USD')
)
GROUP BY
	KHACH_HANG, CCYCD
