--define h_trdt = '20121030'
SELECT DISTINCT
	A.BRCD, CUSTSEQLN CIF, NMLOC TEN_KH,
	APPRSEQ HOP_DONG, CODE KHE_UOC, A.TRDT NGAY_CO_CAU,
	MAX(TP) LOAI_CO_CAU,
	SUBSTR(LNSBTPCD,2,1) NHOM_NO,
	LN1.GET_TCODE('LNLNTPCD', 'CC', LNTPCD, 'DECODE') LOAN_TERM,
	CCYCD LOAI_TIEN, DSBSBAL DU_NO,
	CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, CCYCD, DSBSBAL, '01', 'VND', '01') DU_NO_VND,
	RPMTDT_BFR NGAY_TRA_GOC_TRUOC, INTDT_BFR NGAY_TRA_LAI_TRUOC,
	RPMTDT_AFT NGAY_TRA_GOC_SAU, INTDT_AFT NGAY_TRA_LAI_SAU,
	RPMTDT_CUR NGAY_TRA_GOC_HIEN_TAI, INTDT_CUR NGAY_TRA_LAI_HIEN_TAI
FROM
(
	/* RESCHEDULE (INTEREST) */
	SELECT DISTINCT
		D.BRCD, D.APPRSEQ, D.CUSTSEQLN, A.CODE, A.TRDT, D.LNTPCD, D.LNSBTPCD,
		C.INTPYMNTINTVMM, C.NXTRPMTSCHDDT RPMTDT_BFR, C.NXTINTSCHDDT INTDT_BFR,
		B.INTPYMNTINTVMM, B.NXTRPMTSCHDDT RPMTDT_AFT, B.NXTINTSCHDDT INTDT_AFT,
		D.NXTRPMTSCHDDT RPMTDT_CUR, D.NXTINTSCHDDT INTDT_CUR,
		D.CCYCD, D.DSBSBAL, '00-RESCHEDULE' TP
	FROM
		LN1.TBLN_TCODELN A, LN1.TBLN_DSBSHIST B, LN1.TBLN_DSBSHIST C, TBLN_DSBS D
	WHERE
		NVL(UPDTTPCD,'00') = '03'
		AND A.TRDT = (SELECT MAX(TRDT) FROM LN1.TBLN_TCODELN WHERE BRCD = A.BRCD AND CODE = A.CODE)
		AND A.TRDT = B.BKDT
		AND SUBSTR(A.CODE,1,4) = B.BRCD
		AND SUBSTR(A.CODE,5,3) = B.DSBSID
		AND SUBSTR(A.CODE,8,9) = B.DSBSSEQ
		AND C.BKDT =  LN1.GET_BUSDAYCAL(B.BRCD, B.BKDT, -1, 1)
		AND C.BRCD = B.BRCD
		AND C.DSBSID = B.DSBSID
		AND C.DSBSSEQ = B.DSBSSEQ
		AND B.INTPYMNTINTVMM <> C.INTPYMNTINTVMM
		AND C.BRCD = D.BRCD
		AND C.DSBSID = D.DSBSID
		AND C.DSBSSEQ = D.DSBSSEQ
		AND D.STSCD = '01'

	UNION ALL

	/* MATURITY */
	SELECT DISTINCT
		D.BRCD, D.APPRSEQ, D.CUSTSEQLN, A.CODE, A.TRDT, D.LNTPCD, D.LNSBTPCD,
		C.INTPYMNTINTVMM, C.NXTRPMTSCHDDT RPMTDT_BFR, C.NXTINTSCHDDT INTDT_BFR,
		B.INTPYMNTINTVMM, B.NXTRPMTSCHDDT RPMTDT_AFT, B.NXTINTSCHDDT INTDT_AFT,
		D.NXTRPMTSCHDDT RPMTDT_CUR, D.NXTINTSCHDDT INTDT_AFT,
		D.CCYCD, D.DSBSBAL, '99-MATURITY' TP
	FROM
		LN1.TBLN_TCODELN A, LN1.TBLN_DSBSHIST B, LN1.TBLN_DSBSHIST C, TBLN_DSBS D
	WHERE
		NVL(UPDTTPCD,'00') = '03'
		AND A.TRDT = (SELECT MAX(TRDT) FROM LN1.TBLN_TCODELN WHERE BRCD = A.BRCD AND CODE = A.CODE)
		AND A.TRDT = B.BKDT
		AND SUBSTR(A.CODE,1,4) = B.BRCD
		AND SUBSTR(A.CODE,5,3) = B.DSBSID
		AND SUBSTR(A.CODE,8,9) = B.DSBSSEQ
		AND C.BKDT =  LN1.GET_BUSDAYCAL(B.BRCD, B.BKDT, -1, 1)
		AND C.BRCD = B.BRCD
		AND C.DSBSID = B.DSBSID
		AND C.DSBSSEQ = B.DSBSSEQ
		AND B.MATDT <> C.MATDT
		AND C.BRCD = D.BRCD
		AND C.DSBSID = D.DSBSID
		AND C.DSBSSEQ = D.DSBSSEQ
		AND D.STSCD = '01'

	UNION ALL

	/* RESCHEDULE */
	SELECT DISTINCT
		D.BRCD, D.APPRSEQ, D.CUSTSEQLN, A.CODE, A.TRDT, D.LNTPCD, D.LNSBTPCD,
		C.INTPYMNTINTVMM, C.NXTRPMTSCHDDT RPMTDT_BFR, C.NXTINTSCHDDT INTDT_BFR,
		B.INTPYMNTINTVMM, B.NXTRPMTSCHDDT RPMTDT_AFT, B.NXTINTSCHDDT INTDT_AFT,
		D.NXTRPMTSCHDDT RPMTDT_CUR, D.NXTINTSCHDDT INTDT_AFT,
		D.CCYCD, D.DSBSBAL, '00-RESCHEDULE' TP
	FROM
		LN1.TBLN_TCODELN A, LN1.TBLN_DSBSHIST B, LN1.TBLN_DSBSHIST C,
		TBLN_DSBS D, TBLN_SCHDMAS E, TBLN_SCHDMAS F
	WHERE
		NVL(UPDTTPCD,'00') = '03'
		AND A.TRDT = (SELECT MAX(TRDT) FROM LN1.TBLN_TCODELN WHERE BRCD = A.BRCD AND CODE = A.CODE)
		AND A.TRDT = B.BKDT
		AND SUBSTR(A.CODE,1,4) = B.BRCD
		AND SUBSTR(A.CODE,5,3) = B.DSBSID
		AND SUBSTR(A.CODE,8,9) = B.DSBSSEQ
		AND C.BKDT =  LN1.GET_BUSDAYCAL(B.BRCD, B.BKDT, -1, 1)
		AND C.BRCD = B.BRCD
		AND C.DSBSID = B.DSBSID
		AND C.DSBSSEQ = B.DSBSSEQ
		AND C.BRCD = D.BRCD
		AND C.DSBSID = D.DSBSID
		AND C.DSBSSEQ = D.DSBSSEQ
		AND D.STSCD = '01'
		AND D.BRCD = E.BRCDDSBS
		AND D.DSBSID = E.DSBSID
		AND D.DSBSSEQ = E.DSBSSEQ
		AND E.BRCDDSBS = F.BRCDDSBS
		AND E.DSBSID = F.DSBSID
		AND E.DSBSSEQ = F.DSBSSEQ
		AND TO_CHAR(E.LSTUPDTDT, 'YYYYMMDD') = A.TRDT
		AND TO_CHAR(F.LSTUPDTDT, 'YYYYMMDD') = (SELECT MAX(TO_CHAR(LSTUPDTDT, 'YYYYMMDD'))
		                                         FROM TBLN_SCHDMAS
		                                         WHERE BRCDDSBS = E.BRCDDSBS
		                                         AND DSBSID = E.DSBSID
		                                         AND DSBSSEQ = E.DSBSSEQ
		                                         AND TO_CHAR(LSTUPDTDT, 'YYYYMMDD') < TO_CHAR(E.LSTUPDTDT, 'YYYYMMDD')
												)
		AND (E.RPMTPROGCD <> F.RPMTPROGCD OR E.PARRPMTMTHDCD <> F.PARRPMTMTHDCD
			OR E.INSTSUM <> F.INSTSUM OR E.INSTINTVMM <> F.INSTINTVMM  OR E.INSTDT <> F.INSTDT)
) A, TBCM_GENERAL B
WHERE A.BRCD = B.BRCD
AND A.CUSTSEQLN = B.CUSTSEQ
AND A.TRDT = (SELECT MAX(TRDT) FROM LN1.TBLN_TCODELN WHERE BRCD = A.BRCD AND CODE = A.CODE)
GROUP BY
	A.BRCD, CUSTSEQLN, NMLOC ,
	APPRSEQ , CODE , A.TRDT ,
	CCYCD , DSBSBAL ,
	RPMTDT_BFR , INTDT_BFR ,
	RPMTDT_AFT , INTDT_AFT ,
	RPMTDT_CUR , INTDT_CUR, LNTPCD, LNSBTPCD
ORDER BY BRCD, APPRSEQ, CODE

