--DEFINE h_trdt='20120718'

SELECT
	A.BRCD,
	A.DEPTCD,
	C.DEPTNM,
	A.CUSTSEQLN,
	B.NMLOC,
	SUBSTR(A.LNSBTPCD,2,1) GRP,
	A.TP,
	BAL_A BAL_A,
	BAL_I BAL_I,
	(CASE WHEN A.TP = 'Mortgage' THEN
		CASE WHEN BAL_A >= 20000000000 THEN BAL_A
			ELSE CASE WHEN BAL_I > 20000000000 THEN  20000000000 ELSE BAL_I END
		END
	ELSE
		CASE WHEN BAL_A >= 5000000000 THEN BAL_A
			ELSE CASE WHEN BAL_I > 5000000000 THEN  5000000000 ELSE BAL_I END
		END
	END) BAL_N,
	DECODE(SUBSTR(CUSTTPCD,1,1),'1','Individual','Corporation') CUSTTP,
	LSTDSBSDT LSTDSBSDT
FROM
(
	SELECT
			BRCD, DEPTCD, CUSTSEQLN, LNSBTPCD, TP,
			SUM(BAL_A) BAL_A, SUM(BAL_I) BAL_I, MAX(LSTDSBSDT) LSTDSBSDT
	FROM
	(
		SELECT
			BRCD, DEPTCD, CUSTSEQLN, LNSBTPCD, TP,
			DECODE(SIGN(TO_NUMBER(APPRDT)-TO_NUMBER('20110718')),-1,BAL,0) BAL_A,
			BAL BAL_I, LSTDSBSDT
		FROM
		(
			SELECT
				BRCD,DEPTCD,CUSTSEQLN,LNSBTPCD,'Mortgage' TP
				,LN1.GET_APPRDT(BRCD,APPRID,APPRSEQ) APPRDT
				,SUM(DECODE(CCYCD,'VND',DSBSBAL,CS1.excrosscal (BRCD, 'VND', &h_trdt, CCYCD, DSBSBAL, '01', 'VND', '01'))) BAL
				,MAX(DSBSDT) LSTDSBSDT
			FROM
				LN1.TBLN_DSBSHIST
			WHERE
				BKDT = &h_trdt
				AND STSCD='01'
				AND BUSCD='LN'
				AND DEPTCD LIKE '%O'
				AND DEPTCD NOT IN ('MHO','T1O', 'BNO')
				AND LNTPCD IN ('105','115')
			GROUP BY
				BRCD, DEPTCD, CUSTSEQLN, LNSBTPCD, APPRID, APPRSEQ

			UNION ALL

			SELECT
				BRCD,DEPTCD,CUSTSEQLN,LNSBTPCD,'Others' TP
				,LN1.GET_APPRDT(BRCD,APPRID,APPRSEQ) APPRDT
				,SUM(DECODE(CCYCD,'VND',DSBSBAL,CS1.excrosscal (BRCD, 'VND', &h_trdt, CCYCD, DSBSBAL, '01', 'VND', '01'))) BAL
				,MAX(DSBSDT)
			FROM
				LN1.TBLN_DSBSHIST
			WHERE
				BKDT = &h_trdt
				AND STSCD='01'
				AND BUSCD='LN'
				AND DEPTCD LIKE '%O'
				AND DEPTCD NOT IN ('MHO','T1O', 'BNO')
				AND LNTPCD NOT IN ('105','115')
			GROUP BY
				BRCD,DEPTCD,CUSTSEQLN ,LNSBTPCD, APPRID, APPRSEQ
		)
	)
	GROUP BY BRCD, DEPTCD, LNSBTPCD, TP, CUSTSEQLN, LNSBTPCD
) A,TBCM_GENERAL B,TBCS_DEPTCD C
WHERE
	A.BRCD=B.BRCD
	AND A.CUSTSEQLN=B.CUSTSEQ
	AND A.DEPTCD=C.DEPTCD
ORDER BY C.DEPTNM ,CUSTSEQLN,TP

  
