--DEFINE h_trdt = '20091216'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT
	A.BRCD, A.CCYCD, A.CUSTSEQLN, B.NMLOC KHACH_HANG,
	SUM(A.DSBSBAL) DU_NO,
	SUM(A.DSBSBAL_VND) DU_NO_QUY_DOI
FROM
(
	SELECT
		D.BRCD,
		D.CUSTSEQLN,
		D.CCYCD,
		D.DSBSBAL,
		CS1.EXCROSSCAL(D.BRCD, 'VND', &h_trdt, D.CCYCD, NVL(D.DSBSBAL,0), '01', 'VND', '01') DSBSBAL_VND
	FROM
		LN1.TBLN_DSBSHIST D
	WHERE
		D.BKDT 		= &h_trdt
		AND D.BUSCD = 'LN'
		AND D.STSCD = '01'
		AND LN1.CHK_LNCUSTTP(D.BRCD, D.DSBSID, D.DSBSSEQ, D.CUSTSEQLN, 'ind') = 'Y'

	UNION ALL

	SELECT
		A.BRCD,
		A.CUSTSEQ,
		A.CCY,
		A.TDBAL,
		CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCY, NVL(A.TDBAL,0), '01', 'VND', '01') TDBAL_VND
	FROM
		GL1.TBGL_MAST A
	WHERE
		A.TRDT = &h_trdt
		AND A.BRCD <> '1000'
		AND A.ACCTCD LIKE '2%'
		AND SUBSTR(A.ACCTCD, 1, 3)  NOT IN ('211', '212', '213', '222', '223', '241', '271')
		AND SUBSTR(A.ACCTCD, 3, 1) 	NOT IN ('7', '9')
		AND A.TDBAL 		> 	0
		AND LN1.CHK_LNCUSTTP(A.BRCD, '', '', A.CUSTSEQ, 'ind') = 'Y'
		AND LN1.CHKACCT20SBV(A.ACCTCD, A.CCY) = 'N'
	) A, TBCM_GENERAL B
WHERE
	A.BRCD = B.BRCD (+)
	AND A.CUSTSEQLN = B.CUSTSEQ (+)
GROUP BY
	A.BRCD, A.CCYCD, A.CUSTSEQLN, B.NMLOC
