--define h_trdt = '20111007'

SELECT 	A.BRCD CHI_NHANH, A.CUSTSEQLN CIF, C.SHRTNM TEN_KH,
		A.APPRSEQ SO_HOP_DONG, A.DSBSSEQ SO_KHE_UOC,
		A.DSBSDT NGAY_GIAI_NGAN, A.MATDT NGAY_DAO_HAN,
		LN1.GET_TCODE('LNFNDPRPSTPCD', 'CC', A.FNDPRPSTPCD, 'DECODE') MUC_DICH_VAY_CAP2, A.CCYCD LOAI_TIEN,
		A.DSBSAMT SO_TIEN_GN,
		DECODE(A.CCYCD, 'VND', A.DSBSAMT, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSAMT,'01','VND','01')) SO_TIEN_GN_VND,
		A.DSBSBAL DU_NO,
		DECODE(A.CCYCD, 'VND', A.DSBSBAL, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSBAL,'01','VND','01')) DU_NO_VND,
		B.PLGAMT GIA_TRI_TS, B.PLGAMT_VND GIA_TRI_TS_VND
FROM TBLN_DSBS A,
	(SELECT
			BRCDAPPR, APPRID, APPRSEQ, SUM(PLGAMT) PLGAMT,
			SUM(DECODE(CCYCD, 'VND', PLGAMT, CS1.EXCROSSCAL(BRCD, 'VND', &h_trdt, CCYCD, PLGAMT,'01','VND','01'))) PLGAMT_VND
		FROM
			LN1.TBLN_PLG
		WHERE
			BUSCD = 'LN'
			AND NVL(PLGTRDT, PLGDT) <= &h_trdt
			AND STSCD IN('01','03')
			AND CCYCD = 'GD1'
		GROUP BY BRCDAPPR, APPRID, APPRSEQ) B, TBCM_GENERAL C
WHERE
	A.BRCD LIKE '%'
	AND A.STSCD IN ('01','05')
	AND A.BUSCD = 'LN'
	AND A.DSBSID = 'LDS'
	AND A.DSBSDT BETWEEN SUBSTR(&h_trdt,1,4)||'0101' AND &h_trdt

	AND A.BRCD = B.BRCDAPPR
	AND A.APPRID = B.APPRID
	AND A.APPRSEQ = B.APPRSEQ

	AND A.BRCDLN = C.BRCD
	AND A.CUSTSEQLN = C.CUSTSEQ

	AND LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND') = 'Y'

ORDER BY A.BRCD, A.CUSTSEQLN
