--DEFINE h_trdt = '20120911'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT
		A.CUSTDTLTPCD THANH_PHAN_KH,
		SUM(A.TDBAL_FRDT) DU_NO_FRDT,
		SUM(A.TDBAL_QH_FRDT) DU_NO_QH_FRDT,
		SUM(A.CNT_FRDT) SO_KH_FRDT,
		SUM(A.CNT_QH_FRDT) SO_KH_QH_FRDT,
		SUM(A.TDBAL_TODT) DU_NO_TODT,
		SUM(A.TDBAL_QH_TODT) DU_NO_QH_TODT,
		SUM(A.CNT_TODT) SO_KH_TODT,
		SUM(A.CNT_QH_TODT) SO_KH_QH_TODT
FROM
	(SELECT
			BRCD, CUSTDTLTPCD,
			CUSTSEQ, SHRTNM,
			TDBAL TDBAL_FRDT, TDBAL_QH TDBAL_QH_FRDT,
			COUNT(CUSTSEQ) CNT_FRDT,
			DECODE(TDBAL_QH, 0, 0, COUNT(CUSTSEQ)) CNT_QH_FRDT,
			0 TDBAL_TODT, 0 TDBAL_QH_TODT,
			0 CNT_TODT, 0 CNT_QH_TODT
	FROM
		(SELECT
			A.BRCD, A.CUSTDTLTPCD, A.CUSTSEQ,
			SUM(DECODE(A.CCY, 'VND', A.TDBAL,
				CS1.EXCROSSCAL(A.BRCD, 'VND', '20081231', A.CCY, NVL(A.TDBAL,0), '01', 'VND', '01'))) TDBAL,
			SUM(DECODE(A.CCY, 'VND', A.TDBAL_QH,
				CS1.EXCROSSCAL(A.BRCD, 'VND', '20081231', A.CCY, NVL(A.TDBAL_QH,0), '01', 'VND', '01'))) TDBAL_QH,
			B.SHRTNM
		FROM
			(SELECT
				LN1.BRCDCONVERT(A.BRCD, '0') BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.LDRBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.LDRBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(D.LNTPCD, '105', '07. CA NHAN-KD VANG', '115', '07. CA NHAN-KD VANG', DECODE(A.CUSTSEQ, '100265300', '07. CA NHAN-KD VANG',
													DECODE(D.FNDPRPSTPCD, '09002', '08. CA NHAN-DUHOC', '09007', '08. CA NHAN-DUHOC',
																DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN')))),
								'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
												'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_BALDD A, CM1.TBCM_GENERAL C, LN1.TBLN_DSBS D
			WHERE
				A.TRDT 		= 	'20081231'
				AND A.BRCD 		LIKE 	 '%'
				AND A.BRCD <> LN1.BRCDCONVERT(A.BRCD, 'Y')
				AND A.ACCTCD 	LIKE 	'2%'
				AND SUBSTR(A.ACCTCD, 3, 1) 	<> '9'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '217'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '275'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '221'
				AND A.BUSCD 		=  'LN'
				AND A.LDRBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND D.BRCD	=   LN1.BRCDCONVERT(A.BRCD, '0')
				AND A.TRREF 	= 	D.DSBSID
				AND A.TRSEQ 	= 	D.DSBSSEQ
				AND		D.STSCD IN ('01', '05')
			GROUP BY
				A.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD, C.CUSTTPCD, D.LNTPCD, D.FNDPRPSTPCD, A.ACCTCD

			UNION ALL

			SELECT
				B.BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.LDRBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.LDRBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN'),	'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
											'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_BALDD A, CM1.TBCM_GENERAL C, LN1.TBLN_LNIDSEQ B, LN1.TBLN_DSBS D
			WHERE
				A.TRDT 		= 	'20081231'
				AND B.BRCD 		LIKE 	 '%'
				AND A.ACCTCD 	LIKE 	'2%'
				AND SUBSTR(A.ACCTCD, 3, 1) <> '9'
				AND SUBSTR(A.ACCTCD, 1, 3) <> '217'
				AND SUBSTR(A.ACCTCD, 1, 3) <> '275'
				AND SUBSTR(A.ACCTCD, 1, 3) <> '221'
				AND A.BUSCD 	= 	'LN'
				AND A.LDRBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND A.BRCD 		= 	B.BRCDOLD
				AND A.TRREF 	= 	B.ID
				AND A.TRSEQ 	= 	B.SEQOLD
				AND B.BRCD 		= 	D.BRCD
				AND B.ID		= 	D.DSBSID
				AND B.SEQ 		= 	D.DSBSSEQ
				AND	D.STSCD IN ('01','05')
			GROUP BY
				B.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD, C.CUSTTPCD, A.ACCTCD

			UNION ALL

			SELECT
				DECODE(SUBSTR(A.ACCTCD, 1, 3), '282', A.BRCD, '289', A.BRCD, LN1.BRCDCONVERT(A.BRCD, '0')) BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.TDBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.TDBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN'),	'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
												'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_MAST A, CM1.TBCM_GENERAL C
			WHERE
				A.TRDT 		= 	'20081231'
				AND A.BRCD 	LIKE 	 '%'
				AND A.BRCD <> LN1.BRCDCONVERT(A.BRCD, 'Y')
				AND A.ACCTCD LIKE '2%'
				AND SUBSTR(A.ACCTCD, 1, 3) NOT IN('211', '212', '213', '222', '223', '241', '271')
				AND 'Y' = 'Y'
				AND SUBSTR(A.ACCTCD, 3, 1) 	NOT IN ('7', '9')
				AND A.CUSTSEQ 	LIKE 	 '%'
				AND A.TDBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND LN1.CHKACCT20SBV(A.ACCTCD, A.CCY) = 'N'
			GROUP BY A.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD,C.CUSTTPCD, A.ACCTCD
			) A, CM1.TBCM_GENERAL B
		WHERE
			A.BRCD 		= B.BRCD
			AND A.CUSTSEQ 	= B.CUSTSEQ
		GROUP BY
			A.BRCD, A.CUSTSEQ, A.CUSTDTLTPCD, B.SHRTNM
		)
	GROUP BY
		BRCD,CUSTDTLTPCD,CUSTSEQ,TDBAL,TDBAL_QH,SHRTNM

	UNION ALL

	SELECT
		BRCD, CUSTDTLTPCD,
		CUSTSEQ, SHRTNM,
		0 TDBAL_FRDT, 0 TDBAL_QH_FRDT,
		0 CNT_FRDT, 0 CNT_QH_FRDT,
		TDBAL TDBAL_TODT, TDBAL_QH TDBAL_QH_TODT,
		COUNT(CUSTSEQ) CNT_TODT,
		DECODE(TDBAL_QH, 0, 0, COUNT(CUSTSEQ)) CNT_QH_TODT
	FROM
		(SELECT
			A.BRCD, A.CUSTDTLTPCD, A.CUSTSEQ,
			SUM(DECODE(A.CCY, 'VND', A.TDBAL,
				CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCY, NVL(A.TDBAL,0), '01', 'VND', '01'))) TDBAL,
			SUM(DECODE(A.CCY, 'VND', A.TDBAL_QH,
				CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCY, NVL(A.TDBAL_QH,0), '01', 'VND', '01'))) TDBAL_QH,
			B.SHRTNM
		FROM
			(SELECT
				LN1.BRCDCONVERT(A.BRCD, '0') BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.LDRBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.LDRBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(D.LNTPCD, '105', '07. CA NHAN-KD VANG', '115', '07. CA NHAN-KD VANG', DECODE(A.CUSTSEQ, '100265300', '07. CA NHAN-KD VANG',
													DECODE(D.FNDPRPSTPCD, '09002', '08. CA NHAN-DUHOC', '09007', '08. CA NHAN-DUHOC',
																DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN')))),
								'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
												'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_BALDD A, CM1.TBCM_GENERAL C, LN1.TBLN_DSBS D
			WHERE
				A.TRDT 		= 	&h_trdt
				AND A.BRCD 		LIKE 	 '%'
				AND A.BRCD <> LN1.BRCDCONVERT(A.BRCD, 'Y')
				AND A.ACCTCD 	LIKE 	'2%'
				AND SUBSTR(A.ACCTCD, 3, 1) 	<> '9'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '217'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '275'
				AND SUBSTR(A.ACCTCD, 1, 3) 	<> '221'
				AND A.BUSCD 		=  'LN'
				AND A.LDRBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND D.BRCD	=   LN1.BRCDCONVERT(A.BRCD, '0')
				AND A.TRREF 	= 	D.DSBSID
				AND A.TRSEQ 	= 	D.DSBSSEQ
				AND		D.STSCD IN ('01', '05')
			GROUP BY
				A.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD, C.CUSTTPCD, D.LNTPCD, D.FNDPRPSTPCD, A.ACCTCD

			UNION ALL

			SELECT
				B.BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.LDRBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.LDRBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN'),	'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
											'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_BALDD A, CM1.TBCM_GENERAL C, LN1.TBLN_LNIDSEQ B, LN1.TBLN_DSBS D
			WHERE
				A.TRDT 			= 	&h_trdt
				AND A.ACCTCD 	LIKE 	'2%'
				AND A.BUSCD 	= 	'LN'
				AND A.LDRBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND A.BRCD 		= 	B.BRCDOLD
				AND A.TRREF 	= 	B.ID
				AND A.TRSEQ 	= 	B.SEQOLD
				AND B.BRCD 		= 	D.BRCD
				AND B.ID		= 	D.DSBSID
				AND B.SEQ 		= 	D.DSBSSEQ
				AND	D.STSCD IN ('01','05')
			GROUP BY
				B.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD, C.CUSTTPCD, A.ACCTCD

			UNION ALL

			SELECT
				A.BRCD,
				A.CUSTSEQ, A.CCY,
				SUM(A.TDBAL) TDBAL,
				SUM(DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 0, A.TDBAL)) TDBAL_QH,
				DECODE(A.CUSTSEQ, '100265300', '06. CA NHAN', DECODE(C.CUSTTPCD, '100', DECODE(SUBSTR(A.ACCTCD, 1, 3), '275', '09. CA NHAN-THAU CHI', '221', '10. CA NHAN-CHIET KHAU', '06. CA NHAN'),	'600', '05. TCTD',
								DECODE(C.CUSTDTLTPCD,'200', '01. NHA NUOC',
											'201', '01. NHA NUOC',
											'203', '02. CTY CP, CTY TNHH',
											'212', '02. CTY CP, CTY TNHH',
											'204', '02. CTY CP, CTY TNHH',
											'211', '02. CTY CP, CTY TNHH',
											'209', '03. DNTN',
												'213', '03. DNTN', '04. TCNN VA LD'))) CUSTDTLTPCD
			FROM
				GL1.TBGL_MAST A, CM1.TBCM_GENERAL C
			WHERE
				A.TRDT 		= 	&h_trdt
				AND A.ACCTCD LIKE '2%'
				AND SUBSTR(A.ACCTCD, 1, 3) NOT IN('211', '212', '213', '222', '223', '241', '271')
				AND 'Y' = 'Y'
				AND SUBSTR(A.ACCTCD, 3, 1) 	NOT IN ('7', '9')
				AND A.TDBAL 	> 	0
				AND A.BRCD 		= 	C.BRCD(+)
				AND A.CUSTSEQ 	= 	C.CUSTSEQ(+)
				AND LN1.CHKACCT20SBV(A.ACCTCD, A.CCY) = 'N'
			GROUP BY A.BRCD, A.CCY, A.CUSTSEQ, C.CUSTDTLTPCD,C.CUSTTPCD, A.ACCTCD
			) A, CM1.TBCM_GENERAL B
		WHERE
			A.BRCD 		= B.BRCD
			AND A.CUSTSEQ 	= B.CUSTSEQ
		GROUP BY A.BRCD, A.CUSTSEQ, A.CUSTDTLTPCD, B.SHRTNM
		)
	GROUP BY BRCD,CUSTDTLTPCD,CUSTSEQ,TDBAL,TDBAL_QH,SHRTNM
	) A
GROUP BY
	A.CUSTDTLTPCD
ORDER BY
	A.CUSTDTLTPCD
