--DEFINE h_trdt		= '20120417'

SELECT
	A.TRDT,
	A.BRNM,
	CCY,
	SUM(DU_NO_CON_LAI) DU_NO_CON_LAI,
    LAI_SUAT_KHACH_HANG,
	GIA_FTP,
	TO_DATE(DECODE(DECODE(SIGN(TO_DATE(DECODE(NGAY_TIEP_THEO_DOI_LS,'00000000','',NGAY_TIEP_THEO_DOI_LS),'YYYYMMDD')-TO_DATE(&h_trdt,'YYYYMMDD')),1,DECODE(NGAY_TIEP_THEO_DOI_LS,'00000000','',NGAY_TIEP_THEO_DOI_LS),''),'','',NGAY_CUOI_CUNG_DOI_LS),'YYYYMMDD') NGAY_CUOI_CUNG_DOI_LS1,
	TO_DATE(DECODE(SIGN(TO_DATE(DECODE(NGAY_TIEP_THEO_DOI_LS,'00000000','',NGAY_TIEP_THEO_DOI_LS),'YYYYMMDD')-TO_DATE(&h_trdt,'YYYYMMDD')),1,DECODE(NGAY_TIEP_THEO_DOI_LS,'00000000','',NGAY_TIEP_THEO_DOI_LS),''),'YYYYMMDD') NGAY_TIEP_THEO_DOI_LS1,
	NGAY_GIAI_NGAN,
	NGAY_DAO_HAN,
	CK_DOI_LS,
	QUA_HAN,
	LOAI_KH,
	A.CUSTSEQ CIF,
	B.NM TEN_KHACH_HANG,
	A.TRSEQ KHE_UOC,
	RATE_FTP DEAL_FTP
FROM
(
SELECT A.TRDT TRDT,
	A.BRCD, B.LCLBRNM BRNM,
	A.CCY CCY,
	A.ACRBAMT DU_NO_CON_LAI,
    A.BSRT LAI_SUAT_KHACH_HANG,
	A.SPRDRT GIA_FTP,
	NVL(C.INTAMDDT, '') NGAY_CUOI_CUNG_DOI_LS,
	LN1.GET_NXTINTRTCHNGDT(C.BRCD, C.DSBSID, C.DSBSSEQ) NGAY_TIEP_THEO_DOI_LS,
	TO_DATE(A.OPNDT,'YYYYMMDD') NGAY_GIAI_NGAN,
	TO_DATE(A.MATDT,'YYYYMMDD') NGAY_DAO_HAN,
	A.BSRTCD CK_DOI_LS,
	DECODE(NVL(PYARINT,0),0,'','X') QUA_HAN,
	DECODE(LN1.CHK_LNCUSTTP(C.BRCD, C.DSBSID, C.DSBSSEQ, C.CUSTSEQLN, 'IND'),'Y','CA_NHAN',
						DECODE(LN1.CHK_LNCUSTTP(C.BRCD, C.DSBSID, C.DSBSSEQ, C.CUSTSEQLN, 'CMP'),'Y','DOANH_NGHIEP')) LOAI_KH,
	A.CUSTSEQ,
	A.TRSEQ,
	DECODE(DLFTPREGFLG, 'Y', DECODE(DLFTPCFMFLG, 'Y', DECODE(DLFTPVRFFLG, 'Y', DLFTPSPRD), 0), 0) RATE_FTP
FROM GL1.TBGL_FTPDD A,TBCS_BRCD B,TBLN_DSBS C
WHERE A.TRDT=&h_trdt
AND A.BUSCD='LN'
AND A.BRCD=B.BRCD
AND A.BRCD=C.BRCD
AND A.TRREF=C.DSBSID
AND A.TRSEQ=C.DSBSSEQ
) A, CM1.TBCM_GENERAL B
WHERE A.BRCD = B.BRCD
AND A.CUSTSEQ = B.CUSTSEQ
GROUP BY
	A.TRDT,
	A.BRNM,
	CCY,
    LAI_SUAT_KHACH_HANG,
	GIA_FTP,
	NGAY_CUOI_CUNG_DOI_LS,
	NGAY_TIEP_THEO_DOI_LS,
	NGAY_GIAI_NGAN,
	NGAY_DAO_HAN,
	CK_DOI_LS,
	QUA_HAN,
	LOAI_KH,
	A.CUSTSEQ,
	B.NM,
	A.TRSEQ,
	RATE_FTP
ORDER BY
	A.TRDT,
	A.BRNM,
	CCY,
    LAI_SUAT_KHACH_HANG,
	GIA_FTP,
	NGAY_CUOI_CUNG_DOI_LS,
	NGAY_TIEP_THEO_DOI_LS,
	NGAY_GIAI_NGAN,
	NGAY_DAO_HAN,
	CK_DOI_LS,
	LOAI_KH,
	A.CUSTSEQ,
	B.NM,
	A.TRSEQ,
	RATE_FTP
