--DEFINE h_trdt = '20091216'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT
	A.BRCD, A.GRP_LN NHOM_NO, A.CCYCD,
	A.CUSTSEQLN, B.SHRTNM KHACH_HANG,
	A.APPRSEQ HOP_DONG, A.DSBSSEQ KHE_UOC,
	SUM(A.TDBAL) DU_NO, SUM(A.TDBAL_VND) DU_NO_QUY_DOI
FROM
(
	SELECT
		D.BRCD, D.CUSTSEQLN, D.CCYCD,
		D.DSBSSEQ, D.APPRSEQ,
		DECODE(SUBSTR(D.LNSBTPCD, 2, 1), '1', 'NHOM 1', '2', 'NHOM 2', '3', 'NHOM 3', '4', 'NHOM 4', 'NHOM 5') GRP_LN,
		D.DSBSBAL TDBAL,
		CS1.EXCROSSCAL (D.BRCD, 'VND', &h_trdt, D.CCYCD, NVL(D.DSBSBAL,0), '01', 'VND', '01') TDBAL_VND
	FROM
		LN1.TBLN_DSBSHIST D
	WHERE
		D.BKDT 		= &h_trdt
		AND D.BUSCD = 'LN'
		AND D.STSCD = '01'
		AND LN1.CHK_LNCUSTTP(D.BRCD, D.DSBSID, D.DSBSSEQ, D.CUSTSEQLN, 'CMP') = 'Y'

	UNION ALL

	SELECT
		DECODE(SUBSTR(A.ACCTCD, 1, 3), '282', A.BRCD, '289', A.BRCD, LN1.BRCDCONVERT(A.BRCD, '0')) BRCD,
		A.CUSTSEQ, A.CCY,
		A.ACCTCD TRSEQ, '' APPRSEQ,
		DECODE(SUBSTR(A.ACCTCD, 1, 2), '28', 'NHOM 5', '29', 'NHOM 5',
						DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 'NHOM 1',
								'2', 'NHOM 2', '3', 'NHOM 3',
								'4', 'NHOM 4', 'NHOM 5')) GRP_LN,
		A.TDBAL,
		CS1.EXCROSSCAL (A.BRCD, 'VND', &h_trdt, A.CCY, NVL(A.TDBAL,0), '01', 'VND', '01') TDBAL_VND
	FROM
		GL1.TBGL_MAST A
	WHERE
		A.TRDT 		= 	 &h_trdt
		AND A.BRCD 	LIKE  '%'
		AND A.ACCTCD LIKE '2%'
		AND SUBSTR(A.ACCTCD, 1, 3) NOT IN ('211', '212', '213', '222','223','241', '271')
		AND SUBSTR(A.ACCTCD, 3, 1) NOT IN ('7', '9')
		AND A.TDBAL > 0
		AND LN1.CHK_LNCUSTTP(A.BRCD, '', '', A.CUSTSEQ, 'CMP') = 'Y'
		AND LN1.CHKACCT20SBV(A.ACCTCD, A.CCY) = 'N'
	) A, TBCM_GENERAL B
WHERE
	A.BRCD = B.BRCD(+)
	AND A.CUSTSEQLN = B.CUSTSEQ(+)
GROUP BY
	A.BRCD, A.GRP_LN, A.CUSTSEQLN, B.SHRTNM, A.APPRSEQ, A.DSBSSEQ, A.CCYCD

