SELECT DISTINCT A.TRDT NGAYXUATSOLIEU,
	D.ENGBRSHRTNM TENCHINHANH,
	A.CCY LOAITIEN,
	B.LDRBAL SODU,
	A.BSRT LAISUATHUYDONG,
	A.INTRT LAISUATFTP,
	B.OPNDT NGAYMO,
	B.MATDT NGAYDAOHAN,
	A.BSRTCD KYHAN,
	'DOANH NGHIEP' LOAIKHACHHANG,
	A.CUSTSEQ CIF,
	C.NM TENKHACHHANG,
	A.BRCD||A.TRREF||A.TRSEQ SOKHEUOC
FROM GL1.TBGL_FTPDD A, GL1.TBGL_BALDD B, CM1.TBCM_GENERAL C, CS1.TBCS_BRCD D
WHERE
	A.TRDT = &h_trdt
	AND A.BUSCD = 'TF'
	AND B.TRDT = &h_trdt
	AND B.BUSCD = 'TF'
	AND B.UNTBUSCD = 'EX'
	AND B.ACCTCD IN ('221100','221200','221300','221400','221500')
	AND A.BRCD = B.BRCD
	AND A.TRREF = B.TRREF
	AND A.TRSEQ = B.TRSEQ
	AND A.BRCD = C.BRCD(+)
	AND A.CUSTSEQ = C.CUSTSEQ(+)
	AND A.BRCD = D.BRCD

