SELECT H.LCLBRSHRTNM TENCHINHANH, C.BRCD BRCD, C.TRREF TRREF, C.TRSEQ TRSEQ,
	C.CUSTSEQ CIF, G.NMLOC TENKHACHHANG, C.ISUDT NGAYPHATHANH,
	C.EXPIDT NGAYTHANHTOAN, C.CCYCD NGUYENTE,	C.BALAMT SODU,
	C.GMCCYCD NGUYENTE_KYQUY, C.GMBALAMT TIENKYQUY,
	C.BALAMT -  CS1.EXCROSSCAL(C.BRCD,'VND',&h_trdt,NVL(TRIM(C.GMCCYCD),C.CCYCD),NVL(C.GMBALAMT,0),'01',C.CCYCD,'01') SODUDATRUKYQUYTHEONGUYENTE
FROM
(
	SELECT A.BRCD BRCD, A.TRREF TRREF, A.TRSEQ TRSEQ, A.CUSTSEQ CUSTSEQ,
		A.ISUDT ISUDT, A.EXPIDT EXPIDT, A.MCHDSCD MCHDSCD, A.CCYCD CCYCD,
		A.GMCCYCD GMCCYCD, SUM(DECODE(A.T,'T',-A.AMT,A.AMT)) BALAMT,
		DECODE(A.T,'T',-A.GMAMT,A.GMAMT) GMBALAMT
	FROM
	(
		SELECT 'M' T, M.BRCD BRCD, M.TRREF TRREF, M.IMPRTTRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, L.LCCCYCD CCYCD, M.APLCUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD, NVL(L.LCBALAMT,0)  AMT,
			M.GMCCYCD GMCCYCD, NVL(M.GMBALAMT,0) GMAMT
		FROM TBTF_IMTRMST M, TBTF_IMLC L
		WHERE M.BRCD LIKE '%'
			AND M.TRREF IN ('ILS','ISB')
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
		UNION ALL
		SELECT 'M' T, M.BRCD BRCD, M.TRREF TRREF, M.IMPRTTRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, M.LGISUCCYCD CCYCD, M.APLCUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD, NVL(M.LGBALAMT,0) AMT,
			M.GMCCYCD GMCCYCD, NVL(M.GMBALAMT,0) GMAMT
		FROM TBTF_IMTRMST M, TBTF_IMLC L
		WHERE M.BRCD LIKE '%'
			AND M.TRREF IN ('ILS','ISB')
			AND TRIM(M.LGISUCCYCD) IS NOT NULL
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
		UNION ALL
		SELECT 'T' T, O.BRCD BRCD, O.TRREF TRREF, O.TRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, O.TRCCYCD CCYCD, O.CUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD,
			DECODE(O.TRCD,'W161',-NVL(O.TRAMT,0),'W011',NVL(O.TRAMT,0),'W021',NVL(O.TRAMT,0)) AMT,
			O.TRCCYCD GMCCYCD, DECODE(O.TRCD,'W291',-NVL(O.TRAMT,0),'W271',NVL(O.TRAMT,0)) GMAMT
		FROM TBTF_TRLOG O, TBTF_IMTRMST M, TBTF_IMLC L
		WHERE O.BRCD LIKE '%'
			AND O.TRREF IN ('ILS','ISB')
			AND O.OPRDT > &h_trdt
			AND TRIM(O.DELDT) IS NULL
			AND TRIM(O.DELUSRID) IS NULL
			AND TRIM(O.OPRFLG) NOT IN ('D','C')
			AND O.UNTBUSCD = 'IM'
			AND (O.TRCD IN ('W011','W021','W161','W271','W291'))
			AND O.BRCD = M.BRCD
			AND O.TRREF = M.TRREF
			AND O.TRSEQ = M.IMPRTTRSEQ
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
	)A
	GROUP BY A.BRCD, A.CUSTSEQ, A.TRREF, A.TRSEQ, A.ISUDT, A.EXPIDT, A.MCHDSCD,
		A.CCYCD, A.GMCCYCD, A.T, A.GMAMT
	HAVING (SUM(DECODE(A.T,'T',-A.AMT,A.AMT))<> 0 OR SUM(DECODE(A.T,'T',-A.GMAMT,A.GMAMT)) <>0)
	UNION ALL
	SELECT B.BRCD BRCD, B.TRREF TRREF, B.TRSEQ TRSEQ, B.CUSTSEQ CUSTSEQ,
		B.ISUDT ISUDT, B.EXPIDT EXPIDT, B.MCHDSCD MCHDSCD, B.CCYCD CCYCD,
		B.GMCCYCD GMCCYCD, SUM(DECODE(B.T,'T',-B.AMT,B.AMT)) BALAMT,
		DECODE(B.T,'T',-B.GMAMT,B.GMAMT) GMBALAMT
	FROM
	(
		SELECT 'M' T, M.BRCD BRCD, M.TRREF TRREF, M.IMPRTTRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, L.LCCCYCD CCYCD, M.APLCUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD, NVL(L.LCBALAMT,0)  AMT,
			M.GMCCYCD GMCCYCD, NVL(M.GMBALAMT,0) GMAMT
		FROM TBTF_IMTRMST M, TBTF_IMLC L
		WHERE M.BRCD LIKE '%'
			AND M.TRREF = 'ILU'
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
       		UNION ALL
		SELECT 'M' T, M.BRCD BRCD, M.TRREF TRREF, M.IMPRTTRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, M.LGISUCCYCD CCYCD, M.APLCUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD, NVL(M.LGBALAMT,0) AMT,
			M.GMCCYCD GMCCYCD, NVL(M.GMBALAMT,0) GMAMT
		FROM TBTF_IMTRMST M, TBTF_IMLC L
		WHERE M.BRCD LIKE '%'
			AND M.TRREF = 'ILU'
			AND TRIM(M.LGISUCCYCD) IS NOT NULL
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
		UNION ALL
		SELECT 'M' T, M.BRCD BRCD, M.TRREF TRREF, M.IMPRTTRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, M.ACPTCCYCD CCYCD, M.APLCUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD, NVL(M.ACPTBALAMT,0) AMT ,
			M.GMCCYCD GMCCYCD, NVL(M.GMBALAMT,0) GMAMT
		FROM TBTF_IMTRMST M, TBTF_IMLC L
		WHERE M.BRCD LIKE '%'
			AND M.TRREF = 'ILU'
			AND TRIM(M.ACPTCCYCD) IS NOT NULL
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
		UNION ALL
		SELECT 'T' T, O.BRCD BRCD, O.TRREF TRREF, O.TRSEQ TRSEQ, L.ISUDT ISUDT,
			L.EXPINEWDT EXPIDT, O.TRCCYCD CCYCD, O.CUSTSEQ CUSTSEQ,
			NVL(TRIM(L.MCHDSCD),'28') MCHDSCD,
			DECODE(O.TRCD,'W161',-NVL(O.TRAMT,0),'W011',NVL(O.TRAMT,0),'W021',NVL(O.TRAMT,0)) AMT,
			O.TRCCYCD GMCCYCD, DECODE(O.TRCD,'W291',-NVL(O.TRAMT,0),'W271',NVL(O.TRAMT,0)) GMAMT
		FROM TBTF_TRLOG O, TBTF_IMTRMST M, TBTF_IMLC L
		WHERE O.BRCD LIKE '%'
			AND O.TRREF = 'ILU'
			AND O.OPRDT > &h_trdt
			AND TRIM(O.DELDT) IS NULL
			AND TRIM(O.DELUSRID) IS NULL
			AND TRIM(O.OPRFLG) NOT IN ('D','C')
			AND O.UNTBUSCD = 'IM'
			AND (O.TRCD IN ('W011','W021','W161','W271','W291'))
			AND O.BRCD = M.BRCD
			AND O.TRREF = M.TRREF
			AND O.TRSEQ = M.IMPRTTRSEQ
			AND TRIM(M.CNCLDT) IS NULL
			AND TRIM(M.CNCLUSRID) IS NULL
			AND M.BRCD=L.BRCD
			AND M.TRREF=L.TRREF
			AND M.IMPRTTRSEQ=L.IMPRTTRSEQ
			AND L.ISUDT <= &h_trdt
	)B
	GROUP BY B.BRCD, B.CUSTSEQ, B.TRREF, B.TRSEQ, B.ISUDT, B.EXPIDT, B.MCHDSCD,
		B.CCYCD, B.GMCCYCD, B.T, B.GMAMT
	HAVING (SUM(DECODE(B.T,'T',-B.AMT,B.AMT))<> 0 OR SUM(DECODE(B.T,'T',-B.GMAMT,B.GMAMT)) <> 0)
)C, CM1.TBCM_GENERAL G, RACE.T_CODE T, CS1.TBCS_BRCD H
WHERE C.BRCD = G.BRCD AND C.CUSTSEQ = G.CUSTSEQ
      AND T.CAT_NAME = 'TFMCHDSIM' AND C.MCHDSCD(+)  = T.CODE
      AND C.BRCD = H.BRCD
GROUP BY C.BRCD, C.TRREF, C.TRSEQ, C.CUSTSEQ, G.NMLOC, C.ISUDT, C.EXPIDT, C.CCYCD,
	C.GMCCYCD, C.BALAMT, C.GMBALAMT, H.LCLBRSHRTNM
ORDER BY C.BRCD, C.CCYCD, C.CUSTSEQ, C.TRREF, C.TRSEQ
