SELECT &h_trdt NGAY_BAOCAO, A.BRCD MACHINHANH, B.ENGBRSHRTNM TENCHINHANH,
	A.BRCD||A.NEGOTRREF||A.NEGOTRSEQ SOREF_CK, N.CCYCD LTIEN_CK, SUM(N.NEGOAMT) SOTIEN_CK, N.NEGODT NGAY_CK, decode(nvl(rtrim(F.MATDT), ' '), ' ', N.MATDT,  F.MATDT) NGAYDH,
	A.CCY LTIEN_CK_THUDUOC, SUM(A.AMT) SOTIEN_CK_THUDUOC, SUM(N.NEGOBAL) SODU_CK_CONLAI
FROM
(
	SELECT P.BRCD, P.NEGOTRREF, P.NEGOTRSEQ, L.CUSTSEQ, P.CRDCCYCD CCY, P.TOTALAMT AMT
	FROM
		TF1.TBTF_EXCRD P, TF1.TBTF_TRLOG L
	WHERE
		P.BRCD LIKE '%'
		AND P.NEGOTRREF not like 'C%'
		AND P.STLDT = &h_trdt
		AND NVL(TRIM(P.CNCLFLG),' ') <> 'Y'
		AND NVL(TRIM(P.DELFLG),' ') <> 'Y'
		AND P.BRCD = L.BRCD
		AND P.NEGOTRREF = L.TRREF
		AND P.NEGOTRSEQ = L.TRSEQ
		AND P.PARTSEQ = L.TRSUBSEQ
		AND L.TRCD IN ('W711')
		AND TRIM(L.DELUSRID) IS NULL
		AND TRIM(L.VRFCTNTRFLG) = 'Y'
		AND TRIM(L.VRFCNTUSRID) IS NOT NULL
	UNION ALL
	SELECT P.BRCD, P.NEGOTRREF, P.NEGOTRSEQ, L.CUSTSEQ, P.RFCCYCD CCY, P.DSHNRRFAMT AMT
	FROM
		TF1.TBTF_EXDSH P, TF1.TBTF_TRLOG L
	WHERE
		P.BRCD LIKE '%'
		AND P.NEGOTRREF not like 'C%'
		AND P.DHRRFFLG = 'Y'
		AND P.OPTDT = &h_trdt
		AND NVL(TRIM(P.CNCLFLG),' ') <> 'Y'
		AND NVL(TRIM(P.DELFLG),' ') <> 'Y'
		AND P.BRCD = L.BRCD
		AND P.NEGOTRREF = L.TRREF
		AND P.NEGOTRSEQ = L.TRSEQ
		AND P.DSHNRSEQ = L.TRSUBSEQ
		AND L.TRCD IN ('W551')
		AND TRIM(L.DELUSRID) IS NULL
)A, CS1.TBCS_BRCD B, TF1.TBTF_EXNCO N,
(SELECT  E.BRCD, E.NEGOTRREF, E.NEGOTRSEQ, E.MATDT
                FROM  TBTF_EXACT E,
                     (SELECT  BRCD, NEGOTRREF, NEGOTRSEQ, max(ACTSEQ) ACTSEQ
                        FROM  TBTF_EXACT
                       WHERE  BRCD    like '%'
                         AND  CNCLFLG = 'N'
                         AND  DELFLG  = 'N'
                        GROUP BY  BRCD, NEGOTRREF, NEGOTRSEQ) G
               WHERE  E.BRCD       = G.BRCD
                 AND  E.NEGOTRREF  = G.NEGOTRREF
                 AND  E.NEGOTRSEQ  = G.NEGOTRSEQ
                 AND  E.ACTSEQ     = G.ACTSEQ
) F
WHERE
	A.BRCD = B.BRCD
	AND A.BRCD = N.BRCD
	AND A.NEGOTRREF = N.NEGOTRREF
	AND A.NEGOTRSEQ = N.NEGOTRSEQ
    AND  N.BRCD      = F.BRCD      (+)
	AND  N.NEGOTRREF = F.NEGOTRREF (+)
	AND  N.NEGOTRSEQ = F.NEGOTRSEQ (+)
GROUP BY A.BRCD, B.ENGBRSHRTNM, A.BRCD, A.NEGOTRREF, A.NEGOTRSEQ, N.CCYCD, N.NEGODT, decode(nvl(rtrim(F.MATDT), ' '), ' ', N.MATDT,  F.MATDT), A.CCY
ORDER BY A.BRCD, A.NEGOTRREF, A.NEGOTRSEQ
