--DEFINE h_trdt = '20120918'

SELECT
	A.BRCDOWNR CHI_NHANH,
	A.CUSTSEQOWNR,
	NVL(G.NMLOC, ' ') CHU_TSDB,
	A.CLSEQ TSDB,
	LN1.GET_TCODE('LNCLDTLTPCD', 'VN', A.CLDTLTPCD, 'DECODE') LOAI_TSDB,
	DECODE(SUBSTR(A.CLDTLTPCD,1,1), '1', LN1.GET_TCODE('LNRESTSCD', 'VN', A.CLSTSCD, 'DECODE'),
												LN1.GET_TCODE('LNCLSTSCD', 'VN', A.CLSTSCD, 'DECODE')) TINH_CHAT,
	LN1.GET_TCODE('LNGNTERLTNTPCD', 'VN', A.GNTERLTNTPCD, 'DECODE') QUAN_HE,
	A.GNTERLTNDESC MO_TA_QUAN_HE,
	LN1.GET_TCODE('LNTRSPTSTSCD', 'VN', A.TRSPTSTSCD, 'DECODE') TINH_TRANG,
	NVL(A.MGRDT, ' ') NGAY_QUAN_LY,
	NVL(A.CLQTYSZ, 0) SO_LUONG,
	A.CLCCYCD,
	NVL(A.UNTFCAMT, 0) DON_GIA,
	A.PLGAMT GIA_TRI_TSDB,
	A.PLGAMT_VND GIA_TRI_TSDB_QUY_DOI,
	A.BRCDLN,
	A.CUSTSEQLN,
	NVL(F.NMLOC, ' ') KHACH_HANG_VAY,
	A.APPRSEQ HOP_DONG,
	A.DSBSSEQ KHE_UOC,
	DECODE(LENGTH(A.FNDPRPSTPCD), 5, LN1.GET_TCODE('LNFNDPRBRLEV1', 'CC', SUBSTR(A.FNDPRPSTPCD, 1, 2), 'DECODE')) MUC_DICH_VAY_CAP_1,
	LN1.GET_TCODE('LNFNDPRPSTPCD', 'CC', A.FNDPRPSTPCD, 'DECODE') MUC_DICH_VAY_CAP_2,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||SUBSTR(A.FNDPRPSUNIT, 1, 2), 'DECODE') MUC_DICH_VAY_CAP_3,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||A.FNDPRPSUNIT, 'DECODE') MUC_DICH_VAY_CAP_4,
	LN1.GET_TCODE('LNOTHRTPCD', 'VN', A.FNDPRPSTPCD||NVL(A.FNDPRPSUNIT,'00000')||A.OTHRTPCD, 'DECODE') LOAI_SP,
	A.CCYCD,
	A.DSBSBAL DU_NO,
	A.DSBSBAL_VND DU_NO_QUY_DOI,
	A.BALGRP NHOM_NO,
	A.LNTPCD LOAI_VAY,
	A.NM TEN_CTY_CK,
	A.PIVSEQ PIVSEQ,
	A.BUSREGNO SO_DKKD,
	A.INVRNM TEN_CHU_DAU_TU,
	A.PRJNM  TEN_DU_AN,
	DECODE(SUBSTR(A.CLDTLTPCD, 1, 1),
		'6', DECODE(A.CRDTOFC, 'EIB', 'EIB', LN1.GET_TCODE('LNCRDTOFC', 'VN', A.CRDTOFC, 'DECODE'))) TO_CHUC_PHAT_HANH,
	A.REM REMARK,
	A.CLLOC DIA_CHI_TSDB,
	LN1.GET_TCODE('LNCLPOSTP', 'VN', A.CLPOSTP, 'DECODE') DIA_BAN
FROM
	(
		SELECT
			A.BRCDOWNR,
			A.CUSTSEQOWNR,
			A.BRCDCL ||'-'|| A.CLID ||'-'|| A.CLSEQ CLSEQ,
			A.CLDTLTPCD,
			B.CLSTSCD,
			B.GNTERLTNTPCD,
			B.GNTERLTNDESC,
			B.TRSPTSTSCD,
			B.MGRDT,
			B.CLQTYSZ,
			A.CLCCYCD,
			B.UNTFCAMT,
			A.PLGAMT,
			DECODE(A.CLCCYCD, 'VND', A.PLGAMT, CS1.EXCROSSCAL(A.BRCDCL, 'VND', &h_trdt, A.CLCCYCD, A.PLGAMT, '01', 'VND', '01')) PLGAMT_VND,
			A.BRCDLN,
			A.CUSTSEQLN,
			A.BRCDAPPR ||'-'|| A.APPRID ||'-'|| A.APPRSEQ APPRSEQ,
			A.BRCD     ||'-'|| A.DSBSID ||'-'|| A.DSBSSEQ DSBSSEQ,
			A.FNDPRPSTPCD,
			A.FNDPRPSUNIT,
			C.OTHRTPCD,
			A.CCYCD,
			A.DSBSBAL,
			DECODE(A.CCYCD, 'VND', A.DSBSBAL, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSBAL, '01', 'VND', '01')) DSBSBAL_VND,
			SUBSTR(A.ACCTCD, 4, 1) BALGRP,
			DECODE(NVL(A.ACCTCD, '000000'),'211100','1.Ng¾n h¹n',
							'211101','1.Ng¾n h¹n',
							'211200','1.Ng¾n h¹n',
							'211201','1.Ng¾n h¹n',
							'211300','1.Ng¾n h¹n',
							'211301','1.Ng¾n h¹n',
							'211400','1.Ng¾n h¹n',
							'211401','1.Ng¾n h¹n',
							'211500','1.Ng¾n h¹n',
							'211501','1.Ng¾n h¹n',
							'222100','1.Ng¾n h¹n',
							'222200','1.Ng¾n h¹n',
							'222300','1.Ng¾n h¹n',
							'222400','1.Ng¾n h¹n',
							'222500','1.Ng¾n h¹n',
							'241100','1.Ng¾n h¹n',
							'241200','1.Ng¾n h¹n',
							'241300','1.Ng¾n h¹n',
							'241400','1.Ng¾n h¹n',
							'241500','1.Ng¾n h¹n',
							'212100','2.Trung h¹n',
							'212200','2.Trung h¹n',
							'212300','2.Trung h¹n',
							'212400','2.Trung h¹n',
							'212500','2.Trung h¹n',
							'223100','2.Trung h¹n',
							'223200','2.Trung h¹n',
							'223300','2.Trung h¹n',
							'223400','2.Trung h¹n',
							'223500','2.Trung h¹n',
							'213100','3.Dµi h¹n',
							'213200','3.Dµi h¹n',
							'213300','3.Dµi h¹n',
							'213400','3.Dµi h¹n',
							'213500','3.Dµi h¹n', A.ACCTCD) LNTPCD, A.ACCTCD, D.NM,
			E.PIVID||E.PIVSEQ PIVSEQ, E.BUSREGNO, E.INVRNM, E.PRJNM,
			B.REM, B.CRDTOFC,
			DECODE(B.CLTPCD,'01',UPPER(DECODE(NVL(B.CLLOC, ''), '',
				DECODE(B.CLTPCD, '01', 'SO '||B.ADDR1||',DUONG '||B.ADDR2||',F/XA '||B.ADDR3||',Q/HUYEN '||B.ADDR4||', '||LN1.GET_TCODE('DPLOCCD', 'VN', B.ADDR5, 'STATDECODE') ,
					B.CERTNO||' '||B.REM), B.CLLOC)), '02', B.CARNO, '06', DECODE(B.CRDTOFC,'EIB','Tai Khoan EIB','Tai Khoan Ngan hang khac'),'09', B.CLLOC,'') CLLOC,
			B.CLPOSTP
		FROM
			LN1.TBLN_CLBAL A, LN1.TBLN_CL B, LN1.TBLN_DSBS C,
			(SELECT A.BRCD, CLID, CLSEQ, DECODE(NVL(A.NM,' '), ' ', B.NMLOC, A.NM) NM
			FROM LN1.TBLN_CLREF A, TBCM_GENERAL B
			WHERE
				A.STSCD = '01'
				AND NVL(QTY, 0) = 0
				AND A.BRCD = B.BRCD
				AND TRIM(A.REFNO) = B.CUSTSEQ
			) D,
			(SELECT PIVID, PIVSEQ, BUSREGNO, INVRNM, PRJNM
			FROM LN1.TBLN_PROJINVR A, LN1.TBLN_PROJECT B
			WHERE A.PRJID = B.PRJID
				AND A.PRJSEQ = B.PRJSEQ
				AND A.STSCD = '01'
				AND B.STSCD = '01'
			) E
		WHERE
			A.TRDT = &h_trdt
			AND A.STSCD   = '01'
			AND A.BRCDCL  = B.BRCD (+)
			AND A.CLID    = B.CLID (+)
			AND A.CLSEQ   = B.CLSEQ (+)
			AND A.BRCD    = C.BRCD (+)
			AND A.DSBSID  = C.DSBSID (+)
			AND A.DSBSSEQ = C.DSBSSEQ (+)
			AND B.BRCD 	  = D.BRCD (+)
			AND B.CLID 	  = D.CLID (+)
			AND B.CLSEQ   = D.CLSEQ (+)
			AND B.PIVID	  = E.PIVID (+)
			AND B.PIVSEQ  = E.PIVSEQ (+)

			AND LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND') = 'Y'
	) A, CM1.TBCM_GENERAL F, CM1.TBCM_GENERAL G
WHERE
	A.BRCDLN = F.BRCD (+)
	AND A.CUSTSEQLN = F.CUSTSEQ (+)
	AND A.BRCDOWNR = G.BRCD (+)
	AND A.CUSTSEQOWNR = G.CUSTSEQ (+)
ORDER BY
	BRCDOWNR, CUSTSEQOWNR, CLSEQ, BRCDLN, CUSTSEQLN, APPRSEQ, DSBSSEQ
