--define h_trdt = '20110817'

SELECT
	A.BRCD MA_CN,
	B.LCLBRNM TEN_CN,
	DECODE(SUBSTR(NVL(A.DEPTCD, 'XXX'), 3, 1), 'O', A.DEPTCD) MA_PGD,
	DECODE(SUBSTR(NVL(A.DEPTCD, 'XXX'), 3, 1), 'O', D.DEPTNM) TEN_PGD,
	A.CUSTSEQLN CIF,
	C.NMLOC TEN_KH,
	A.DSBSSEQ KHE_UOC,
	A.DSBSDT NGAY_GIAI_NGAN,
	A.MATDT NGAY_DAO_HAN,
	LN1.GET_TCODE('LNLNTPCD', 'CC', A.LNTPCD, 'DECODE') LOAI_VAY,
	DECODE(LENGTH(A.FNDPRPSTPCD), 5, LN1.GET_TCODE('LNFNDPRBRLEV1', 'CC', SUBSTR(A.FNDPRPSTPCD, 1, 2), 'DECODE')) MDV_CAP1,
	LN1.GET_TCODE('LNFNDPRPSTPCD', 'CC', A.FNDPRPSTPCD, 'DECODE') MDV_CAP2,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||SUBSTR(A.FNDPRPSUNIT, 1, 2), 'DECODE') MDV_CAP3,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||A.FNDPRPSUNIT, 'DECODE') MDV_CAP4,
	A.CCYCD LOAI_TIEN,
	A.BSRTCD CODE_LAI_SUAT,
	A.BASERATE LAI_SUAT,
	DECODE(A.INTRTTPCD, '01', A.TOTALRATE - A.BASERATE, A.SPRD) BIEN_DO,
	DECODE(A.INTRTTPCD, '01', A.TOTALRATE, A.SPRD + A.BASERATE) LAI_SUAT_VAY,
	A.DSBSAMT SO_TIEN_GIAI_NGAN,
	CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSAMT, '01', 'VND', '01') SO_TIEN_GIAI_NGAN_VND,
	A.DSBSBAL DU_NO,
	CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSBAL, '01', 'VND', '01') DU_NO_VND
FROM
	TBLN_DSBS A, TBCS_BRCD B, TBCM_GENERAL C, CS1.TBCS_DEPTCD D
WHERE
	A.STSCD IN ('01', '05')
	AND A.DSBSDT BETWEEN SUBSTR(&h_trdt, 1, 4)||'0101' AND &h_trdt
	AND A.BUSCD = 'LN'
	AND A.BRCD = B.BRCD
	AND A.BRCDLN = C.BRCD
	AND A.CUSTSEQLN = C.CUSTSEQ
	AND A.DEPTCD = D.DEPTCD (+)
	AND LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND') = 'Y'
ORDER BY
	A.BRCD, A.DEPTCD, A.CUSTSEQLN, A.DSBSSEQ
