SELECT
	/*+ INDEX (A PKLN_DSBS) INDEX (D PKCS_BRCD) */
	A.BRCD,
	D.LCLBRNM TEN_CN,
	A.CUSTSEQLN CIF,
	C.NMLOC TEN_KH,
	A.BRCDAPPR||'-'||A.APPRID||'-'||A.APPRSEQ HOP_DONG,
	LN1.GET_APPRDT(A.BRCD, A.DSBSID, A.DSBSSEQ) NGAY_HOP_DONG,
	A.BRCD||'-'||A.DSBSID||'-'||A.DSBSSEQ KHE_UOC,
	LN1.GET_TCODE('LNLNTPCD', 'CC', A.LNTPCD, 'DECODE') LOAI_VAY,
	A.DSBSDT NGAY_GIAI_NGAN,
	A.MATDT NGAY_DAO_HAN,
	A.CCYCD LOAI_TIEN,
	A.DSBSAMT SO_TIEN_GIAI_NGAN,
	A.DSBSBAL DU_NO_HIEN_TAI,
	NVL(A.INTAMDDT, '00000000') NGAY_THAY_DOI_LS_TRUOC,
	DECODE(LN1.GET_INTRTTP(A.BRCD, A.DSBSID, A.DSBSSEQ),
		'CIA', B.INTAMDYY * 12 + B.INTAMDMM,
		'CID', A.INTAMDMM) CHU_KY,
	LN1.GET_NXTINTRTCHNGDT(A.BRCD, A.DSBSID, A.DSBSSEQ) NGAY_THAY_DOI_LS_KE_TIEP,
	A.BSRTCD CODE_LS,
	A.BASERATE LS_CO_BAN,
	DECODE(A.INTRTTPCD, '01', A.TOTALRATE - A.BASERATE, A.SPRD) BIEN_DO,
	DECODE(A.INTRTTPCD, '01', A.TOTALRATE, A.BASERATE + A.SPRD) LAI_SUAT_VAY,
	--LN1.GET_NXTDSBSINTRT(A.BRCD, A.DSBSID, A.DSBSSEQ) LS_DU_KIEN,
	LN1.GET_TCODE('LNFNDPRPSTPCD', 'CC', A.FNDPRPSTPCD, 'DECODE') MUC_DICH_VAY,
	LN1.GET_TCODE('LNFNDPRPSUNIT', 'CC', A.FNDPRPSTPCD||A.FNDPRPSUNIT, 'DECODE') SAN_PHAM_VAY,
	DECODE(LN1.GET_INTRTTP(A.BRCD, A.DSBSID, A.DSBSSEQ), 'CIA', 'Approval', 'CID', 'Disbursement') LOAI_THAY_DOI_LS,
	DECODE(SUBSTR(C.CUSTTPCD,1,1),'1','IND','CMP') LOAI_KHACH_HANG
FROM
	LN1.TBLN_DSBS A, LN1.TBLN_APPR B, CM1.TBCM_GENERAL C, CS1.TBCS_BRCD D
WHERE
	--A.BRCD LIKE '%'AND 
	A.BRCDAPPR = B.BRCD
	AND A.APPRID = B.APPRID
	AND A.APPRSEQ = B.APPRSEQ
	AND A.BRCD = C.BRCD
	AND A.CUSTSEQLN = C.CUSTSEQ
	AND A.BRCD = D.BRCD
	AND A.STSCD = '01'
	AND A.BUSCD = 'LN'
	AND LN1.GET_INTRTTP(A.BRCD, A.DSBSID, A.DSBSSEQ) IN ('CIA', 'CID')
	--AND LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, '', 'ind') = 'Y'
	--AND C.CUSTTPCD LIKE '1%'
ORDER BY
	A.BRCD, A.CUSTSEQLN, A.APPRSEQ, A.DSBSSEQ
