--define h_trdt = '20121112'

SELECT
	DISTINCT A.BRCD, A.CUSTSEQLN, E.NMLOC TEN_KH,
	FSTPSTDT NGAY_DAUTIEN_QH,
	DECODE(SIGN(NVL(PSTCNT, 0)),1,'Y','N') NQH_TRONG_3THANG_LIENTIEP,
	DECODE(LNSBTPCD, '01', '', PSTDT) NGAY_CHUYEN_NHOM_QH,
	DECODE(SUBSTR(E.CUSTTPCD,1,1), '1', 'CA NHAN', 'DOANH NGHIEP') DOI_TUONG_KH

FROM LN1.TBLN_DSBSHIST A,
(SELECT BRCD,CUSTSEQLN, MIN(TRDT) FSTPSTDT
		FROM LN1.TBLN_PSTADMLN
		WHERE LNSBTPCD <> '01'
		GROUP BY BRCD,CUSTSEQLN) B,
(SELECT
	BRCD, CUSTSEQLN, COUNT(DISTINCT SUBSTR(PSTDT,1,6)) PSTCNT
		FROM LN1.TBLN_PSTADMLN
		WHERE
			TRDT BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt,'YYYYMMDD'), -3), 'YYYYMMDD') AND &h_trdt
			AND CNTPSTDAY < 10
			AND PSTTPCD IN ('01', '02')
		GROUP BY BRCD, CUSTSEQLN
		HAVING COUNT(DISTINCT SUBSTR(PSTDT,1,6)) >= 3 ) C,
(SELECT CUSTSEQLN, MAX(PSTDT) PSTDT
		FROM
			(
				SELECT CUSTSEQLN, MAX(TRDT) PSTDT
				FROM
				(
					SELECT CUSTSEQLN, TRDT, MAX(LNBEFSBTPCD) LNBEFSBTPCD,
						MAX(LNAFTSBTPCD) LNAFTSBTPCD
					FROM LN1.TBLN_PSTADMLN
					WHERE
						LNAFTSBTPCD > '01'
						AND STSCD = '01'
					GROUP BY CUSTSEQLN, TRDT
				)
				WHERE
					LNBEFSBTPCD <> LNAFTSBTPCD
				GROUP BY CUSTSEQLN

				UNION ALL

				SELECT CUSTSEQLN, MIN(TRDT) PSTDT
				FROM LN1.TBLN_PSTADMLN
				WHERE
					LNAFTSBTPCD > '01'
					AND CUSTSEQLN NOT IN
					(
						SELECT DISTINCT CUSTSEQLN
						FROM
						(
							SELECT
								CUSTSEQLN, TRDT, MAX(LNBEFSBTPCD) LNBEFSBTPCD,
								MAX(LNAFTSBTPCD) LNAFTSBTPCD
							FROM LN1.TBLN_PSTADMLN
							WHERE
								LNAFTSBTPCD > '01'
								AND STSCD = '01'
							GROUP BY CUSTSEQLN, TRDT
						)
						WHERE LNBEFSBTPCD <> LNAFTSBTPCD
					)
				GROUP BY CUSTSEQLN

				UNION ALL

				SELECT CUSTSEQLN, MAX(TRDT) PSTDT
				FROM LN1.TBLN_PSTADMCUST
				WHERE STSCD = '01'
				GROUP BY CUSTSEQLN
			)
			GROUP BY CUSTSEQLN
		) D, CM1.TBCM_GENERAL E
WHERE
	A.BUSCD = 'LN'
	AND A.STSCD = '01'
	AND A.BKDT = &h_trdt

	AND A.BRCD = B.BRCD(+)
	AND A.CUSTSEQLN = B.CUSTSEQLN(+)

	AND A.BRCD = C.BRCD(+)
	AND A.CUSTSEQLN = C.CUSTSEQLN(+)

	AND A.CUSTSEQLN = D.CUSTSEQLN(+)

	AND A.BRCDLN = E.BRCD
	AND A.CUSTSEQLN = E.CUSTSEQ
ORDER BY BRCD, CUSTSEQLN

