-- DEFINE h_trdt	= '20100928'

SELECT
	'ChØ tiªu cÊp 1' ITEM1,
	'ChØ tiªu cÊp 2' ITEM2,
	'ChØ tiªu cÊp 3' ITEM3,
	'Lo¹i tiÒn' CCYCD,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 30, 'YYYYMMDD')) DAY01,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 29, 'YYYYMMDD')) DAY02,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 28, 'YYYYMMDD')) DAY03,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 27, 'YYYYMMDD')) DAY04,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 26, 'YYYYMMDD')) DAY05,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 25, 'YYYYMMDD')) DAY06,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 24, 'YYYYMMDD')) DAY07,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 23, 'YYYYMMDD')) DAY08,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 22, 'YYYYMMDD')) DAY09,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 21, 'YYYYMMDD')) DAY10,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 20, 'YYYYMMDD')) DAY11,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 19, 'YYYYMMDD')) DAY12,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 18, 'YYYYMMDD')) DAY13,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 17, 'YYYYMMDD')) DAY14,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 16, 'YYYYMMDD')) DAY15,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 15, 'YYYYMMDD')) DAY16,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 14, 'YYYYMMDD')) DAY17,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 13, 'YYYYMMDD')) DAY18,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 12, 'YYYYMMDD')) DAY19,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 11, 'YYYYMMDD')) DAY20,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 10, 'YYYYMMDD')) DAY21,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 9,  'YYYYMMDD')) DAY22,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 8,  'YYYYMMDD')) DAY23,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 7,  'YYYYMMDD')) DAY24,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 6,  'YYYYMMDD')) DAY25,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 5,  'YYYYMMDD')) DAY26,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 4,  'YYYYMMDD')) DAY27,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 3,  'YYYYMMDD')) DAY28,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 2,  'YYYYMMDD')) DAY29,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 1,  'YYYYMMDD')) DAY30,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD'),  	 'YYYYMMDD')) RPTDT,
	TO_NUMBER(TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') + 1,  'YYYYMMDD')) RPTDT01

FROM
	DUAL

UNION ALL

SELECT
	ITEM1, ITEM2, ITEM3, CCYCD,
	DAY01, DAY02, DAY03, DAY04, DAY05,
	DAY06, DAY07, DAY08, DAY09, DAY10,
	DAY11, DAY12, DAY13, DAY14, DAY15,
	DAY16, DAY17, DAY18, DAY19, DAY20,
	DAY21, DAY22, DAY23, DAY24, DAY25,
	DAY26, DAY27, DAY28, DAY29, DAY30,
	RPTDT, RPTDT01
FROM
(
	SELECT
		ITEM1,
		ITEM2,
		ITEM3,
		CCYCD,
	   	SUM(DAY01) DAY01, SUM(DAY02) DAY02, SUM(DAY03) DAY03, SUM(DAY04) DAY04, SUM(DAY05) DAY05,
		SUM(DAY06) DAY06, SUM(DAY07) DAY07, SUM(DAY08) DAY08, SUM(DAY09) DAY09, SUM(DAY10) DAY10,
		SUM(DAY11) DAY11, SUM(DAY12) DAY12, SUM(DAY13) DAY13, SUM(DAY14) DAY14, SUM(DAY15) DAY15,
		SUM(DAY16) DAY16, SUM(DAY17) DAY17, SUM(DAY18) DAY18, SUM(DAY19) DAY19, SUM(DAY20) DAY20,
		SUM(DAY21) DAY21, SUM(DAY22) DAY22, SUM(DAY23) DAY23, SUM(DAY24) DAY24, SUM(DAY25) DAY25,
		SUM(DAY26) DAY26, SUM(DAY27) DAY27, SUM(DAY28) DAY28, SUM(DAY29) DAY29, SUM(DAY30) DAY30,
		SUM(RPTDT) RPTDT, SUM(RPTDT01) RPTDT01
	FROM
	(
		SELECT
			AA.ITEM1,
			DECODE(BB.ITEM, 'Tæng céng', ' ', NVL(AA.ITEM2, ' ')) ITEM2,
			DECODE(BB.ITEM, 'Tæng céng', BB.ITEM, AA.ITEM3) ITEM3,
			AA.CCYCD,
			AA.DAY01, AA.DAY02, AA.DAY03, AA.DAY04, AA.DAY05,
			AA.DAY06, AA.DAY07, AA.DAY08, AA.DAY09, AA.DAY10,
			AA.DAY11, AA.DAY12, AA.DAY13, AA.DAY14, AA.DAY15,
			AA.DAY16, AA.DAY17, AA.DAY18, AA.DAY19, AA.DAY20,
			AA.DAY21, AA.DAY22, AA.DAY23, AA.DAY24, AA.DAY25,
			AA.DAY26, AA.DAY27, AA.DAY28, AA.DAY29, AA.DAY30,
			AA.RPTDT, AA.RPTDT01
		FROM
		(
			SELECT
				ITEM1, ITEM2, ITEM3, CCYCD,
				SUM(DECODE(DAYS, 30, AMT, 0)) DAY01,
				SUM(DECODE(DAYS, 29, AMT, 0)) DAY02,
				SUM(DECODE(DAYS, 28, AMT, 0)) DAY03,
				SUM(DECODE(DAYS, 27, AMT, 0)) DAY04,
				SUM(DECODE(DAYS, 26, AMT, 0)) DAY05,
				SUM(DECODE(DAYS, 25, AMT, 0)) DAY06,
				SUM(DECODE(DAYS, 24, AMT, 0)) DAY07,
				SUM(DECODE(DAYS, 23, AMT, 0)) DAY08,
				SUM(DECODE(DAYS, 22, AMT, 0)) DAY09,
				SUM(DECODE(DAYS, 21, AMT, 0)) DAY10,
				SUM(DECODE(DAYS, 20, AMT, 0)) DAY11,
				SUM(DECODE(DAYS, 19, AMT, 0)) DAY12,
				SUM(DECODE(DAYS, 18, AMT, 0)) DAY13,
				SUM(DECODE(DAYS, 17, AMT, 0)) DAY14,
				SUM(DECODE(DAYS, 16, AMT, 0)) DAY15,
				SUM(DECODE(DAYS, 15, AMT, 0)) DAY16,
				SUM(DECODE(DAYS, 14, AMT, 0)) DAY17,
				SUM(DECODE(DAYS, 13, AMT, 0)) DAY18,
				SUM(DECODE(DAYS, 12, AMT, 0)) DAY19,
				SUM(DECODE(DAYS, 11, AMT, 0)) DAY20,
				SUM(DECODE(DAYS, 10, AMT, 0)) DAY21,
				SUM(DECODE(DAYS,  9, AMT, 0)) DAY22,
				SUM(DECODE(DAYS,  8, AMT, 0)) DAY23,
				SUM(DECODE(DAYS,  7, AMT, 0)) DAY24,
				SUM(DECODE(DAYS,  6, AMT, 0)) DAY25,
				SUM(DECODE(DAYS,  5, AMT, 0)) DAY26,
				SUM(DECODE(DAYS,  4, AMT, 0)) DAY27,
				SUM(DECODE(DAYS,  3, AMT, 0)) DAY28,
				SUM(DECODE(DAYS,  2, AMT, 0)) DAY29,
				SUM(DECODE(DAYS,  1, AMT, 0)) DAY30,
				SUM(DECODE(DAYS,  0, AMT, 0)) RPTDT,
				SUM(DECODE(DAYS, -1, AMT, 0)) RPTDT01
			FROM
			(
				SELECT
					'1.§¸o h¹n' ITEM1,
					' ' ITEM2,
					DECODE(LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'ind'), 'Y', 'a.C¸ nh©n', 'b.Doanh nghiÖp') ITEM3,
					CCYCD,
					(TO_DATE(&h_trdt, 'YYYYMMDD') - TO_DATE(C.RPMTSCHDDT, 'YYYYMMDD')) DAYS,
					(NVL(C.RPMTSCHDAMT, 0) - NVL(C.RPMTAMT, 0)) AMT
				FROM
					LN1.TBLN_DSBS A, LN1.TBLN_SCHDMAS B, LN1.TBLN_SCHDSB C
				WHERE
					C.RPMTSCHDDT = TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') + 1, 'YYYYMMDD')
					AND A.BRCD = B.BRCDDSBS
					AND A.DSBSID = B.DSBSID
					AND A.DSBSSEQ = B.DSBSSEQ
					AND A.BUSCD	= 'LN'
					AND A.STSCD = '01'
					AND B.BRCD = C.BRCD
					AND B.RPMTSCHDID =  C.RPMTSCHDID
					AND B.RPMTSCHDSEQ = C.RPMTSCHDSEQ
					AND B.STSCD = '01'
					AND (NVL(C.RPMTSCHDAMT, 0) - NVL(C.RPMTAMT, 0)) > 0

				UNION ALL

				SELECT /*+ INDEX (A PKLN_RPMT) */
					'3.Tr¶ nî' ITEM1,
					DECODE(SIGN(B.RPMTSCHDDT - A.TRDT), 1, '1.Tr­íc h¹n', 0, '2.§óng h¹n', '3.TrÔ h¹n') ITEM2,
					DECODE(LN1.CHK_LNCUSTTP(A.BRCDDSBS, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'IND'), 'Y', 'a.C¸ nh©n', 'b.Doanh nghiÖp') ITEM3,
					C.CCYCD,
					(TO_DATE(&h_trdt, 'YYYYMMDD') - TO_DATE(A.TRDT, 'YYYYMMDD')) DAYS,
					NVL(B.RPMTAMT, 0) AMT
				FROM
					LN1.TBLN_RPMT A, LN1.TBLN_RPMTDTL B, LN1.TBLN_DSBS C
				WHERE
					A.TRDT BETWEEN TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 30, 'YYYYMMDD') AND &h_trdt
					AND A.BRCD = B.BRCD
					AND A.RPMTID = B.RPMTID
					AND A.RPMTSEQ = B.RPMTSEQ
					AND A.STSCD = '01'
					AND A.ACMODE = 0
					AND A.BRCDDSBS = C.BRCD
					AND A.DSBSID = C.DSBSID
					AND A.DSBSSEQ = C.DSBSSEQ
					AND NVL(B.RPMTAMT, 0) > 0

				UNION ALL

				SELECT /*+ INDEX (A PKLN_DSBS) */
					'4.Gi¶i ng©n' ITEM1, '' ITEM2,
					DECODE(LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'ind'), 'Y', 'a.C¸ nh©n', 'b.Doanh nghiÖp') ITEM3,
					A.CCYCD,
					TO_DATE(&h_trdt, 'YYYYMMDD') - TO_DATE(A.DSBSDT, 'YYYYMMDD') DAYS,
					A.DSBSAMT AMT
				FROM
					LN1.TBLN_DSBS A
				WHERE
					A.BRCD LIKE '%'
					AND A.STSCD IN ('01', '05')
					AND A.BUSCD = 'LN'
					AND A.DSBSDT BETWEEN TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 30, 'YYYYMMDD') AND &h_trdt
			)
			GROUP BY
				ITEM1, ITEM2, ITEM3, CCYCD
		) AA,

		(
			SELECT
				'Tæng céng' ITEM
			FROM
				DUAL

			UNION ALL

			SELECT
				'Chi tiÕt'
			FROM
				DUAL
		) BB

		UNION ALL

		SELECT
			ITEM1, ITEM2, ITEM3, CCYCD,
			SUM(DECODE(DAYS, 30, AMT, 0)) DAY01,
			SUM(DECODE(DAYS, 29, AMT, 0)) DAY02,
			SUM(DECODE(DAYS, 28, AMT, 0)) DAY03,
			SUM(DECODE(DAYS, 27, AMT, 0)) DAY04,
			SUM(DECODE(DAYS, 26, AMT, 0)) DAY05,
			SUM(DECODE(DAYS, 25, AMT, 0)) DAY06,
			SUM(DECODE(DAYS, 24, AMT, 0)) DAY07,
			SUM(DECODE(DAYS, 23, AMT, 0)) DAY08,
			SUM(DECODE(DAYS, 22, AMT, 0)) DAY09,
			SUM(DECODE(DAYS, 21, AMT, 0)) DAY10,
			SUM(DECODE(DAYS, 20, AMT, 0)) DAY11,
			SUM(DECODE(DAYS, 19, AMT, 0)) DAY12,
			SUM(DECODE(DAYS, 18, AMT, 0)) DAY13,
			SUM(DECODE(DAYS, 17, AMT, 0)) DAY14,
			SUM(DECODE(DAYS, 16, AMT, 0)) DAY15,
			SUM(DECODE(DAYS, 15, AMT, 0)) DAY16,
			SUM(DECODE(DAYS, 14, AMT, 0)) DAY17,
			SUM(DECODE(DAYS, 13, AMT, 0)) DAY18,
			SUM(DECODE(DAYS, 12, AMT, 0)) DAY19,
			SUM(DECODE(DAYS, 11, AMT, 0)) DAY20,
			SUM(DECODE(DAYS, 10, AMT, 0)) DAY21,
			SUM(DECODE(DAYS,  9, AMT, 0)) DAY22,
			SUM(DECODE(DAYS,  8, AMT, 0)) DAY23,
			SUM(DECODE(DAYS,  7, AMT, 0)) DAY24,
			SUM(DECODE(DAYS,  6, AMT, 0)) DAY25,
			SUM(DECODE(DAYS,  5, AMT, 0)) DAY26,
			SUM(DECODE(DAYS,  4, AMT, 0)) DAY27,
			SUM(DECODE(DAYS,  3, AMT, 0)) DAY28,
			SUM(DECODE(DAYS,  2, AMT, 0)) DAY29,
			SUM(DECODE(DAYS,  1, AMT, 0)) DAY30,
			SUM(DECODE(DAYS,  0, AMT, 0)) RPTDT,
			SUM(DECODE(DAYS, -1, AMT, 0)) RPTDT01
		FROM
		(
			SELECT
				'2.Nguån vèn' ITEM1,
				DECODE(A.CODE, 	'B05006', '1.Ng¾n h¹n',
								'B05008', '1.Ng¾n h¹n',
								'B05009', '1.Ng¾n h¹n',
								'B05007', '2.Trung dµi h¹n',
								'B05010', '2.Trung dµi h¹n',
								'B05011', '2.Trung dµi h¹n',
								' ') ITEM2,
				DECODE(A.CODE, 	'B05008', 'b.Doanh nghiÖp',
								'B05009', 'a.C¸ nh©n',
								'B05010', 'b.Doanh nghiÖp',
								'B05011', 'a.C¸ nh©n',
								'Tæng céng') ITEM3,
				A.CCY CCYCD,
				(TO_DATE(&h_trdt, 'YYYYMMDD') - TO_DATE(A.PLNYR, 'YYYYMMDD')) DAYS,
				A.PLNAMT AMT
			FROM
				RT1.TBRT_PLAN A, RACE.T_CODE B
			WHERE
				A.CODE = B.CODE
				AND  A.BRCD = '9999'
				AND  A.RPTCD = 'FU25'
				AND  A.PLNYR BETWEEN TO_CHAR(TO_DATE(&h_trdt, 'YYYYMMDD') - 30, 'YYYYMMDD') AND &h_trdt
				AND  A.SEQ = '4'
				AND  B.CAT_NAME='GLMISRPTFU35'
				AND  B.COUNTRY='VN'
				AND  A.CODE IN ('B05001', 'B05006', 'B05008','B05009','B05007', 'B05010', 'B05011')
		)
		GROUP BY
			ITEM1, ITEM2, ITEM3, CCYCD

		UNION ALL

		SELECT
			ITEM1, ITEM2, ITEM3, CCYCD,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0
		FROM
			(SELECT DISTINCT CCYCD FROM LN1.TBLN_CCYINFO),
			(	SELECT '1.§¸o h¹n'		ITEM1, ' ' 					ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '1.§¸o h¹n'		ITEM1, ' ' 					ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '1.§¸o h¹n'		ITEM1, ' ' 					ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, ' ' 					ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '1.Ng¾n h¹n' 		ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '1.Ng¾n h¹n' 		ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '1.Ng¾n h¹n' 		ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '2.Trung dµi h¹n'	ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '2.Trung dµi h¹n'	ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '2.Nguån vèn'	ITEM1, '2.Trung dµi h¹n'	ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, ' ' 					ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '1.Tr­íc h¹n' 		ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '1.Tr­íc h¹n' 		ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '2.§óng h¹n' 		ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '2.§óng h¹n' 		ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '3.TrÔ h¹n' 			ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '3.Tr¶ nî'		ITEM1, '3.TrÔ h¹n' 			ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL UNION ALL
				SELECT '4.Gi¶i ng©n'	ITEM1, ' ' 					ITEM2, 'Tæng céng' 		ITEM3 FROM DUAL UNION ALL
				SELECT '4.Gi¶i ng©n'	ITEM1, ' ' 					ITEM2, 'a.C¸ nh©n' 		ITEM3 FROM DUAL UNION ALL
				SELECT '4.Gi¶i ng©n'	ITEM1, ' ' 					ITEM2, 'b.Doanh nghiÖp' ITEM3 FROM DUAL)
	)
	GROUP BY
		ITEM1, ITEM2, ITEM3, CCYCD
	ORDER BY
		ITEM1, ITEM2, ITEM3, CCYCD
)
