--DEFINE h_trdt = '20121013'

SELECT T.BRCD AS MA_CN,
       (SELECT BRCD.LCLBRNM
	FROM   TBCS_BRCD BRCD
	WHERE  BRCD.BRCD = T.BRCD) AS TEN_CN,

       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', NULL, T.PLGAMT_VND), NULL)) AS NHADAT_NT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', NULL, T.DSBSBAL_VND), NULL)) AS NHADAT_NT_DU_NO_QD,

       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', T.PLGAMT_VND, NULL), NULL)) AS DATNN_NT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '02', DECODE(T.CLDTLTPCD, '128', T.DSBSBAL_VND, NULL), NULL)) AS DATNN_NT_DU_NO_QD,

       SUM(DECODE(T.CLPOSTP, '01', DECODE(T.CLDTLTPCD, '128', T.PLGAMT_VND, NULL), NULL)) AS DATNN_DT_GIA_TRI_TSDB_QD,
       SUM(DECODE(T.CLPOSTP, '01', DECODE(T.CLDTLTPCD, '128', T.DSBSBAL_VND, NULL), NULL)) AS DATNN_DT_DU_NO_QD,

       SUM(T.PLGAMT_VND) AS TONG_GIA_TRI_TSDB_QD,
       SUM(T.DSBSBAL_VND) AS TONG_DU_NO_QD

FROM   (

	SELECT A.BRCDOWNR,
		A.CUSTSEQOWNR,
		A.BRCDCL || '-' || A.CLID || '-' || A.CLSEQ CLSEQ,
		A.CLDTLTPCD,
		B.CLSTSCD,
		B.GNTERLTNTPCD,
		B.GNTERLTNDESC,
		B.TRSPTSTSCD,
		B.MGRDT,
		B.CLQTYSZ,
		A.CLCCYCD,
		B.UNTFCAMT,
		A.PLGAMT,
		DECODE(A.CLCCYCD, 'VND', A.PLGAMT, CS1.EXCROSSCAL(A.BRCDCL, 'VND', &h_trdt, A.CLCCYCD, A.PLGAMT, '01', 'VND', '01')) PLGAMT_VND,
		A.BRCDLN,
		A.CUSTSEQLN,
		A.BRCDAPPR || '-' || A.APPRID || '-' || A.APPRSEQ APPRSEQ,
		A.BRCD,
		A.BRCD || '-' || A.DSBSID || '-' || A.DSBSSEQ DSBSSEQ,
		A.FNDPRPSTPCD,
		A.FNDPRPSUNIT,
		C.OTHRTPCD,
		A.CCYCD,
		A.DSBSBAL,
		DECODE(A.CCYCD, 'VND', A.DSBSBAL, CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, A.CCYCD, A.DSBSBAL, '01', 'VND', '01')) DSBSBAL_VND,
		SUBSTR(A.ACCTCD, 4, 1) BALGRP,
		DECODE(NVL(A.ACCTCD, '000000'), '000000', '', LN1.GET_PARM('LNTERM', 'ACCTCD', A.ACCTCD, '', '', 'NM')) LNTPCD,
		A.ACCTCD,
		DECODE(B.CLTPCD, '03', B.CLMGMTTPCD) CLMGMTTPCD,
		DECODE(B.CLTPCD, '03', B.CLMGMTMTHDTPCD) CLMGMTMTHDTPCD,
		DECODE(B.CLTPCD, '03', B.CLMGRNM) CLMGRNM,
		D.NM,
		E.PIVID || E.PIVSEQ PIVSEQ,
		E.BUSREGNO,
		E.INVRNM,
		E.PRJNM,
		B.REM,
		B.CRDTOFC,
		B.CLLOC,
		B.CLPOSTP

	FROM   LN1.TBLN_CLBAL A,
		LN1.TBLN_CL B,
		LN1.TBLN_DSBS C,
		(

		 SELECT A.BRCD,
			 CLID,
			 CLSEQ,
			 DECODE(NVL(A.NM, ' '), ' ', B.NMLOC, A.NM) NM
		 FROM   LN1.TBLN_CLREF A,
			 TBCM_GENERAL   B
		 WHERE  A.STSCD = '01'
			AND NVL(QTY, 0) = 0
			AND A.BRCD = B.BRCD(+)
			AND TRIM(A.REFNO) = B.CUSTSEQ(+)

		 ) D,
		(

		 SELECT PIVID,
			 PIVSEQ,
			 BUSREGNO,
			 INVRNM,
			 PRJNM
		 FROM   LN1.TBLN_PROJINVR A,
			 LN1.TBLN_PROJECT  B
		 WHERE  A.PRJID = B.PRJID
			AND A.PRJSEQ = B.PRJSEQ
			AND A.STSCD = '01'
			AND B.STSCD = '01'

		 ) E

	WHERE  A.TRDT = &h_trdt
	       AND A.BRCDCL = B.BRCD(+)
	       AND A.CLID = B.CLID(+)
	       AND A.CLSEQ = B.CLSEQ(+)
	       AND A.BRCD = C.BRCD(+)
	       AND A.DSBSID = C.DSBSID(+)
	       AND A.DSBSSEQ = C.DSBSSEQ(+)

	       AND B.BRCD = D.BRCD(+)
	       AND B.CLID = D.CLID(+)
	       AND B.CLSEQ = D.CLSEQ(+)
	       AND B.PIVID = E.PIVID(+)
	       AND B.PIVSEQ = E.PIVSEQ(+)

	       AND A.STSCD = '01'
	       AND (B.CLPOSTP = '02' OR
	       (B.CLPOSTP = '01' AND A.CLDTLTPCD = '128'))
	       AND
	       LN1.CHK_LNCUSTTP(A.BRCD, A.DSBSID, A.DSBSSEQ, A.CUSTSEQLN, 'CMP') = 'Y'

	) T

GROUP  BY T.BRCD

ORDER  BY T.BRCD;
