SELECT
			CUSTSEQLN CIF ,
			NMLOC TEN_KHACH_HANG,
			APPRSEQ HOP_DONG,
			DSBSSEQ KHE_UOC,
			LNSBTPNM LOAI_QUA_HAN,
			CCYCD LOAI_TIEN,
			DSBSAMT SO_TIEN_GIAI_NGAN,
			DSBSDT NGAY_GIAI_NGAN,
			MATDT NGAY_DAO_HAN,
			LSTTRFNRLDT NGAY_BAT_DAU_CHO_CHUYEN_NHOM,
			DSBSBAL DU_NO,
			LCLBRNM TEN_CHI_NHANH,
			BRCD MA_CHI_NHANH,
			REMK REMARK
		FROM
		(
			SELECT
				A.BRCD||'-'||C.CUSTSEQLN CUSTSEQLN,
				B.NMLOC,
				C.BRCD||'-LAV-'||C.APPRSEQ APPRSEQ,
				C.BRCD||'-LDS-'||C.DSBSSEQ DSBSSEQ,
				D.LNSBTPNM,
				C.CCYCD,
				C.DSBSAMT,
				C.DSBSDT,
				C.MATDT,
				A.LSTTRFNRLDT,
				C.DSBSBAL,
				E.LCLBRNM,
				A.BRCD,
				DECODE(SUBSTR(A.REMARK,1,2),'06','Maturity','10','Reschedule','') REMK
			FROM
				LN1.TBLN_PSTHIST A,TBCM_GENERAL B ,TBLN_DSBS C,TBLN_LNACCT D, TBCS_BRCD E
			WHERE A.BRCD=B.BRCD
				AND C.CUSTSEQLN=B.CUSTSEQ
				AND A.BRCD=C.BRCD
				AND C.DSBSID='LDS'
				AND A.DSBSSEQ=C.DSBSSEQ
				AND A.BRCD= D.BRCD
				AND C.LNTPCD=D.LNTPCD
				AND C.LNSBTPCD <> '01'
				AND A.STSCD='01'
				AND C.STSCD='01'
				AND C.LNSBTPCD=D.LNSBTPCD
				AND A.BRCD = E.BRCD

			UNION ALL

			SELECT
				A.CUSTSEQ,
				A.CUSTNM,
				A.CARDNBR,
				A.ACCTNO,
				A.LNSBTPNM,
				A.CCYCD,
				A.LIMIT,
				A.OPENDT,
				A.EXPDATE,
				A.PASTDUEDT,
				A.DEBITAMT,
				B.LCLBRNM,
				B.BRCD,
				'Credit card' REMK
			FROM
			(
				SELECT C.BRCD||'-'||C.CUSTSEQ CUSTSEQ,
				C.CUSTNM CUSTNM,
				C.CARDNBR||' ' CARDNBR,
				C.ACCTNO||' ' ACCTNO,
				C.CARDTP||' (Past due group '||C.CRDSBTPCD||')' LNSBTPNM,
				C.CCYCD,
				C.LIMIT,
				C.OPENDT OPENDT,
				C.EXPDATE,
				C.PASTDUEDT PASTDUEDT,
				C.DEBITAMT DEBITAMT
				FROM (
				SELECT A.CRDSBTPCD,A.CUSTSEQ CUSTSEQ, B.CUSTNM CUSTNM, B.CARDNBR CARDNBR, A.ACCTNO ACCTNO,
				DECODE(SIGN((TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD')-TO_DATE(A.PASTDUEDT,'YYYYMMDD') )), 1, FLOOR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD') - TO_DATE(A.PASTDUEDT,'YYYYMMDD')),0) TOTALPSTDUEDT,
				A.PASTDUEDT PASTDUEDT, DECODE(A.CRDTP, '1','MASTER','3','VISA','A','VISADEBIT','B','VISABUSINESS') CARDTP ,
				'VND' CCYCD, NVL(B.LMTAMT,'0') LIMIT, A.DEBITAMT DEBITAMT, B.OPENDT OPENDT,
				TO_CHAR(LAST_DAY( TO_DATE( '20'|| SUBSTR(B.EXPDATE,3,2) || SUBSTR(B.EXPDATE,1,2) || '01'
				,'YYYYMMDD')),'YYYYMMDD') EXPDATE,
				DECODE (SUBSTR(B.CARDNBR,1,10),'5483702812', 'MS' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'5428538212', 'MG' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4239608157', 'VC' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4041523485', 'VG' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4220946370', 'VD' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4363088181', 'V1' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4181590123', 'VB' || SUBSTR(B.CARDNBR,11,6), '0'))))))) CARD,
				A.PAMT , A.BRCD, A.CRDTP, B.SEMAACCT,A.LSTSTSDT
				FROM EI1.TBEI_CARDMST A, EI1.TBEI_CARD2ACCT B,EI1.TBEI_VSMCHEADER C,CM1.TBCM_GENERAL D
				WHERE A.BRCD = B.BRCD
				AND A.ACCTNO = B.ACCTCD
				AND A.CRDTP <> 'B'
				AND A.CRDSBTPCD <> '1'
				AND (A.EXPIREFLG='N' OR A.PAYMENTFLG='Y')
				AND A.ALLSBTPCD IS NOT NULL
				AND B.BRCD = C.BRCD
				AND DECODE(SUBSTR(B.CARDNBR,1,10),'5483702812',DECODE(SIGN(TO_NUMBER(SUBSTR(B.CARDNBR,11,2 )) - 0 ), 0, 'TC',DECODE(SIGN(TO_NUMBER(SUBSTR(B.CARDNBR,11,2 )) - 20 ), -1,'TC',
				DECODE (SUBSTR(B.CARDNBR,1,10),'5483702812', 'MS'))),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4239608157', 'VC',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4041523485', 'VG' ,
				DECODE (SUBSTR(B.CARDNBR,1,10),'4220946370', 'VD',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4181590123', 'VB',
				DECODE (SUBSTR(B.CARDNBR,1,6),'469655', 'VP',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4363088181', 'V1',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4363098181', 'V2',
				DECODE (SUBSTR(B.CARDNBR,1,10),'5428538212', 'MG'))))))))) || SUBSTR(B.CARDNBR,11,6) = C.CARDNBR
				AND A.CRDTP = C.CARDTYPE
				AND B.SEMAACCT = C.SEMAACCT
				AND A.ACCTNO = C.BKACCT
				AND C.TRMONTH = SUBSTR(LSTSTSDT, 5,2) || '/' || SUBSTR(LSTSTSDT, 1,4)
				AND A.BRCD=D.BRCD
				AND A.CUSTSEQ=D.CUSTSEQ
				) C , EI1.TBEI_VSMCHEADER D
				WHERE C.BRCD = D.BRCD(+)
				AND C.CARD = D.CARDNBR(+)
				AND C.CRDTP = D.CARDTYPE(+)
				AND C.SEMAACCT = D.SEMAACCT(+)
				AND C.ACCTNO = D.BKACCT(+)
				AND D.TRMONTH(+) = SUBSTR(C.LSTSTSDT, 5,2) || '/' || SUBSTR(C.LSTSTSDT, 1,4)
				AND C.OPENDT = (SELECT MAX(OPENDT)
				FROM EI1.TBEI_CARD2ACCT G
				WHERE G.BRCD = C.BRCD
				AND G.ACCTCD = C.ACCTNO
				)
				GROUP BY C.CUSTSEQ , C.CUSTNM , C.CARDNBR , C.ACCTNO ,
				C.TOTALPSTDUEDT,C.PASTDUEDT , C.CARDTP,C.CRDSBTPCD,
				C.CCYCD,C.LIMIT, C.DEBITAMT , C.OPENDT ,
				C.EXPDATE, C.CARD, C.PAMT, C.BRCD, C.CRDTP, C.SEMAACCT ,C.PAMT
				--==========///////////////////////////============================
				UNION ALL

				SELECT C.BRCD||'-'||C.CUSTSEQ CUSTSEQ,
				C.CUSTNM CUSTNM,
				C.CARDNBR||' ' CARDNBR,
				C.ACCTNO||' ' ACCTNO,
				C.CARDTP||' (Past due group '||C.CRDSBTPCD||')',
				C.CCYCD,
				C.LIMIT,
				C.OPENDT OPENDT,
				C.EXPDATE,
				C.PASTDUEDT PASTDUEDT,
				C.DEBITAMT DEBITAMT
				FROM (
				SELECT A.CRDSBTPCD,A.CUSTSEQ CUSTSEQ, B.CUSTNM CUSTNM, B.CARDNBR CARDNBR, A.ACCTNO ACCTNO,
				DECODE(SIGN((TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD')-TO_DATE(A.PASTDUEDT,'YYYYMMDD') )), 1, FLOOR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD') - TO_DATE(A.PASTDUEDT,'YYYYMMDD')),0) TOTALPSTDUEDT,
				A.PASTDUEDT PASTDUEDT, DECODE(A.CRDTP, '1','MASTER','3','VISA','A','VISADEBIT','B','VISABUSINESS') CARDTP ,
				'VND' CCYCD, NVL(B.LMTAMT,'0') LIMIT, A.DEBITAMT DEBITAMT, B.OPENDT OPENDT,
				TO_CHAR(LAST_DAY( TO_DATE( '20'|| SUBSTR(B.EXPDATE,3,2) || SUBSTR(B.EXPDATE,1,2) || '01'
				,'YYYYMMDD')),'YYYYMMDD') EXPDATE,
				DECODE (SUBSTR(B.CARDNBR,1,10),'5483702812', 'MS' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'5428538212', 'MG' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4239608157', 'VC' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4041523485', 'VG' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4220946370', 'VD' || SUBSTR(B.CARDNBR,11,6),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4181590123', 'VB' || SUBSTR(B.CARDNBR,11,6), '0')))))) CARD,
				A.PAMT , A.BRCD, A.CRDTP, B.SEMAACCT,A.LSTSTSDT
				FROM EI1.TBEI_CARDMST A, EI1.TBEI_CARD2ACCT B,EI1.TBEI_VSMCHEADER C,CM1.TBCM_GENERAL D,
				EI1.TBEI_EMPLOYEE K, EI1.TBEI_CIF L
				WHERE A.BRCD = B.BRCD
				AND A.ACCTNO = B.ACCTCD
				AND A.CRDTP = 'B'
				AND A.CRDSBTPCD <> '1'
				AND (A.EXPIREFLG='N' OR A.PAYMENTFLG='Y')
				AND A.ALLSBTPCD IS NOT NULL
				AND B.BRCD = C.BRCD
				AND DECODE(SUBSTR(B.CARDNBR,1,10),'5483702812',DECODE(SIGN(TO_NUMBER(SUBSTR(B.CARDNBR,11,2 )) - 0 ), 0, 'TC',DECODE(SIGN(TO_NUMBER(SUBSTR(B.CARDNBR,11,2 )) - 20 ), -1,'TC',
				DECODE (SUBSTR(B.CARDNBR,1,10),'5483702812', 'MS'))),
				DECODE (SUBSTR(B.CARDNBR,1,10),'4239608157', 'VC',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4041523485', 'VG' ,
				DECODE (SUBSTR(B.CARDNBR,1,10),'4220946370', 'VD',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4181590123', 'VB',
				DECODE (SUBSTR(B.CARDNBR,1,6),'469655', 'VP',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4363088181', 'V1',
				DECODE (SUBSTR(B.CARDNBR,1,10),'4363098181', 'V2',
				DECODE (SUBSTR(B.CARDNBR,1,10),'5428538212', 'MG'))))))))) || SUBSTR(B.CARDNBR,11,6) = C.CARDNBR
				AND A.CRDTP = C.CARDTYPE
				AND B.SEMAACCT = C.SEMAACCT
				AND A.ACCTNO = C.BKACCT
				AND C.TRMONTH = SUBSTR(LSTSTSDT, 5,2) || '/' || SUBSTR(LSTSTSDT, 1,4)
				AND A.DEBITAMT>100
				AND TO_CHAR(SYSDATE,'YYYYMMDD') > SUBSTR(C.DUEDTE,7,4)||SUBSTR(C.DUEDTE,4,2)||SUBSTR(C.DUEDTE,1,2)
				AND A.BRCD=D.BRCD
				AND A.CUSTSEQ=D.CUSTSEQ
				AND A.BRCD = K.BRCD
				AND A.CUSTSEQ = K.CUSTSEQEMPLOY
				AND A.ACCTNO = K.PAYACCT
				AND K.BRCD = L.BRCD
				AND K.CUSTSEQ = L.CUSTSEQ
				) C , EI1.TBEI_VSMCHEADER D
				WHERE C.BRCD = D.BRCD(+)
				AND C.CARD = D.CARDNBR(+)
				AND C.CRDTP = D.CARDTYPE(+)
				AND C.SEMAACCT = D.SEMAACCT(+)
				AND C.ACCTNO = D.BKACCT(+)
				AND D.TRMONTH(+) = SUBSTR(C.LSTSTSDT, 5,2) || '/' || SUBSTR(C.LSTSTSDT, 1,4)
				AND C.OPENDT = (SELECT MAX(OPENDT)
				FROM EI1.TBEI_CARD2ACCT G
				WHERE G.BRCD = C.BRCD
				AND G.ACCTCD = C.ACCTNO
				)
				GROUP BY C.CUSTSEQ , C.CUSTNM , C.CARDNBR , C.ACCTNO ,
				C.TOTALPSTDUEDT,C.PASTDUEDT , C.CARDTP,C.CRDSBTPCD,
				C.CCYCD,C.LIMIT, C.DEBITAMT , C.OPENDT ,
				C.EXPDATE, C.CARD, C.PAMT, C.BRCD, C.CRDTP, C.SEMAACCT ,C.PAMT
			) A, CS1.TBCS_BRCD B
			WHERE
				SUBSTR(A.CUSTSEQ, 1, 4) = B.BRCD
		)
		ORDER BY
			CUSTSEQLN, APPRSEQ, DSBSSEQ
	;
