--DEFINE h_trdt = '20120918'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT
	A.BRCD, A.GRP_LN NHOM_NO, A.CCYCD,
	A.CUSTSEQ, B.SHRTNM KHACH_HANG,
	A.APPRSEQ HOP_DONG, A.TRSEQ KHE_UOC,
	SUM(A.TDBAL) DU_NO, SUM(A.TDBAL_VND) DU_NO_QUY_DOI
FROM
(
	SELECT
		A.BRCD,
		A.CUSTSEQ, A.CCY CCYCD,
		A.ACCTCD TRSEQ, '' APPRSEQ,
		DECODE(SUBSTR(A.ACCTCD, 1, 2), '28', 'NHOM 5', '29', 'NHOM 5',
						DECODE(SUBSTR(A.ACCTCD, 4, 1), '1', 'NHOM 1',
								'2', 'NHOM 2', '3', 'NHOM 3',
								'4', 'NHOM 4', 'NHOM 5')) GRP_LN,
		A.TDBAL,
		CS1.EXCROSSCAL (A.BRCD, 'VND', &h_trdt, A.CCY, NVL(A.TDBAL,0), '01', 'VND', '01') TDBAL_VND
	FROM
		GL1.TBGL_MAST A
	WHERE
		A.TRDT 		= 	 &h_trdt
		AND A.BRCD 	LIKE  '%'
		AND A.ACCTCD LIKE '2%'
		AND SUBSTR(A.ACCTCD, 1, 3) NOT IN ('211', '212', '213', '222','223','241', '271')
		AND SUBSTR(A.ACCTCD, 3, 1) NOT IN ('7', '9')
		AND A.TDBAL > 0
		--AND LN1.CHK_LNCUSTTP(A.BRCD, '', '', A.CUSTSEQ, 'OOC') = 'Y'
		AND LN1.CHKACCT20SBV(A.ACCTCD, A.CCY) = 'Y'
	) A, TBCM_GENERAL B
WHERE
	A.BRCD = B.BRCD(+)
	AND A.CUSTSEQ = B.CUSTSEQ(+)
GROUP BY
	A.BRCD, A.GRP_LN, A.CUSTSEQ, B.SHRTNM, A.APPRSEQ, A.TRSEQ, A.CCYCD

