--DEFINE h_trdt='20110922'
SELECT BRCD,LCLBRNM,SUM(QUIDOIDUDAU_DUPHONGCUTHE),SUM(DUCO_DUPHONGCUTHE),SUM(DUNO_DUPHONGCUTHE),SUM(QUIDOI_DUPHONGCUTHE),
						SUM(QUIDOIDUDAU_DUPHONGCHUNG),SUM(DUCO_DUPHONGCHUNG),SUM(DUNO_DUPHONGCHUNG),SUM(QUIDOI_DUPHONGCHUNG),
						SUM(QUIDOIDUDAU_SUDUNGDUPHONG),SUM(DUCO_SUDUNGDUPHONG),SUM(DUNO_SUDUNGDUPHONG),SUM(QUIDOI_SUDUNGDUPHONG)
FROM
(
		SELECT	A.ACCTCD,
					A.BRCD,E.LCLBRNM,
					A.TRDT, A.CCY,
							A.CUSTSEQ,
							C.NMLOC CUSTNM
							,ABS(SUM(A.TDBAL))DUPHONGCUTHE,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.PDBAL)))QUIDOIDUDAU_DUPHONGCUTHE,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.CRAMT)))DUCO_DUPHONGCUTHE,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.DRAMT)))DUNO_DUPHONGCUTHE,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.TDBAL))) QUIDOI_DUPHONGCUTHE,
							0 DUPHONGCHUNG,
							0 QUIDOIDUDAU_DUPHONGCHUNG,
							0 DUCO_DUPHONGCHUNG,
							0 DUNO_DUPHONGCHUNG,
							0 QUIDOI_DUPHONGCHUNG,
							0 SUDUNGDUPHONG,
							0 QUIDOIDUDAU_SUDUNGDUPHONG,
							0 DUCO_SUDUNGDUPHONG,
							0 DUNO_SUDUNGDUPHONG,
							0 QUIDOI_SUDUNGDUPHONG

					 FROM    TBGL_MAST A,
					 		TBCM_GENERAL C,CS1.TBCS_BRCD E
						 WHERE   A.TRDT LIKE &h_trdt
						 AND	A.BRCD=C.BRCD(+)
						 AND	A.CUSTSEQ=C.CUSTSEQ(+)
						 AND A.ACCTCD IN('209100','219100','229100','239100','249100','259100','269100','279100') --tkdu phong cuthe
			             AND	A.BRCD = E.BRCD
			             AND A.TDBAL<>0
			GROUP BY A.ACCTCD,
					A.BRCD,E.LCLBRNM,
					A.TRDT, A.CCY,
							A.CUSTSEQ,
							C.NMLOC
UNION ALL
		SELECT	A.ACCTCD,
				A.BRCD,E.LCLBRNM,
				A.TRDT, A.CCY,
						A.CUSTSEQ,
						C.NMLOC CUSTNM,
						0 DUPHONGCUTHE,
							0 QUIDOIDUDAU_DUPHONGCUTHE,
							0 DUCO_DUPHONGCUTHE,
							0 DUNO_DUPHONGCUTHE,
							0 QUIDOI_DUPHONGCUTHE,
							ABS(SUM(A.TDBAL)) DUPHONGCHUNG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.PDBAL))) QUIDOIDUDAU_DUPHONGCHUNG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.CRAMT))) DUCO_DUPHONGCHUNG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.DRAMT))) DUNO_DUPHONGCHUNG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.TDBAL))) QUIDOI_DUPHONGCHUNG,
							0 SUDUNGDUPHONG,
							0 QUIDOIDUDAU_SUDUNGDUPHONG,
							0 DUCO_SUDUNGDUPHONG,
							0 DUNO_SUDUNGDUPHONG,
							0 QUIDOI_SUDUNGDUPHONG

				 FROM    TBGL_MAST A,
				 		TBCM_GENERAL C,CS1.TBCS_BRCD E
					 WHERE   A.TRDT   LIKE &h_trdt
					 AND	A.BRCD=C.BRCD(+)
					 AND	A.CUSTSEQ=C.CUSTSEQ(+)
					 AND A.ACCTCD IN('209200','219200','229200','239200','249200','259200','269200','279200','489500') --tkdu phong chung

		             AND	A.BRCD = E.BRCD
		             AND A.TDBAL<>0
		GROUP BY A.ACCTCD,
				A.BRCD,E.LCLBRNM,
				A.TRDT, A.CCY,
						A.CUSTSEQ,
						C.NMLOC
UNION ALL
		SELECT	A.ACCTCD,
						A.BRCD,E.LCLBRNM,
						A.TRDT, A.CCY,
								A.CUSTSEQ,
								C.NMLOC CUSTNM,

							0 DUPHONGCUTHE,
							0 QUIDOIDUDAU_DUPHONGCUTHE,
							0 DUCO_DUPHONGCUTHE,
							0 DUNO_DUPHONGCUTHE,
							0 QUIDOI_DUPHONGCUTHE,
							0 DUPHONGCHUNG,
							0 QUIDOIDUDAU_DUPHONGCHUNG,
							0 DUCO_DUPHONGCHUNG,
							0 DUNO_DUPHONGCHUNG,
							0 QUIDOI_DUPHONGCHUNG,
							ABS(SUM(A.TDBAL))SUDUNGDUPHONG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.PDBAL)))QUIDOIDUDAU_SUDUNGDUPHONG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.CRAMT)))DUCO_SUDUNGDUPHONG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.DRAMT)))DUNO_SUDUNGDUPHONG,
							ABS(SUM(GL1.PERIODEXCHANGE_F('1', '1000', 'VND', A.CCY, A.TRDT, A.TRDT, A.TDBAL))) QUIDOI_SUDUNGDUPHONG
						 FROM    TBGL_MAST A,
						 		TBCM_GENERAL C,CS1.TBCS_BRCD E
							 WHERE   A.TRDT   LIKE &h_trdt
							 AND	A.BRCD=C.BRCD(+)
							 AND	A.CUSTSEQ=C.CUSTSEQ(+)
							 AND A.ACCTCD IN('971001','971201') --tkdu su dung du phong
				             AND	A.BRCD = E.BRCD
				             AND A.TDBAL<>0
				GROUP BY A.ACCTCD,
						A.BRCD,E.LCLBRNM,
						A.TRDT, A.CCY,
								A.CUSTSEQ,
								C.NMLOC
)GROUP BY BRCD,LCLBRNM
--ORDER BY ACCTCD

