--DEFINE h_trdt = '20090625'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT	'9999' BRCD, ITEM, SUM(OUTSTAND) OUTSTAND, SUM(INTPAY) INTPAY, 0 OUTSTAND_VND,0  INTPAY_VND, CCY,DECODE(CCY,'XXX','QDOI NGOAI TE SANG USD','YYY','QDOI NGOAI TE SANG VND','ZZZ','QDOI VND TAT CA CCY','') REMARK
FROM
(
		SELECT	BRCD, ITEM,	ABS(SUM(OUTSTAND)) OUTSTAND,ABS(SUM(INTPAY)) INTPAY,ABS(SUM(DECODE(CCY, 'VND', NVL(OUTSTAND, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(OUTSTAND, 0), '01', 'VND', '01')))) OUTSTAND_VND,
				ABS(SUM(DECODE(CCY, 'VND', NVL(INTPAY, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(INTPAY, 0), '01', 'VND', '01')))) INTPAY_VND,
				CCY
		FROM
		(
					/* Loan */
					SELECT	A.BRCD, A.CUSTSEQ,
							DECODE(SUBSTR(A.ACCTCD,4,1), '1', DECODE(SUBSTR(A.ACCTCD,1,3), '212', 'B.CHO VAY TRUNG HAN',
												'213', 'C.CHO VAY DAI HAN',
												'222', 'D.CHO VAY CAM CO',
												'A.CHO VAY NGAN HAN'),
								'2', 'DA1.NO QUA HAN NHOM 2-3', '3', 'DA1.NO QUA HAN NHOM 2-3',
								'4', 'DA2.NO QUA HAN NHOM 4-5', '5', 'DA2.NO QUA HAN NHOM 4-5')  ITEM,A.CCY,
							SUM(A.LDRBAL) OUTSTAND,
							SUM(A.LDRBAL*DECODE(B.INTRTTPCD, '01', B.TOTALRATE, B.BASERATE+B.SPRD)/100) INTPAY
					FROM	GL1.TBGL_BALDD A, LN1.TBLN_DSBS B
					WHERE	A.TRDT 		= &h_trdt
							AND 	SUBSTR(A.ACCTCD,1,1)	=	'2'
							AND 	A.BUSCD		= 'LN'
							AND 	A.LDRBAL	> 0
							AND 	A.BRCD		= B.BRCD
							AND 	A.TRREF		= B.DSBSID
							AND 	A.TRSEQ		= B.DSBSSEQ
					GROUP BY A.BRCD, A.CUSTSEQ, A.ACCTCD, A.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,
							DECODE(SUBSTR(ACCTCD,1,4), '2211', 'DA3.CHO VAY CHIET KHAU', 'DA4.CHO VAY CAC TCTD') ITEM,
							CCY, SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT 	= &h_trdt
							AND 	(SUBSTR(ACCTCD,1,4) = '2211' OR SUBSTR(ACCTCD,1,2)='20')
							AND 	TDBAL 	<> 0
					GROUP BY BRCD, CUSTSEQ, CCY, ACCTCD

					/* GL	*/
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'E.TIEN GUI NHNN' ITEM,CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('111100','111300','111600')
						  --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'F.DAU TU TRAI PHIEU' ITEM,CCY,SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('115100','115300','115400')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GA1.TG TAI TCTD KKH NN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('122100','122300')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GA2.TG TAI TCTD CO KH NN' ITEM, CCY, max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
									   AND A.CCYCD = G.CCYCD(+)
			  						   AND B.VALDT (+)  <= &h_trdt--M.TRDT
									   AND B.DLLASTSTSCD in('03','09')
									   AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('122200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ , 'GB1.TG TAI TCTD KKH TN' ITEM,  CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('131100')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GB2.TG TAI TCTD CO KH TN' ITEM,CCY, max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
									   	AND A.CCYCD = G.CCYCD(+)
			  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
									   	AND B.DLLASTSTSCD in('03','09')
									   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('131200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
							   		   --AND C.CUSTDTLTPCD not in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'H.HUM VON LIEN DOANH' ITEM,CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('134100','134200')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'I.DAU TU CHUNG KHOAN' ITEM,CCY,SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('123100','123201','123202','133100','133201','133202')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'J.VON DIEU CHUYEN' ITEM,CCY,DECODE('9999','9999',0,SUM(TDBAL))  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('519102')
						   	AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'K.TIEN MAT TAI QUY' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('101101','101102','101103','101201','101202','101300',
						   	   		  	 	'101901','101902','102100','102200','102300','102900',
											'103101','103102','103103','103200','103300','103900',
											'104100','104300','104900','105101','105102','105901',
											'105902','105903')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
				)
			GROUP BY BRCD, ITEM, CCY
			UNION ALL
			/*QUI DOI USD CHO TAT CA CCYCD LA NGOAI TE*/
			SELECT	BRCD, ITEM,
					ABS(SUM(DECODE(CCY, 'VND', NVL(OUTSTAND, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(OUTSTAND, 0), '01', 'USD', '01')))) OUTSTAND,
					ABS(SUM(DECODE(CCY, 'VND', NVL(INTPAY, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(INTPAY, 0), '01', 'USD', '01')))) INTPAY,
					0 OUTSTAND_VND,0 INTPAY_VND,'XXX' CCY
			FROM (
				 /* Loan */
					SELECT	A.BRCD, A.CUSTSEQ,
							DECODE(SUBSTR(A.ACCTCD,4,1), '1', DECODE(SUBSTR(A.ACCTCD,1,3), '212', 'B.CHO VAY TRUNG HAN',
												'213', 'C.CHO VAY DAI HAN',
												'222', 'D.CHO VAY CAM CO',
												'A.CHO VAY NGAN HAN'),
								'2', 'DA1.NO QUA HAN NHOM 2-3', '3', 'DA1.NO QUA HAN NHOM 2-3',
								'4', 'DA2.NO QUA HAN NHOM 4-5', '5', 'DA2.NO QUA HAN NHOM 4-5')  ITEM,
							A.CCY,SUM(A.LDRBAL) OUTSTAND,
							SUM(A.LDRBAL*DECODE(B.INTRTTPCD, '01', B.TOTALRATE, B.BASERATE+B.SPRD)/100) INTPAY
					FROM	GL1.TBGL_BALDD A, LN1.TBLN_DSBS B
					WHERE	A.TRDT 		= &h_trdt
							AND 	SUBSTR(A.ACCTCD,1,1)	=	'2'
							AND 	A.BUSCD		= 'LN'
							AND 	A.LDRBAL	> 0
							AND 	A.BRCD		= B.BRCD
							AND 	A.TRREF		= B.DSBSID
							AND 	A.TRSEQ		= B.DSBSSEQ
					GROUP BY A.BRCD, A.CUSTSEQ, A.ACCTCD, A.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,
							DECODE(SUBSTR(ACCTCD,1,4), '2211', 'DA3.CHO VAY CHIET KHAU', 'DA4.CHO VAY CAC TCTD') ITEM,
							CCY, SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT 	= &h_trdt
							AND 	(SUBSTR(ACCTCD,1,4) = '2211' OR SUBSTR(ACCTCD,1,2)='20')
							AND 	TDBAL 	<> 0
					GROUP BY BRCD, CUSTSEQ, CCY, ACCTCD
					/* GL	*/
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'E.TIEN GUI NHNN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('111100','111300','111600')
						  --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'F.DAU TU TRAI PHIEU' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('115100','115300','115400')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GA1.TG TAI TCTD KKH NN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('122100','122300')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GA2.TG TAI TCTD CO KH NN' ITEM,CCY,
						   	max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
								   		AND A.CCYCD = G.CCYCD(+)
		  						   		AND B.VALDT (+)  <= &h_trdt--M.TRDT
								   		AND B.DLLASTSTSCD in('03','09')
								   		AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('122200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GB1.TG TAI TCTD KKH TN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('131100')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GB2.TG TAI TCTD CO KH TN' ITEM,CCY,
						   	max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
							SELECT	A.brcd,A.CCYCD,G.INTRT
							FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
							WHERE	A.BRCD 	 	= B.BRCD 		AND
									A.DLTPCD  	= B.DLTPCD 	   		AND
									A.SBTPCD 	= B.SBTPCD 			AND
									A.DLSEQNO 	= B.DLSEQNO			AND
									A.BRCD 		= G.BRCD (+)		AND
									A.DLTPCD 	= G.DLTPCD (+)		AND
									A.SBTPCD 	= G.SBTPCD 	(+)	AND
									A.DLSEQNO 	= G.DLSEQNO  (+)
								   	AND A.CCYCD = G.CCYCD(+)
		  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
								   	AND B.DLLASTSTSCD in('03','09')
								   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('131200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD not in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'H.HUM VON LIEN DOANH' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('134100','134200')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'I.DAU TU CHUNG KHOAN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('123100','123201','123202','133100','133201','133202')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,	'J.VON DIEU CHUYEN' ITEM,CCY, DECODE('9999','9999',0,SUM(TDBAL))  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('519102')
						   	AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'K.TIEN MAT TAI QUY' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('101101','101102','101103','101201','101202','101300',
						   	   		  	 	'101901','101902','102100','102200','102300','102900',
											'103101','103102','103103','103200','103300','103900',
											'104100','104300','104900','105101','105102','105901',
											'105902','105903')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
				)
			WHERE CCY NOT IN ('VND','GD1')
			GROUP BY BRCD, ITEM, CCY
			UNION ALL
			/*QUI DOI VND CHO TAT CA CCYCD LA NGOAI TE*/
			SELECT	BRCD, ITEM,
					ABS(SUM(DECODE(CCY, 'VND', NVL(OUTSTAND, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(OUTSTAND, 0), '01', 'VND', '01')))) OUTSTAND,
					ABS(SUM(DECODE(CCY, 'VND', NVL(INTPAY, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(INTPAY, 0), '01', 'VND', '01')))) INTPAY,
					0 OUTSTAND_VND,0 INTPAY_VND,'YYY' CCY

			FROM
			(
					SELECT	A.BRCD, A.CUSTSEQ,
							DECODE(SUBSTR(A.ACCTCD,4,1), '1', DECODE(SUBSTR(A.ACCTCD,1,3), '212', 'B.CHO VAY TRUNG HAN',
												'213', 'C.CHO VAY DAI HAN',
												'222', 'D.CHO VAY CAM CO',
												'A.CHO VAY NGAN HAN'),
								'2', 'DA1.NO QUA HAN NHOM 2-3', '3', 'DA1.NO QUA HAN NHOM 2-3',
								'4', 'DA2.NO QUA HAN NHOM 4-5', '5', 'DA2.NO QUA HAN NHOM 4-5')  ITEM,
							A.CCY,
							SUM(A.LDRBAL) OUTSTAND,
							SUM(A.LDRBAL*DECODE(B.INTRTTPCD, '01', B.TOTALRATE, B.BASERATE+B.SPRD)/100) INTPAY
					FROM	GL1.TBGL_BALDD A, LN1.TBLN_DSBS B
					WHERE	A.TRDT 		= &h_trdt
							AND 	SUBSTR(A.ACCTCD,1,1)	=	'2'
							AND 	A.BUSCD		= 'LN'
							AND 	A.LDRBAL	> 0
							AND 	A.BRCD		= B.BRCD
							AND 	A.TRREF		= B.DSBSID
							AND 	A.TRSEQ		= B.DSBSSEQ
					GROUP BY A.BRCD, A.CUSTSEQ, A.ACCTCD, A.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,
							DECODE(SUBSTR(ACCTCD,1,4), '2211', 'DA3.CHO VAY CHIET KHAU', 'DA4.CHO VAY CAC TCTD') ITEM,
							CCY, SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT 	= &h_trdt
							AND 	(SUBSTR(ACCTCD,1,4) = '2211' OR SUBSTR(ACCTCD,1,2)='20')
							AND 	TDBAL 	<> 0
					GROUP BY BRCD, CUSTSEQ, CCY, ACCTCD
					/* GL	*/
					union all
					SELECT	BRCD, CUSTSEQ ,'E.TIEN GUI NHNN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('111100','111300','111600')
						  --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'F.DAU TU TRAI PHIEU' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('115100','115300','115400')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GA1.TG TAI TCTD KKH NN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE   TRDT = &h_trdt
						   	AND ACCTCD IN ('122100','122300')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,
						   'GA2.TG TAI TCTD CO KH NN' ITEM,
						   	CCY, max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
									   	AND A.CCYCD = G.CCYCD(+)
			  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
									   	AND B.DLLASTSTSCD in('03','09')
									   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('122200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GB1.TG TAI TCTD KKH TN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('131100')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GB2.TG TAI TCTD CO KH TN' ITEM,CCY,max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
							SELECT	A.brcd,A.CCYCD,G.INTRT
							FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
							WHERE	A.BRCD 	 	= B.BRCD 		AND
									A.DLTPCD  	= B.DLTPCD 	   		AND
									A.SBTPCD 	= B.SBTPCD 			AND
									A.DLSEQNO 	= B.DLSEQNO			AND
									A.BRCD 		= G.BRCD (+)		AND
									A.DLTPCD 	= G.DLTPCD (+)		AND
									A.SBTPCD 	= G.SBTPCD 	(+)	AND
									A.DLSEQNO 	= G.DLSEQNO  (+)
								   	AND A.CCYCD = G.CCYCD(+)
		  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
								   	AND B.DLLASTSTSCD in('03','09')
								   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('131200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD not in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'H.HUM VON LIEN DOANH' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('134100','134200')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'I.DAU TU CHUNG KHOAN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('123100','123201','123202','133100','133201','133202')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'J.VON DIEU CHUYEN' ITEM,CCY, DECODE('9999','9999',0,SUM(TDBAL))  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('519102')
						   	AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'K.TIEN MAT TAI QUY' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('101101','101102','101103','101201','101202','101300',
						   	   		  	 	'101901','101902','102100','102200','102300','102900',
											'103101','103102','103103','103200','103300','103900',
											'104100','104300','104900','105101','105102','105901',
											'105902','105903')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
				)
			WHERE CCY NOT IN ('VND','GD1')
			GROUP BY BRCD, ITEM, CCY
			union ALL
			/*QUI DOI VND CHO TAT CA CCYCD*/
			SELECT	BRCD, ITEM,ABS(SUM(DECODE(CCY, 'VND', NVL(OUTSTAND, 0),
					CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(OUTSTAND, 0), '01', 'VND', '01')))) OUTSTAND,
					ABS(SUM(DECODE(CCY, 'VND', NVL(INTPAY, 0),
							CS1.excrosscal (BRCD, 'VND', &h_trdt, CCY, NVL(INTPAY, 0), '01', 'VND', '01')))) INTPAY,
					0 OUTSTAND_VND,0 INTPAY_VND,'ZZZ' CCY

			FROM (
				 /* Loan */
					SELECT	A.BRCD, A.CUSTSEQ,
							DECODE(SUBSTR(A.ACCTCD,4,1), '1', DECODE(SUBSTR(A.ACCTCD,1,3), '212', 'B.CHO VAY TRUNG HAN',
												'213', 'C.CHO VAY DAI HAN',
												'222', 'D.CHO VAY CAM CO',
												'A.CHO VAY NGAN HAN'),
								'2', 'DA1.NO QUA HAN NHOM 2-3', '3', 'DA1.NO QUA HAN NHOM 2-3',
								'4', 'DA2.NO QUA HAN NHOM 4-5', '5', 'DA2.NO QUA HAN NHOM 4-5')  ITEM,A.CCY,
							SUM(A.LDRBAL) OUTSTAND,
							SUM(A.LDRBAL*DECODE(B.INTRTTPCD, '01', B.TOTALRATE, B.BASERATE+B.SPRD)/100) INTPAY
					FROM	GL1.TBGL_BALDD A, LN1.TBLN_DSBS B
					WHERE	A.TRDT 		= &h_trdt
							AND 	SUBSTR(A.ACCTCD,1,1)	=	'2'
							AND 	A.BUSCD		= 'LN'
							AND 	A.LDRBAL	> 0
							AND 	A.BRCD		= B.BRCD
							AND 	A.TRREF		= B.DSBSID
							AND 	A.TRSEQ		= B.DSBSSEQ
					GROUP BY A.BRCD, A.CUSTSEQ, A.ACCTCD, A.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,
							DECODE(SUBSTR(ACCTCD,1,4), '2211', 'DA3.CHO VAY CHIET KHAU', 'DA4.CHO VAY CAC TCTD') ITEM,
							CCY, SUM(TDBAL)  OUTSTAND,	0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT 	= &h_trdt
							AND 	(SUBSTR(ACCTCD,1,4) = '2211' OR SUBSTR(ACCTCD,1,2)='20')
							AND 	TDBAL 	<> 0
					GROUP BY BRCD, CUSTSEQ, CCY, ACCTCD

					/* GL	*/
					union all
					SELECT	BRCD, CUSTSEQ ,'E.TIEN GUI NHNN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('111100','111300','111600')
						  --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY

					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'F.DAU TU TRAI PHIEU' ITEM,CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('115100','115300','115400')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GA1.TG TAI TCTD KKH NN' ITEM,CCY,SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('122100','122300')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GA2.TG TAI TCTD CO KH NN' ITEM,CCY,
						   	max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
									   	AND A.CCYCD = G.CCYCD(+)
			  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
									   	AND B.DLLASTSTSCD in('03','09')
									   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('122200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'GB1.TG TAI TCTD KKH TN' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('131100')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
			        SELECT	M.BRCD, M.CUSTSEQ ,'GB2.TG TAI TCTD CO KH TN' ITEM,CCY, max(M.TDBAL)  OUTSTAND,
						   	max(M.TDBAL)*(ROUND(sum(NVL(G.INTRT,0))/decode(COUNT(G.INTRT),1,1,0,1,count(g.intrt)),3)/100) INTPAY
					FROM	GL1.TBGL_MAST M, CM1.TBCM_GENERAL C,
						(
								SELECT	A.brcd,A.CCYCD,G.INTRT
								FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B,DL1.TBDL_INTSCH G
								WHERE	A.BRCD 	 	= B.BRCD 		AND
										A.DLTPCD  	= B.DLTPCD 	   		AND
										A.SBTPCD 	= B.SBTPCD 			AND
										A.DLSEQNO 	= B.DLSEQNO			AND
										A.BRCD 		= G.BRCD (+)		AND
										A.DLTPCD 	= G.DLTPCD (+)		AND
										A.SBTPCD 	= G.SBTPCD 	(+)	AND
										A.DLSEQNO 	= G.DLSEQNO  (+)
									   	AND A.CCYCD = G.CCYCD(+)
			  						   	AND B.VALDT (+)  <= &h_trdt--M.TRDT
									   	AND B.DLLASTSTSCD in('03','09')
									   	AND B.AUTHFLG='Y'

				   	   	) G
					WHERE	M.TRDT = &h_trdt
						   	AND M.ACCTCD IN ('131200')
						   	AND M.TDBAL > 0
						   	and m.brcd=g.brcd (+)
						   	AND G.CCYCD (+) = M.CCY
						   	AND C.BRCD   = M.BRCD
				   		   	AND C.CUSTSEQ=M.CUSTSEQ
				   		   --AND C.CUSTDTLTPCD not in('601','602')
					GROUP BY M.BRCD, M.CUSTSEQ, M.CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'H.HUM VON LIEN DOANH' ITEM,CCY,SUM(TDBAL)  OUTSTAND,0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('134100','134200')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY

					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'I.DAU TU CHUNG KHOAN' ITEM, CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('123100','123201','123202','133100','133201','133202')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ ,'J.VON DIEU CHUYEN' ITEM,CCY,DECODE('9999','9999',0,SUM(TDBAL))  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('519102')
						   	AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
					UNION ALL
					SELECT	BRCD, CUSTSEQ , 'K.TIEN MAT TAI QUY' ITEM,CCY, SUM(TDBAL)  OUTSTAND, 0 INTPAY
					FROM	GL1.TBGL_MAST
					WHERE	TRDT = &h_trdt
						   	AND ACCTCD IN ('101101','101102','101103','101201','101202','101300',
						   	   		  	 	'101901','101902','102100','102200','102300','102900',
											'103101','103102','103103','103200','103300','103900',
											'104100','104300','104900','105101','105102','105901',
											'105902','105903')
						   --AND TDBAL > 0
					GROUP BY BRCD, CUSTSEQ, CCY
				)
			GROUP BY BRCD, ITEM, CCY
)
GROUP BY ITEM, CCY
ORDER BY CCY,ITEM

