--thay doi: ngay lam viec Korebank
--define h_trdt = '20090901'
--define h_trdt = '20090901'

SELECT A.BRCD, A.CCYCD, SUM(A.CURBAL)
FROM
(	SELECT clr.BRCD, clr.DPTPCD, clr.ACCTSEQ, clr.CLRDT, mst.MATDT, mst.CCYCD, mst.CUSTSEQ, mst.IDXACNO, mst.CURBAL
	FROM
	(	SELECT BRCD, DPTPCD, ACCTSEQ, MIN(CLRDT) CLRDT
		FROM DP1.TBDP_SCLRBAL
		WHERE BRCD LIKE ''||'%'
		AND CLRDT <= &h_trdt
		GROUP BY BRCD, DPTPCD, ACCTSEQ
		HAVING MIN(CLRDT) >= &h_trdt
	) clr, DP1.TBDP_SAVMST mst
	WHERE clr.BRCD = mst.BRCD
	AND clr.DPTPCD = mst.DPTPCD
	AND clr.ACCTSEQ = mst.ACCTSEQ
	AND mst.CCYCD LIKE ''||'%'
) A,
(	SELECT BRCD, DPTPCD, ACCTSEQ, MIN(RENWDT) MINREN
	FROM DP1.TBDP_RENEW
	WHERE BRCD LIKE ''||'%'
	AND RENWDT > &h_trdt
	GROUP BY BRCD, DPTPCD, ACCTSEQ
) B,  DP1.TBDP_TRLST lst, CM1.TBCM_GENERAL gen
WHERE A.BRCD = B.BRCD(+)
AND A.DPTPCD = B.DPTPCD(+)
AND A.ACCTSEQ = B.ACCTSEQ(+)
AND A.BRCD = lst.BRCD(+)
AND A.DPTPCD = lst.DPTPCD(+)
AND A.ACCTSEQ = lst.ACCTSEQ(+)
AND lst.TRDT(+) BETWEEN &h_trdt AND &h_trdt
AND lst.TGTFLG(+) = 0
AND lst.CNCLTRFLG(+) = 0
AND gen.BRCD = '1000'
AND A.CUSTSEQ = gen.CUSTSEQ
AND gen.CUSTTPCD LIKE DECODE('3','1','100','%')
AND gen.CUSTTPCD NOT LIKE DECODE('3','1','999','2','100','999')
AND gen.CUSTTPCD NOT LIKE DECODE('3','1','999','2','100','999')
GROUP BY A.BRCD, A.CCYCD

