SELECT A.BRCD MACHINHANH, B.ENGBRSHRTNM TENCHINHANH,
	A.CUSTSEQ MAKHACHHANG, A.NM TENKHACHHANG, A.BRCD||A.TRREF||A.GNTESEQ REFNO,
	DECODE(A.TRREF, 'GCB', 'BAO LANH VAY VON', 'GTA', 'BAO LANH THANH TOAN', 'GPB', 'BAO LANH THUC HIEN HOP DONG', 'GBB', 'BAO LANH DU THAU', 'CAC CAM KET BAO LANH KHAC') LOAIBAOLANH,
	A.ISUDT NGAYPHATHANH, A.AMDMATDT NGAYDAOHAN,
	A.GNTECCYCD NGUYENTEBAOLANH, A.BAL TRIGIABAOLANH,
	A.BRCD||A.APPRTRREF||A.APPRDTALSEQ HOPDONGTINDUNG,
	C.CCYCD NGUYENTECUAHANMUCBAOLANH, C.APPRAMT HANMUCCAPBAOLANH,
	A.BTRTPCD NHOMNO
FROM
(
	select BRCD, CUSTSEQ, NM, TRREF, GNTESEQ, ISUDT, AMDMATDT, GNTECCYCD, sum(BAL) BAL, APPRTRREF, APPRDTALSEQ, BTRTPCD
	from
	(select MAS.brcd BRCD, MAS.CUSTSEQ CUSTSEQ, GEN.NM NM, MAS.TRREF TRREF, MAS.GNTESEQ GNTESEQ, MAS.ISUDT ISUDT, MAS.AMDMATDT AMDMATDT,
			b.CCY GNTECCYCD, sum(b.LDRBAL) BAL, MAS.APPRTRREF APPRTRREF, MAS.APPRDTALSEQ APPRDTALSEQ, MAS.BTRTPCD BTRTPCD
	from TF1.TBTF_GNTEMAS MAS, CM1.TBCM_GENERAL GEN, GL1.TBGL_BALDD b
	where  b.TRDT = &h_trdt
		and b.BRCD like '%'
		and b.BUSCD = 'TF'
		and b.UNTBUSCD = 'BF'
		and (b.ACCTCD like '921%01' or b.ACCTCD like '921%03' or b.ACCTCD like '922%01' or b.ACCTCD like '922%03' or b.ACCTCD like '926%01' or b.ACCTCD like '926%03' or b.ACCTCD like '927%01' or b.ACCTCD like '927%03' or b.ACCTCD like '928%01' or b.ACCTCD like '928%03')
		and b.TRREF like 'G%'
		and b.BRCD = MAS.brcd
		and b.TRREF = MAS.TRREF
		and b.TRSEQ = MAS.GNTESEQ
--		and MAS.cnclflg = 'N'
--		and MAS.delflg = 'N'
		and TRIM(MAS.APPRDTALSEQ) IS NOT NULL
		and MAS.CUSTSEQ like '%'
		and MAS.BRCD = GEN.BRCD(+)
		and MAS.CUSTSEQ = GEN.CUSTSEQ(+)
 		group by MAS.brcd, MAS.CUSTSEQ, GEN.NM, MAS.TRREF, MAS.GNTESEQ, MAS.ISUDT, MAS.AMDMATDT,
			b.CCY, MAS.APPRTRREF, MAS.APPRDTALSEQ, MAS.BTRTPCD

	union all

	select MAS.brcd, MAS.CUSTSEQ, GEN.NM NM, MAS.TRREF, MAS.GNTESEQ ,MAS.ISUDT, MAS.AMDMATDT,
			MAS.GNTECCYCD ccy, sum(MAS.GNTEBAL) BAL, MAS.APPRTRREF, MAS.APPRDTALSEQ, MAS.BTRTPCD
	from TF1.TBTF_GNTEMAS MAS, CM1.TBCM_GENERAL GEN
	where  	to_char(sysdate,'yyyymmdd') = &h_trdt
		and MAS.brcd like '%'
		and MAS.cnclflg = 'N'
		and MAS.delflg = 'N'
		and TRIM(MAS.APPRDTALSEQ) IS NOT NULL
		and MAS.GNTEBAL > 0
		and MAS.CUSTSEQ like '%'
		and MAS.BRCD = GEN.BRCD(+)
		and MAS.CUSTSEQ = GEN.CUSTSEQ(+)
	group by MAS.brcd, MAS.CUSTSEQ, GEN.NM, MAS.TRREF, MAS.GNTESEQ ,MAS.ISUDT, MAS.AMDMATDT,
			MAS.GNTECCYCD, MAS.APPRTRREF, MAS.APPRDTALSEQ, MAS.BTRTPCD
	)
	group by BRCD, CUSTSEQ, NM, TRREF, GNTESEQ, ISUDT, AMDMATDT, GNTECCYCD, APPRTRREF, APPRDTALSEQ, BTRTPCD
)A, TBCS_BRCD B, TBLN_APPR C
WHERE
	A.BAL > 0
	AND A.BRCD = B.BRCD
	AND A.BRCD = C.BRCD
	AND A.APPRTRREF = C.APPRID
	AND A.APPRDTALSEQ = C.APPRSEQ
ORDER BY A.BRCD, B.ENGBRSHRTNM, A.CUSTSEQ, A.TRREF,A. GNTECCYCD DESC
