SELECT A.BRCD, SBV.SBVCD SBVCODE,
	SUBSTR(A.ACCTCD,1,3)||DECODE(B.GROUPTYPE,'','1',B.GROUPTYPE)||SUBSTR(A.ACCTCD,5,2) TAIKHOAN,
	A.NEGOTRSEQ SOREF, A.CCYCD NGUYENTE, A.NEGOBAL SOTIEN,
	DECODE(A.CCYCD,'VND',A.NEGOBAL,
	CS1.EXCROSSCAL(A.BRCD,'VND',&h_trdt,A.CCYCD,A.NEGOBAL,'01','VND','01')) SOTIEN_QUYDOI,
	A.NEGODT NGAYMO, A.MATDT NGAYDAOHAN, A.COMMRT LAISUAT, DECODE(B.GROUPTYPE,'','1',B.GROUPTYPE) NHOMNO
FROM
(
	SELECT BAL.BRCD, BAL.BRCD||BAL.TRREF||BAL.TRSEQ NEGOTRSEQ, BAL.BRCD||BAL.CUSTSEQ CIF, GEN.NM CUSTINFO,
		BAL.ACCTCD, BAL.OPNDT NEGODT, BAL.MATDT , DECODE(STL.TRCCYCD, STL.STLCCYCD,  BAL.CCY,  'VND') CCYCD,
		DECODE(STL.TRCCYCD, STL.STLCCYCD, BAL.LDRBAL, ROUND(BAL.LDRBAL*ROUND(SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT)))) NEGOBAL,
		EXN.COMMRT, DECODE(DECODE(STL.TRCCYCD, STL.STLCCYCD,  BAL.CCY,  'VND'),'VND',1,DECODE(DECODE(STL.TRCCYCD, STL.STLCCYCD,  BAL.CCY,  'VND'),'GD1',3,2)) KIND
	FROM GL1.TBGL_BALDD BAL, TF1.TBTF_EXNCO EXN, TF1.TBTF_STLINFO STL, CM1.TBCM_GENERAL GEN
	WHERE
		BAL.TRDT = &h_trdt
		AND BAL.BRCD LIKE '%'
		AND BAL.BUSCD = 'TF'
		AND BAL.UNTBUSCD = 'EX'
		AND BAL.TRREF IN ('ESP','EUP','EDA','EDP','TTR','TTA')
		AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
		AND BAL.BRCD = EXN.BRCD
		AND BAL.TRREF = EXN.NEGOTRREF
		AND BAL.TRSEQ = EXN.NEGOTRSEQ
		AND BAL.CCY = EXN.CCYCD
		AND BAL.BRCD = STL.BRCD
		AND BAL.TRREF = STL.TRREF
		AND BAL.TRSEQ = STL.TRSEQ
		AND BAL.CCY = STL.TRCCYCD
		AND BAL.UNTBUSCD = STL.UNTBUSCD
		AND STL.TRCD IN ('W501','W521')
		AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
		AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
		AND BAL.BRCD = GEN.BRCD
		AND BAL.CUSTSEQ = GEN.CUSTSEQ
	GROUP BY BAL.TRDT, BAL.BRCD, BAL.TRREF, BAL.TRSEQ, BAL.CUSTSEQ, GEN.NM, BAL.ACCTCD, BAL.OPNDT,
		BAL.MATDT, STL.TRCCYCD, STL.STLCCYCD, BAL.CCY, BAL.LDRBAL, EXN.COMMRT
)A,  GL1.TBGL_SBVCD SBV,
(
SELECT DISTINCT MAS.BRCD, MAS.CUSTSEQ, SUBSTR(MAS.ACCTCD,4,1) GROUPTYPE
FROM GL1.TBGL_MAST MAS
WHERE
	MAS.TRDT = &h_trdt
	AND MAS.BRCD LIKE '%'
	AND MAS.ACCTCD LIKE '2%'
	AND SUBSTR(MAS.ACCTCD,1,3) <> '217'
	AND MAS.TDBAL > 0
ORDER BY MAS.BRCD, MAS.CUSTSEQ
)B
WHERE
	A.ACCTCD = SBV.ACCTCD AND
	A.KIND = SBV.BCCYFG AND
	A.BRCD = B.BRCD(+) AND
	SUBSTR(A.CIF,5,9) = B.CUSTSEQ(+)
ORDER BY A.CIF
