SELECT A.BRCD, B.ENGBRSHRTNM,
	ROUND(SUM(LC_USD)/1000,2) TRIGIACK_LC_USD,
	ROUND(SUM(NTDP_USD)/1000,2) TRIGIACK_NTDP_USD,
	ROUND(SUM(NTDA_USD)/1000,2) TRIGIACK_NTDA_USD,
	ROUND(SUM(NTTTR_USD)/1000,2) TRIGIACK_NTTTR_USD,
	ROUND(SUM(NTTTA_USD)/1000,2) TRIGIACK_NTTTA_USD,
	ROUND(SUM(LC_VND)/1000000) TRIGIACK_LC_VND,
	ROUND(SUM(NTDP_VND)/1000000) TRIGIACK_NTDP_VND,
	ROUND(SUM(NTDA_VND)/1000000) TRIGIACK_NTDA_VND,
	ROUND(SUM(NTTTR_VND)/1000000) TRIGIACK_NTTTR_VND,
	ROUND(SUM(NTTTA_VND)/1000000) TRIGIACK_NTTTA_VND,
	ROUND(SUM(LC_USD1)/1000,2) DUNOCK_LC_USD1,
	ROUND(SUM(NTDP_USD1)/1000,2) DUNOCK_NTDP_USD1,
	ROUND(SUM(NTDA_USD1)/1000,2) DUNOCK_NTDA_USD1,
	ROUND(SUM(NTTTR_USD1)/1000,2) DUNOCK_NTTTR_USD1,
	ROUND(SUM(NTTTA_USD1)/1000,2) DUNOCK_NTTTA_USD1,
	ROUND(SUM(LC_VND1)/1000000) DUNOCK_LC_VND1,
	ROUND(SUM(NTDP_VND1)/1000000) DUNOCK_NTDP_VND1,
	ROUND(SUM(NTDA_VND1)/1000000) DUNOCK_NTDA_VND1,
	ROUND(SUM(NTTTR_VND1)/1000000) DUNOCK_NTTTR_VND1,
	ROUND(SUM(NTTTA_VND1)/1000000) DUNOCK_NTTTA_VND1
FROM
(
	SELECT BRCD, SUM(LC_USD) LC_USD, SUM(NTDP_USD) NTDP_USD,
			SUM(NTDA_USD) NTDA_USD, SUM(NTTTR_USD) NTTTR_USD, SUM(NTTTA_USD) NTTTA_USD,
			SUM(LC_VND) LC_VND, SUM(NTDP_VND) NTDP_VND, SUM(NTDA_VND) NTDA_VND,
			SUM(NTTTR_VND) NTTTR_VND, SUM(NTTTA_VND) NTTTA_VND,
			0 LC_USD1, 0 NTDP_USD1, 0 NTDA_USD1, 0 NTTTR_USD1, 0 NTTTA_USD1,
			0 LC_VND1, 0 NTDP_VND1, 0 NTDA_VND1, 0 NTTTR_VND1, 0 NTTTA_VND1
	FROM
	(
		SELECT S.BRCD, S.STLCCYCD,
			SUM(CS1.excrosscal(S.BRCD,'VND',&h_trdt, S.STLCCYCD, S.STLAMT,'01','USD','01')) LC_USD,
			0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD, 0 LC_VND, 0 NTDP_VND,
			0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRCD IN ('W501')
			AND S.STLCCYCD <> 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD,
		SUM(CS1.excrosscal(S.BRCD,'VND',&h_trdt, S.STLCCYCD, S.STLAMT,'01','USD','01')) NTDP_USD,
		0 NTDP_USD, 0 NTTTR_USD, 0 NTTTA_USD, 0 LC_VND, 0 NTDP_VND, 0 NTDA_VND,
		0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'EDP'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD <> 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD,
		SUM(CS1.excrosscal(S.BRCD,'VND',&h_trdt, S.STLCCYCD, S.STLAMT,'01','USD','01')) NTDA_USD,
		0 NTTTR_USD, 0 NTTTA_USD, 0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'EDA'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD <> 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD,
		SUM(CS1.excrosscal(S.BRCD,'VND',&h_trdt, S.STLCCYCD, S.STLAMT,'01','USD','01')) NTTTR_USD,
		0 NTTTA_USD, 0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'TTR'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD <> 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD,
		SUM(CS1.excrosscal(S.BRCD,'VND',&h_trdt, S.STLCCYCD, S.STLAMT,'01','USD','01')) NTTTA_USD,
		0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'TTA'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD <> 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
			SUM(S.STLAMT) LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRCD IN ('W501')
			AND S.STLCCYCD = 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
			0 LC_VND, SUM(S.STLAMT) NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'EDP'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD = 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
			0 LC_VND, 0 NTDP_VND, SUM(S.STLAMT) NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'EDA'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD = 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
			0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, SUM(S.STLAMT) NTTTR_VND, 0 NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'TTR'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD = 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
		UNION ALL
		SELECT S.BRCD, S.STLCCYCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
			0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, SUM(S.STLAMT) NTTTA_VND
		FROM TBTF_STLINFO S, TBTF_EXNCO E
		WHERE
			S.BRCD  LIKE '%'
			AND (S.STLDT >= &h_trdt AND S.STLDT <= &h_trdt)
			AND S.TRREF = 'TTA'
			AND S.TRCD IN ('W521')
			AND S.STLCCYCD = 'VND'
			AND (S.CNCLDT = ' ' OR S.CNCLDT IS NULL)
			AND S.BRCD = E.BRCD
			AND S.TRREF = E.NEGOTRREF
			AND S.TRSEQ = E.NEGOTRSEQ
			AND (E.DELFLG = 'N' OR E.DELFLG IS NULL)
			AND (E.CNCLFLG= 'N' OR E.CNCLFLG IS NULL)
		GROUP BY S.BRCD, S.STLCCYCD
	)
	GROUP BY BRCD
	UNION ALL
	SELECT BRCD, 0 LC_USD, 0 NTDP_USD, 0 NTDA_USD, 0 NTTTR_USD, 0 NTTTA_USD,
		0 LC_VND, 0 NTDP_VND, 0 NTDA_VND, 0 NTTTR_VND, 0 NTTTA_VND,
		SUM(AMTLC_USD) LC_USD1, SUM(AMTNTDP_USD) NTDP_USD1,
		SUM(AMTNTDA_USD) NTDA_USD1, SUM(AMTNTTTR_USD) NTTTR_USD1,
		SUM(AMTNTTTA_USD) NTTTA_USD1,
		SUM(AMTLC_VND) LC_VND1, SUM(AMTNTDP_VND) NTDP_VND1,
		SUM(AMTNTDA_VND) NTDA_VND1, SUM(AMTNTTTR_VND) NTTTR_VND1,
		SUM(AMTNTTTA_VND) NTTTA_VND1
	FROM
	(
		SELECT BRCD, SUM(AMTLC_USD) AMTLC_USD, SUM(AMTLC_VND) AMTLC_VND,
			0 AMTNTDP_USD, 0 AMTNTDP_VND, 0 AMTNTDA_USD, 0 AMTNTDA_VND,
			0 AMTNTTTR_USD, 0 AMTNTTTR_VND, 0 AMTNTTTA_USD, 0 AMTNTTTA_VND
		FROM
		(
			SELECT BRCD,  TRSEQ,
				DECODE(TRCCYCD, STLCCYCD, SUM(CS1.excrosscal(BRCD,'VND',&h_trdt, CCY, LDRBAL,'01','USD','01')),0) AMTLC_USD,
				DECODE(TRCCYCD, STLCCYCD, 0, LDRBAL * TYGIA) AMTLC_VND
			FROM
			(
				SELECT BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD,
					SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT) TYGIA
				FROM TBGL_BALDD BAL, TBTF_STLINFO STL
				WHERE
					BAL.BRCD LIKE '%'
					AND BAL.TRDT = &h_trdt
					AND BAL.BUSCD = 'TF'
					AND BAL.UNTBUSCD = 'EX'
					AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
					AND BAL.TRREF IN ('ESP','EUP')
					AND BAL.BRCD = STL.BRCD
					AND BAL.TRREF = STL.TRREF
					AND BAL.TRSEQ = STL.TRSEQ
					AND	BAL.UNTBUSCD = STL.UNTBUSCD
					AND STL.TRCD IN ('W501','W521')
					AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
					AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
				GROUP BY BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD
			)
			GROUP BY BRCD, TRSEQ, LDRBAL, TRCCYCD, STLCCYCD, TYGIA
		)
		GROUP BY BRCD
		UNION ALL
		SELECT BRCD, 0 AMTLC_USD, 0 AMTLC_VND,
			SUM(AMTNTDP_USD) AMTNTDP_USD, SUM(AMTNTDP_VND) AMTNTDP_VND,
			SUM(AMTNTDA_USD) AMTNTDA_USD, SUM(AMTNTDA_VND) AMTNTDA_VND,
			SUM(AMTNTTTR_USD) AMTNTTTR_USD, SUM(AMTNTTTR_VND) AMTNTTTR_VND,
			SUM(AMTNTTTA_USD) AMTNTTTA_USD, SUM(AMTNTTTA_VND) AMTNTTTA_VND
		FROM
		(
			SELECT BRCD,  TRSEQ,
				DECODE(TRCCYCD, STLCCYCD, SUM(CS1.excrosscal(BRCD,'VND',&h_trdt, CCY, LDRBAL,'01','USD','01')),0) AMTNTDP_USD,
				DECODE(TRCCYCD, STLCCYCD, 0, LDRBAL * TYGIA) AMTNTDP_VND,
				0 AMTNTDA_USD, 0 AMTNTDA_VND, 0 AMTNTTTR_USD, 0 AMTNTTTR_VND, 0 AMTNTTTA_USD, 0 AMTNTTTA_VND
			FROM
			(
				SELECT BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD,
					SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT) TYGIA
				FROM TBGL_BALDD BAL, TBTF_STLINFO STL
				WHERE
					BAL.BRCD LIKE '%'
					AND BAL.TRDT = &h_trdt
					AND BAL.BUSCD = 'TF'
					AND BAL.UNTBUSCD = 'EX'
					AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
					AND BAL.TRREF IN ('EDP')
					AND BAL.BRCD = STL.BRCD
					AND BAL.TRREF = STL.TRREF
					AND BAL.TRSEQ = STL.TRSEQ
					AND	BAL.UNTBUSCD = STL.UNTBUSCD
					AND STL.TRCD IN ('W501','W521')
					AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
					AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
				GROUP BY BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD
			)
			GROUP BY BRCD, TRSEQ, LDRBAL, TRCCYCD, STLCCYCD, TYGIA

			UNION ALL

			SELECT BRCD,  TRSEQ, 0 AMTNTDP_USD, 0 AMTNTDP_VND,
				DECODE(TRCCYCD, STLCCYCD, SUM(CS1.excrosscal(BRCD,'VND',&h_trdt, CCY, LDRBAL,'01','USD','01')),0) AMTNTDA_USD,
				DECODE(TRCCYCD, STLCCYCD, 0, LDRBAL * TYGIA) AMTNTDA_VND,
				0 AMTNTTTR_USD, 0 AMTNTTTR_VND, 0 AMTNTTTA_USD, 0 AMTNTTTA_VND
			FROM
			(
				SELECT BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD,
					SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT) TYGIA
				FROM TBGL_BALDD BAL, TBTF_STLINFO STL
				WHERE
					BAL.BRCD LIKE '%'
					AND BAL.TRDT = &h_trdt
					AND BAL.BUSCD = 'TF'
					AND BAL.UNTBUSCD = 'EX'
					AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
					AND BAL.TRREF IN ('EDA')
					AND BAL.BRCD = STL.BRCD
					AND BAL.TRREF = STL.TRREF
					AND BAL.TRSEQ = STL.TRSEQ
					AND	BAL.UNTBUSCD = STL.UNTBUSCD
					AND STL.TRCD IN ('W501','W521')
					AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
					AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
				GROUP BY BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD
			)
			GROUP BY BRCD, TRSEQ, LDRBAL, TRCCYCD, STLCCYCD, TYGIA

			UNION ALL

			SELECT BRCD,  TRSEQ, 0 AMTNTDP_USD, 0 AMTNTDP_VND, 0 AMTNTDA_USD, 0 AMTNTDA_VND,
				DECODE(TRCCYCD, STLCCYCD, SUM(CS1.excrosscal(BRCD,'VND',&h_trdt, CCY, LDRBAL,'01','USD','01')),0) AMTNTTTR_USD,
				DECODE(TRCCYCD, STLCCYCD, 0, LDRBAL * TYGIA) AMTNTTTR_VND, 0 AMTNTTTA_USD, 0 AMTNTTTA_VND
			FROM
			(
				SELECT BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD,
					SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT) TYGIA
				FROM TBGL_BALDD BAL, TBTF_STLINFO STL
				WHERE
					BAL.BRCD LIKE '%'
					AND BAL.TRDT = &h_trdt
					AND BAL.BUSCD = 'TF'
					AND BAL.UNTBUSCD = 'EX'
					AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
					AND BAL.TRREF IN ('TTR')
					AND BAL.BRCD = STL.BRCD
					AND BAL.TRREF = STL.TRREF
					AND BAL.TRSEQ = STL.TRSEQ
					AND	BAL.UNTBUSCD = STL.UNTBUSCD
					AND STL.TRCD IN ('W501','W521')
					AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
					AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
				GROUP BY BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD
			)
			GROUP BY BRCD, TRSEQ, LDRBAL, TRCCYCD, STLCCYCD, TYGIA

			UNION ALL

			SELECT BRCD,  TRSEQ, 0 AMTNTDP_USD, 0 AMTNTDP_VND, 0 AMTNTDA_USD, 0 AMTNTDA_VND, 0 AMTNTTTR_USD, 0 AMTNTTTR_VND,
				DECODE(TRCCYCD, STLCCYCD, SUM(CS1.excrosscal(BRCD,'VND',&h_trdt, CCY, LDRBAL,'01','USD','01')),0) AMTNTTTA_USD,
				DECODE(TRCCYCD, STLCCYCD, 0, LDRBAL * TYGIA) AMTNTTTA_VND
			FROM
			(
				SELECT BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD,
					SUM(STL.BCEQAMT)/SUM(STL.TRCCYEQAMT) TYGIA
				FROM TBGL_BALDD BAL, TBTF_STLINFO STL
				WHERE
					BAL.BRCD LIKE '%'
					AND BAL.TRDT = &h_trdt
					AND BAL.BUSCD = 'TF'
					AND BAL.UNTBUSCD = 'EX'
					AND BAL.ACCTCD IN ('221100','221200','221300','221400','221500')
					AND BAL.TRREF IN ('TTA')
					AND BAL.BRCD = STL.BRCD
					AND BAL.TRREF = STL.TRREF
					AND BAL.TRSEQ = STL.TRSEQ
					AND	BAL.UNTBUSCD = STL.UNTBUSCD
					AND STL.TRCD IN ('W501','W521')
					AND (STL.CNCLDT = ' ' OR STL.CNCLDT IS NULL)
					AND (STL.CNCLUSRID = ' ' OR STL.CNCLUSRID IS NULL)
				GROUP BY BAL.BRCD, BAL.TRSEQ, BAL.CCY, BAL.LDRBAL, STL.TRCCYCD, STL.STLCCYCD
			)
			GROUP BY BRCD, TRSEQ, LDRBAL, TRCCYCD, STLCCYCD, TYGIA
		)
		GROUP BY BRCD
	)
	GROUP BY BRCD
)A, TBCS_BRCD B
WHERE A.BRCD = B.BRCD
GROUP BY A.BRCD, B.ENGBRSHRTNM
ORDER BY A.BRCD, B.ENGBRSHRTNM
