-- Tu dau thang - QDUSD
-- Ko tinh GD va VND
--define	h_trdt  = '20120231'

SELECT	a.BRCD, c.LCLBRSHRTNM, a.ACCTCD,
		DECODE(B.CUSTTPCD, '100', 'INV', 'CMP') CUSTTYPE,
		SUM(CS1.excrosscal('1000', 'VND', A.TRDT, A.CCY, NVL(A.CRAMT,0) , '01', 'USD', '01')) CRAMT,
		SUM(CS1.excrosscal('1000', 'VND', A.TRDT, A.CCY, NVL(A.DRAMT,0) , '01', 'USD', '01')) DRAMT,
		SUM(CS1.excrosscal('1000', 'VND', A.TRDT, A.CCY, NVL(A.CRAMT,0) , '01', 'VND', '01')) CRAMT_QD,
		SUM(CS1.excrosscal('1000', 'VND', A.TRDT, A.CCY, NVL(A.DRAMT,0) , '01', 'VND', '01')) DRAMT_QD
FROM (
	SELECT
		C.SBVCD, C.ACCTCD, A.BRCD, A.TRDT, A.CCY, A.CRTUSR,A.DYSEQ, A.CUSTSEQ,
		DECODE(A.TRDRCR, 'C', DECODE(B.TRTP, '0', A.TRAMT, -A.TRAMT), 0) CRAMT,
		DECODE(A.TRDRCR, 'D', DECODE(B.TRTP, '0', A.TRAMT, -A.TRAMT), 0) DRAMT,
		B.REMARK1, A.TRREF, B.TRTP
	FROM GL1.TBGL_JNLDD A, GL1.TBGL_JNLMST B, (
		SELECT *
		FROM GL1.TBGL_SBVCD
		WHERE ACCTCD IN ('221100', '221101') OR SUBSTR(SBVCD, 1, 3) = '275' OR SUBSTR(SBVCD, 1, 2) = '28'
		) C
	WHERE
		A.TRDT = B.TRDT AND A.DYHBR = B.DYHBR AND A.CRTUSR = B.CRTUSR AND A.DYSEQ = B.DYSEQ
		AND A.ACCTCD = C.ACCTCD AND DECODE(A.CCY,'VND','1','GD1','3','GD2','3','GD3','3','GD4','3','2') = C.BCCYFG
		AND A.TRDT BETWEEN substr(&h_trdt, 1, 6) || '01' AND &h_trdt
		AND A.DYHBR LIKE '%'
	) a, CM1.TBCM_GENERAL b, CS1.TBCS_BRCD c
WHERE
	A.BRCD = B.BRCD AND A.CUSTSEQ = B.CUSTSEQ
	AND a.BRCD = c.BRCD
	AND a.CCY     LIKE DECODE('2','1','%','2','%','3','GD%','4','USD')
	AND a.CCY NOT LIKE DECODE('2','1','AAA','2','GD%','3','AAA','4','AAA')
	AND a.CCY NOT LIKE DECODE('2','1','AAA','2','VND','3','AAA','4','AAA')
	AND B.CUSTTPCD LIKE '%'
GROUP BY a.BRCD, c.LCLBRSHRTNM, a.ACCTCD, B.CUSTTPCD
ORDER BY A.BRCD, c.LCLBRSHRTNM, A.ACCTCD, B.CUSTTPCD ;
