--thay doi: ngay lam viec Korebank
--define h_trdt = '20090901'
--define h_trdt = '20090901'

SELECT BRCD, CCYCD, SUM(CLRBAL)
FROM
(	SELECT clr.BRCD, clr.DPTPCD, clr.ACCTSEQ, clr.MINSCL, mst.CLSDT, mst.CCYCD, mst.CUSTSEQ, mst.IDXACNO, mst.CURBAL, scl.CLRBAL
	FROM
	(	SELECT a.BRCD, a.DPTPCD, a.ACCTSEQ, MINSCL, MAX(CLRDT) MAXSCL
		FROM DP1.TBDP_SCLRBAL a,
		(
			SELECT BRCD, DPTPCD, ACCTSEQ, MIN(CLRDT) MINSCL
			FROM DP1.TBDP_SCLRBAL
			WHERE BRCD LIKE ''||'%'
			AND CLRDT <= &h_trdt
			GROUP BY BRCD, DPTPCD, ACCTSEQ
			HAVING COUNT (*)>1
		) b
		WHERE a.BRCD=b.BRCD
		AND a.DPTPCD=b.DPTPCD
		AND a.ACCTSEQ=b.ACCTSEQ
		GROUP BY a.BRCD, a.DPTPCD, a.ACCTSEQ, MINSCL
	) clr, DP1.TBDP_SAVMST mst, DP1.TBDP_SCLRBAL scl, CM1.TBCM_GENERAL gen
	WHERE clr.BRCD = mst.BRCD
	AND clr.DPTPCD = mst.DPTPCD
	AND clr.ACCTSEQ = mst.ACCTSEQ
	AND mst.CLSDT BETWEEN &h_trdt AND &h_trdt
	AND gen.BRCD = '1000'
	AND mst.CUSTSEQ = gen.CUSTSEQ
	AND gen.CUSTTPCD LIKE DECODE('3','1','100','%')
	AND gen.CUSTTPCD NOT LIKE DECODE('3','1','999','2','100','999')
	AND mst.CCYCD LIKE ''||'%'
	AND clr.BRCD=scl.BRCD
	AND clr.DPTPCD=scl.DPTPCD
	AND clr.ACCTSEQ=scl.ACCTSEQ
	AND clr.MAXSCL=scl.CLRDT
)
GROUP BY BRCD, CCYCD
