SELECT A.BRCD, B.MCTVNNM COUNTER_PARTY,A.EDCDT DEAL_DATE,
       D.VALDT VALUE_DATE,'BUY'  TT_SELL,
       A.CCYCD DEAL_CCY,A.TRANAMT DEAL_AMOUNT,
       'VND' COUNTER_CCY, (A.TRANAMT*C.TREXRT) COUNTER_AMOUNT,
       C.TREXRT RATE,A.GLUSERID USERID, A.GLNO JOURNAL_SEQ,
       D.REMARK1  REMARK, A.GLDT NGAY_HACH_TOAN
FROM EI1.TBEI_EDCINF A, EI1.TBEI_MCTINF B, EI1.TBEI_JOURNAL  C,
	 GL1.TBGL_JNLMST D
WHERE  A.EDCDT >= TO_CHAR(ADD_MONTHS(TO_DATE(&h_trdt,'YYYYMMDD'),-3),'YYYYMMDD')
AND A.CCYCD = 'USD'
AND A.GLDT = &h_trdt
AND A.STATUS IN ('3','6','T')
AND A.BRCD = B.BRCD
AND A.MCTID = B.MCTID
AND A.BRCD = C.BRCD
AND A.GLDT = C.TRDT
AND TRIM(A.GLUSERID) = TRIM(C.TRUSRID)
AND A.GLNO = C.JOURNALNO
AND C.SEQNO = '0'
AND A.BRCD = D.DYHBR
AND A.GLDT = D.TRDT
AND A.GLUSERID =  D.CRTUSR
AND A.GLNO = D.DYSEQ
ORDER BY A.BRCD, A.GLDT,A.GLUSERID,A.GLNO;







