
SELECT A.BRCD MACHINHANH, D.LCLBRNM, G.DEPTCD MAPGD, C.DEPTNM TENPGD, A.CUSTSEQ CIF,
	B.NM TENKHACHHANG, DECODE(A.CRDTP,'1', 'MASTER', '3', 'VISA', 'B', 'VISA BUSINESS') LOAITHE,
	A.DEBITAMT DUNO, E.DECODE TAISANDAMBAO, E.CCYCD NGUYENTE, E.PLGAMT TRIGIA,
	F.CARDNBR
FROM
	EI1.TBEI_CARDMST A, CM1.TBCM_GENERAL B, CS1.TBCS_DEPTCD C, CS1.TBCS_BRCD D,
(
	SELECT
	DISTINCT A.BRCD,
	A.CUSTSEQLN,
	A.CCYCD,
	SUM(A.PLGAMT) PLGAMT,
	D.DECODE
	FROM LN1.TBLN_PLG A,LN1.TBLN_CLPLG B,LN1.TBLN_CL C,RACE.T_CODE D
	WHERE A.BRCD LIKE '%'
	AND A.STSCD IN('01','03')
	AND A.REGSTPCD='02'
	AND A.PLGAMT<>0
	AND (A.RLSTRDT>&h_trdt OR NVL(A.RLSTRDT,'NONENONE')='NONENONE')
	AND NVL(A.PLGTRDT,'00000000')<=&h_trdt
	AND A.BUSCD='EI'
	AND A.BRCD=B.BRCD
	AND A.PLGID=B.PLGID
	AND A.PLGSEQ=B.PLGSEQ
	AND B.BRCDCL=C.BRCD
	AND B.CLID=C.CLID
	AND B.CLSEQ=C.CLSEQ
	AND D.CAT_NAME='LNCLDTLTPCD'
	AND C.CLDTLTPCD<>'620'
	AND D.COUNTRY='VN'
	AND C.CLDTLTPCD=D.CODE
	GROUP BY A.BRCD, A.CUSTSEQLN, A.CCYCD, D.DECODE
	UNION ALL
	SELECT
	A.BRCD,
	A.CUSTSEQ,
	A.CCY,
	SUM(A.TDBAL),
	'TK K Qy'
	FROM GL1.TBGL_MAST A
	WHERE A.BRCD LIKE '%'
	AND A.TRDT=&h_trdt
	AND A.ACCTCD ='466301'
	AND A.TDBAL<>0
	GROUP BY A.BRCD,A.CUSTSEQ ,A.CCY,A.ACCTCD
	ORDER BY CUSTSEQLN
) E, EI1.TBEI_CARD2ACCT F , DP1.TBDP_IDXACCT G
WHERE
	A.BRCD = B.BRCD
	AND A.CUSTSEQ = B.CUSTSEQ
	AND A.ACCTNO = G.ACCTNO
	AND G.DEPTCD = C.DEPTCD
	AND SUBSTR(G.DEPTCD,3,1) = 'O'
	AND A.BRCD = D.BRCD
	AND A.BRCD = E.BRCD(+)
	AND A.CUSTSEQ = E.CUSTSEQLN(+)
	AND A.BRCD = F.BRCD
	AND A.ACCTNO = F.ACCTCD
ORDER BY A.BRCD, B.DEPTCD, A.CUSTSEQ
