--define h_trdt = '20120830'

SELECT ITEM, A.CUSTSEQ, NVL(NMLOC, 'KH VANG LAI') TENKHACHHANG,
       ROUND(SUM(DECODE(CCYCD, 'VND', COKYHAN + DECODE(ITEM, 'I. Nhan tien goi cua TCTD khac', DECODE(CCYCD, 'VND', NVL(KHONGKYHAN, 0), 0), 0), 0)), 0) SODU_VND,
       ROUND(SUM(DECODE(CCYCD, 'VND', 0, DECODE(SUBSTR(CCYCD, 1, 2), 'GD', 0, COKYHAN)) + DECODE(CCYCD, 'VND', 0, DECODE(SUBSTR(CCYCD, 1, 2), 'GD', 0, DECODE(ITEM, 'I. Nhan tien goi cua TCTD khac', KHONGKYHAN, 0))))) SODU_NGTE,
       ROUND(SUM(DECODE(SUBSTR(CCYCD, 1, 2), 'GD', NVL(COKYHAN, 0), 0) + DECODE(SUBSTR(CCYCD, 1, 2), 'GD', DECODE(ITEM, 'I. Nhan tien goi cua TCTD khac', NVL(KHONGKYHAN, 0), 0), 0)), 0) SODU_VANG
FROM
(
SELECT 'I. Nhan tien goi cua TCTD khac' ITEM, A.BRCD, A.CPTYSEQNO CUSTSEQ, B.CCYCD,
       CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, B.CCYCD, B.NMNLAMT - NVL(SUM(G.NMNLAMT), 0), '01', 'VND', '01') / 1000000 COKYHAN, 0 KHONGKYHAN,
       TO_DATE(A.MATDT, 'YYYYMMDD') - TO_DATE(A.VALDT, 'YYYYMMDD') DAYS
FROM   DL1.TBDL_DEAL A, DL1.TBDL_MM B, DL1.TBDL_DEALSUB F, DL1.TBDL_MMSUB G, CS1.TBCS_BRCD H
WHERE  A.DLTPCD = 'M' AND A.SBTPCD = 'CM' AND A.AUTHFLG = 'Y' AND
       A.VALDT <= &h_trdt AND H.BRCD = A.BRCD AND A.MATDT > &h_trdt AND A.MATDT <= H.CURBUSDAY AND
       B.BRCD = A.BRCD AND B.DLTPCD = A.DLTPCD AND B.SBTPCD = A.SBTPCD AND B.DLSEQNO = A.DLSEQNO
	AND F.BRCD (+) = A.BRCD
	AND F.DLTPCD (+) = A.DLTPCD
	AND F.SBTPCD (+) = A.SBTPCD
	AND F.DLSEQNO (+) = A.DLSEQNO
	AND F.DLLASTSTSCD (+) = '09'
	AND F.MATDT (+) <= &h_trdt
	AND G.BRCD (+) = F.BRCD
	AND G.DLTPCD (+) = F.DLTPCD
	AND G.SBTPCD (+) = F.SBTPCD
	AND G.DLSEQNO (+) = F.DLSEQNO
	AND G.SUBSEQ (+) = F.SUBSEQ
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CPTYSEQNO, B.CCYCD, B.NMNLAMT, A.VALDT, A.MATDT
UNION ALL
SELECT 'II. Vay TCTD khac' ITEM, A.BRCD, A.CPTYSEQNO, B.CCYCD,
       CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, B.CCYCD, B.NMNLAMT - NVL(SUM(G.NMNLAMT), 0), '01', 'VND', '01') /1000000 COKYHAN, 0 KHONGKYHAN,
       TO_DATE(A.MATDT, 'YYYYMMDD') - TO_DATE(A.VALDT, 'YYYYMMDD') DAYS
FROM   DL1.TBDL_DEAL A, DL1.TBDL_MM B, DL1.TBDL_DEALSUB F, DL1.TBDL_MMSUB G, CS1.TBCS_BRCD H
WHERE  A.DLTPCD = 'M' AND A.SBTPCD = 'BB' AND A.AUTHFLG = 'Y' AND
       A.VALDT <= &h_trdt AND H.BRCD = A.BRCD AND A.MATDT > &h_trdt AND A.MATDT <= H.CURBUSDAY AND
       B.BRCD = A.BRCD AND B.DLTPCD = A.DLTPCD AND B.SBTPCD = A.SBTPCD AND B.DLSEQNO = A.DLSEQNO
	AND F.BRCD (+) = A.BRCD
	AND F.DLTPCD (+) = A.DLTPCD
	AND F.SBTPCD (+) = A.SBTPCD
	AND F.DLSEQNO (+) = A.DLSEQNO
	AND F.DLLASTSTSCD (+) = '09'
	AND F.MATDT (+) <= &h_trdt
	AND G.BRCD (+) = F.BRCD
	AND G.DLTPCD (+) = F.DLTPCD
	AND G.SBTPCD (+) = F.SBTPCD
	AND G.DLSEQNO (+) = F.DLSEQNO
	AND G.SUBSEQ (+) = F.SUBSEQ
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CPTYSEQNO, B.CCYCD, B.NMNLAMT, A.VALDT, A.MATDT
UNION ALL
SELECT 'II. Di vay TCTD khac' ITEM, A.BRCD, A.CPTYSEQNO, B.CCYCD,
       CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, B.CCYCD, B.NMNLAMT - NVL(SUM(G.NMNLAMT), 0), '01', 'VND', '01') /1000000 COKYHAN, 0 KHONGKYHAN,
       TO_DATE(A.MATDT, 'YYYYMMDD') - TO_DATE(A.VALDT, 'YYYYMMDD') DAYS
FROM   DL1.TBDL_DEAL A, DL1.TBDL_MM B, DL1.TBDL_DEALSUB F, DL1.TBDL_MMSUB G, CS1.TBCS_BRCD H
WHERE  A.DLTPCD = 'M' AND A.SBTPCD = 'BM' AND A.AUTHFLG = 'Y' AND
       A.VALDT <= &h_trdt AND H.BRCD = A.BRCD AND A.MATDT > &h_trdt AND A.MATDT <= H.CURBUSDAY AND
       B.BRCD = A.BRCD AND B.DLTPCD = A.DLTPCD AND B.SBTPCD = A.SBTPCD AND B.DLSEQNO = A.DLSEQNO
	AND F.BRCD (+) = A.BRCD
	AND F.DLTPCD (+) = A.DLTPCD
	AND F.SBTPCD (+) = A.SBTPCD
	AND F.DLSEQNO (+) = A.DLSEQNO
	AND F.DLLASTSTSCD (+) = '09'
	AND F.MATDT (+) <= &h_trdt
	AND G.BRCD (+) = F.BRCD
	AND G.DLTPCD (+) = F.DLTPCD
	AND G.SBTPCD (+) = F.SBTPCD
	AND G.DLSEQNO (+) = F.DLSEQNO
	AND G.SUBSEQ (+) = F.SUBSEQ
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CPTYSEQNO, B.CCYCD, B.NMNLAMT, A.VALDT, A.MATDT
UNION ALL
SELECT 'III. Goi tien tai cac TCTD khac' ITEM, A.BRCD, A.CPTYSEQNO, B.CCYCD,
       CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, B.CCYCD, B.NMNLAMT - NVL(SUM(G.NMNLAMT), 0), '01', 'VND', '01')/1000000 COKYHAN, 0 KHONGKYHAN,
       TO_DATE(A.MATDT, 'YYYYMMDD') - TO_DATE(A.VALDT, 'YYYYMMDD') DAYS
FROM   DL1.TBDL_DEAL A, DL1.TBDL_MM B, DL1.TBDL_DEALSUB F, DL1.TBDL_MMSUB G, CS1.TBCS_BRCD H
WHERE  A.DLTPCD = 'M' AND A.SBTPCD = 'CL' AND A.AUTHFLG = 'Y' AND
       A.VALDT <= &h_trdt AND H.BRCD = A.BRCD AND A.MATDT > &h_trdt AND A.MATDT <= H.CURBUSDAY AND
       B.BRCD = A.BRCD AND B.DLTPCD = A.DLTPCD AND B.SBTPCD = A.SBTPCD AND B.DLSEQNO = A.DLSEQNO
	AND F.BRCD (+) = A.BRCD
	AND F.DLTPCD (+) = A.DLTPCD
	AND F.SBTPCD (+) = A.SBTPCD
	AND F.DLSEQNO (+) = A.DLSEQNO
	AND F.DLLASTSTSCD (+) = '09'
	AND F.MATDT (+) <= &h_trdt
	AND G.BRCD (+) = F.BRCD
	AND G.DLTPCD (+) = F.DLTPCD
	AND G.SBTPCD (+) = F.SBTPCD
	AND G.DLSEQNO (+) = F.DLSEQNO
	AND G.SUBSEQ (+) = F.SUBSEQ
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CPTYSEQNO, B.CCYCD, B.NMNLAMT, A.VALDT, A.MATDT
UNION ALL
SELECT 'IV. Cho vay cac TCTD khac' ITEM, A.BRCD, A.CPTYSEQNO, B.CCYCD,
       CS1.EXCROSSCAL(A.BRCD, 'VND', &h_trdt, B.CCYCD, B.NMNLAMT - NVL(SUM(G.NMNLAMT), 0), '01', 'VND', '01')/1000000 COKYHAN, 0 KHONGKYHAN,
       TO_DATE(A.MATDT, 'YYYYMMDD') - TO_DATE(A.VALDT, 'YYYYMMDD') DAYS
FROM   DL1.TBDL_DEAL A, DL1.TBDL_MM B, DL1.TBDL_DEALSUB F, DL1.TBDL_MMSUB G, CS1.TBCS_BRCD H
WHERE  A.DLTPCD = 'M' AND A.SBTPCD = 'BL' AND A.AUTHFLG = 'Y' AND
       A.VALDT <= &h_trdt AND H.BRCD = A.BRCD AND A.MATDT > &h_trdt AND A.MATDT <= H.CURBUSDAY AND
       B.BRCD = A.BRCD AND B.DLTPCD = A.DLTPCD AND B.SBTPCD = A.SBTPCD AND B.DLSEQNO = A.DLSEQNO
	AND F.BRCD (+) = A.BRCD
	AND F.DLTPCD (+) = A.DLTPCD
	AND F.SBTPCD (+) = A.SBTPCD
	AND F.DLSEQNO (+) = A.DLSEQNO
	AND F.DLLASTSTSCD (+) = '09'
	AND F.MATDT (+) <= &h_trdt
	AND G.BRCD (+) = F.BRCD
	AND G.DLTPCD (+) = F.DLTPCD
	AND G.SBTPCD (+) = F.SBTPCD
	AND G.DLSEQNO (+) = F.DLSEQNO
	AND G.SUBSEQ (+) = F.SUBSEQ
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CPTYSEQNO, B.CCYCD, B.NMNLAMT, A.VALDT, A.MATDT
) A, CM1.TBCM_GENERAL B
WHERE A.BRCD = B.BRCD AND A.CUSTSEQ = B.CUSTSEQ
GROUP BY ITEM, A.CUSTSEQ, NVL(NMLOC, 'KH VANG LAI')
ORDER BY ITEM, CUSTSEQ
