--DEFINE h_trdt = '20120730'
SELECT C.VALDATE, C.BRCD, C.OPUSER, C.DASEQ, B.TRACCY, B.TRAAMT, A.CPCCY, A.CPTRAEXRT, A.CPTRAMT, D.NMLOC
FROM LR1.TBLR_SRCNPDTL A , LR1.TBLR_SRMASTER B, LR1.TBLR_SRDETAIL C, CM1.TBCM_GENERAL D
WHERE A.BRCD IN (SELECT BRCD FROM CS1.TBCS_BRCD)
AND A.TRREF='STT'
--AND A.TRSEQ LIKE '12%'
AND A.DTSEQ=1
AND A.CPSEQ=1
AND A.CPCCY<>'VND'
AND A.BRCD =B.BRCD
AND A.TRREF=B.TRREF
AND A.TRSEQ =B.TRSEQ
AND A.BRCD =C.BRCD
AND A.TRREF=C.TRREF
AND A.TRSEQ =C.TRSEQ
AND B.OPENFLG=1
AND C.VALDATE = &h_trdt
AND B.VERIFY='Y'
AND B.MSGKDCD IN ('IO','PC','CH','VC','IB')
AND B.TRACCY ='VND'
AND D.BRCD='1000'
AND D.CUSTSEQ(+)=B.CUSTNO
ORDER BY C.VALDATE, C.BRCD, C.OPUSER, C.DASEQ ;
