--DEFINE h_trdt = '20090625'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT A.BRCD,	A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CCYCD, TO_CHAR(A.NMNLAMT), A.INTRT, A.SPRD, A.OVRNTFLG,
	TO_CHAR(SUM(NVL(E.INTAMT, 0))), B.VALDT, B.MATDT, B.ONOFFSHRFLG, C.SBTPNM, D.SHRTNMLOC, B.DLDT
FROM	DL1.TBDL_MM A, DL1.TBDL_DEAL B, DL1.TBDL_SUBTYPE C, CM1.TBCM_GENERAL D, DL1.TBDL_INTSCH E
WHERE	A.DLTPCD	!= 'N'	AND
A.BRCD		= B.BRCD		AND
A.DLTPCD	= B.DLTPCD		AND
A.SBTPCD	= B.SBTPCD		AND
A.DLSEQNO	= B.DLSEQNO		AND
A.BRCD		= E.BRCD		AND
A.DLTPCD	= E.DLTPCD		AND
A.SBTPCD	= E.SBTPCD		AND
A.DLSEQNO	= E.DLSEQNO		AND
A.DLTPCD	= C.DLTPCD		AND
A.SBTPCD	= C.SBTPCD		AND
B.DLLASTSTSCD = '03'		AND
B.BRCD		= D.BRCD(+)		AND
B.CPTYSEQNO	= D.CUSTSEQ(+)	AND
A.BRCD||A.DLTPCD||A.SBTPCD||A.DLSEQNO > '0' AND 1=1  AND (B.VALDT <= &h_trdt AND B.MATDT > &h_trdt) AND
A.BRWPLCFLG IN ('B', 'P')  AND A.CCYCD IN ('VND', 'USD', 'GD1')
GROUP BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO, A.CCYCD, A.NMNLAMT, A.INTRT, A.SPRD, A.OVRNTFLG,
	B.VALDT, B.MATDT, B.ONOFFSHRFLG, C.SBTPNM, D.SHRTNMLOC, B.DLDT
ORDER BY A.BRCD, A.DLTPCD, A.SBTPCD, A.DLSEQNO
