SELECT 
	A.BRCD MA_CHI_NHANH, B.LCLBRNM CHI_NHANH, 
	A.DEPTCD MA_PHONG, A.DEPTNM PHONG_GIAO_DICH
FROM 
	CS1.TBCS_DEPTCD A, CS1.TBCS_BRCD B
WHERE 
	A.DEPTCD LIKE '__O'
	AND A.BRCD = B.BRCD
	AND A.DEPTCD NOT IN ('BNO', 'T1O', 'MHO')
ORDER BY 
	A.BRCD, A.DEPTCD
