--DEFINE h_trdt = '20090625'
--DEFINE h_startdt = '20090631'
--DEFINE h_enddt = '20090530'
SELECT BRCD, SUM(TDBAL1) AS TKCC,SUM(TDBAL2) TKCK,SUM(TDBAL3) DNCKCT,SUM(TDBAL4) DNCC,SUM(TDBAL5) "466901"

                     		FROM
					(
						SELECT  G.BRCD BRCD, G.ACCTCD ACCTCD,
				   		SUM(decode(G.CCY, 'VND',G.TDBAL, GL1.PERIODEXCHANGE_F('1', G.BRCD, 'VND', G.CCY, &h_trdt, &h_trdt, G.TDBAL)
												)) TDBAL1,  0 TDBAL2, 0 TDBAL3, 0 TDBAL4,0 TDBAL5
						FROM
							(
								SELECT  A.TRDT,  A.BRCD BRCD, A.CCY CCY,  A.ACCTCD ACCTCD, SUM(A.TDBAL + A.TDACRBAL) TDBAL
								FROM 	 GL1.TBGL_MAST A
								WHERE
									A.TRDT LIKE &h_trdt
									AND	A.BRCD  like  '%'
									AND  	A.ACCTCD IN (SELECT DECODE FROM RACE.T_CODE WHERE CAT_NAME='GLMISRPTFU26' AND CODE LIKE 'A01%')
									AND 	A.TDBAL+A.TDACRBAL <> 0
									AND    	A.ONOFFTP LIKE '1'
									GROUP   BY A.TRDT, A.BRCD, A.CCY, A.ACCTCD
							) G
						GROUP BY  G.TRDT, G.BRCD, G.ACCTCD
						UNION ALL
						SELECT  G.BRCD BRCD, G.ACCTCD ACCTCD, 0 TDBAL1,
						SUM(decode(G.CCY, 'VND',G.TDBAL, GL1.PERIODEXCHANGE_F('1', G.BRCD, 'VND', G.CCY, &h_trdt, &h_trdt, G.TDBAL)
												)) TDBAL2, 0 TDBAL3, 0 TDBAL4,0 TDBAL5
						FROM
							(
								SELECT  A.TRDT,  A.BRCD BRCD, A.CCY CCY,  A.ACCTCD ACCTCD, SUM(A.TDBAL + A.TDACRBAL) TDBAL
								FROM 	 GL1.TBGL_MAST A
								WHERE
									A.TRDT LIKE &h_trdt
									AND	A.BRCD  LIKE  '%'
									AND  	A.ACCTCD IN (SELECT DECODE FROM RACE.T_CODE WHERE CAT_NAME='GLMISRPTFU26' AND CODE LIKE 'A02%')
									AND     A.CUSTSEQ<>'100272080'
									AND 	A.TDBAL+A.TDACRBAL <> 0
									AND    	A.ONOFFTP LIKE '1'
									GROUP   BY A.TRDT, A.BRCD, A.CCY, A.ACCTCD
							) G
						GROUP BY  G.TRDT, G.BRCD, G.ACCTCD
						UNION ALL
						SELECT  G.BRCD BRCD, G.ACCTCD ACCTCD, 0 TDBAL1, 0 TDBAL2,
						SUM(decode(G.CCY, 'VND',G.TDBAL, GL1.PERIODEXCHANGE_F('1', G.BRCD, 'VND', G.CCY, &h_trdt, &h_trdt, G.TDBAL)
												)) TDBAL3,0 TDBAL4,0 TDBAL5
						FROM
							(
								SELECT  A.TRDT,  A.BRCD BRCD, A.CCY CCY,  A.ACCTCD ACCTCD, SUM(A.TDBAL + A.TDACRBAL) TDBAL
								FROM 	 GL1.TBGL_MAST A
								WHERE
									A.TRDT LIKE &h_trdt
									AND	A.BRCD  LIKE  '%'
									AND  	A.ACCTCD IN (SELECT DECODE FROM RACE.T_CODE WHERE CAT_NAME='GLMISRPTFU26' AND CODE LIKE 'A03%')
									AND 	A.TDBAL+A.TDACRBAL <> 0
									AND    	A.ONOFFTP LIKE '1'
									GROUP   BY A.TRDT, A.BRCD, A.CCY, A.ACCTCD
							) G
						GROUP BY  G.TRDT, G.BRCD, G.ACCTCD
						UNION ALL
						SELECT  G.BRCD BRCD, G.ACCTCD ACCTCD, 0 TDBAL1, 0 TDBAL2, 0 TDBAL3,
						SUM(decode(G.CCY, 'VND',G.TDBAL, GL1.PERIODEXCHANGE_F('1', G.BRCD, 'VND', G.CCY, &h_trdt, &h_trdt, G.TDBAL)
												)) TDBAL4,0 TDBAL5
						FROM
							(
								SELECT  A.TRDT,  A.BRCD BRCD, A.CCY CCY,  A.ACCTCD ACCTCD, SUM(A.TDBAL + A.TDACRBAL) TDBAL
								FROM 	 GL1.TBGL_MAST A
								WHERE
									A.TRDT LIKE &h_trdt
									AND	A.BRCD  LIKE  '%'
									AND  	SUBSTR(A.ACCTCD,1,3) IN (SELECT DECODE FROM RACE.T_CODE WHERE CAT_NAME='GLMISRPTFU26' AND CODE LIKE 'A04%')
									AND 	A.TDBAL+A.TDACRBAL <> 0
									AND    	A.ONOFFTP LIKE '1'
									GROUP   BY A.TRDT, A.BRCD, A.CCY, A.ACCTCD
							) G
						GROUP BY  G.TRDT, G.BRCD, G.ACCTCD
						UNION ALL
						SELECT  G.BRCD BRCD, G.ACCTCD ACCTCD, 0 TDBAL1, 0 TDBAL2, 0 TDBAL3,0 TDBAL4,
						SUM(decode(G.CCY, 'VND',G.TDBAL, GL1.PERIODEXCHANGE_F('1', G.BRCD, 'VND', G.CCY, &h_trdt, &h_trdt, G.TDBAL)
												)) TDBAL5
						FROM
							(
								SELECT  A.TRDT,  A.BRCD BRCD, A.CCY CCY,  A.ACCTCD ACCTCD, SUM(A.TDBAL + A.TDACRBAL) TDBAL
								FROM 	 GL1.TBGL_MAST A
								WHERE
									A.TRDT LIKE &h_trdt
									AND	A.BRCD  LIKE  '%'
									AND  	A.ACCTCD IN (SELECT DECODE FROM RACE.T_CODE WHERE CAT_NAME='GLMISRPTFU26' AND CODE LIKE 'A05%')
									AND 	A.TDBAL+A.TDACRBAL <> 0
									AND    	A.ONOFFTP LIKE '1'
									GROUP   BY A.TRDT, A.BRCD, A.CCY, A.ACCTCD
							) G
						GROUP BY  G.TRDT, G.BRCD, G.ACCTCD
					)
				GROUP BY BRCD;
