--thay doi: ngay lam viec Korebank
--define h_trdt = '20090901'
--define h_trdt = '20100625'

SELECT custtpcd, BRCD, CCYCD, SUM(BFBAL), SUM(NEWAMT), SUM(CURBAL)
FROM
(	SELECT decode(gen.custtpcd, '100', 'CA NHAN', 'DOANH NGHIEP') custtpcd, A.BRCD, ren.BFBAL, DECODE(NVL(ren.BFBAL, -1), -1, bal.CLRBAL, 0) NEWAMT, A.CURBAL, A.CCYCD
	FROM
	(	SELECT ren.BRCD, ren.DPTPCD, ren.ACCTSEQ, ren.FMAT, ren.MAXREN, mst.MATDT, mst.CURBAL, mst.CCYCD, ren.ROLLAMT, mst.CUSTSEQ, mst.IDXACNO
		FROM
		(	SELECT BRCD, DPTPCD, ACCTSEQ, DECODE(SIGN(MINOPN - &h_trdt),  -1, MINREN, MINOPN) FMAT, MAXREN, ROLLAMT
			FROM
			(	SELECT BRCD, DPTPCD, ACCTSEQ, MIN(RENWDT) MINREN, MAX(RENWDT) MAXREN, MIN(BFOPNDT) MINOPN, MAX(BFOPNDT) MAXOPN, MIN(BFBAL) ROLLAMT
				FROM DP1.TBDP_RENEW
				WHERE BRCD LIKE ''||'%'
				AND RENWDT BETWEEN &h_trdt AND &h_trdt
				GROUP BY BRCD, DPTPCD, ACCTSEQ
			)
		) ren, DP1.TBDP_SAVMST mst
		WHERE ren.BRCD = mst.BRCD
		AND ren.DPTPCD = mst.DPTPCD
		AND ren.ACCTSEQ = mst.ACCTSEQ
		AND mst.CCYCD LIKE ''||'%'
	) A,
	(	SELECT BRCD, DPTPCD, ACCTSEQ, MIN(RENWDT) MINREN
		FROM DP1.TBDP_RENEW
		WHERE BRCD LIKE ''||'%'
		AND RENWDT > &h_trdt
		GROUP BY BRCD, DPTPCD, ACCTSEQ
	) B, DP1.TBDP_RENEW ren, DP1.TBDP_SCLRBAL bal, DP1.TBDP_TRLST lst, CM1.TBCM_GENERAL gen
	WHERE A.BRCD = B.BRCD(+)
	AND A.DPTPCD = B.DPTPCD(+)
	AND A.ACCTSEQ = B.ACCTSEQ(+)
	AND A.BRCD = ren.BRCD(+)
	AND A.DPTPCD = ren.DPTPCD(+)
	AND A.ACCTSEQ = ren.ACCTSEQ(+)
	AND A.FMAT = ren.RENWDT(+)
	AND A.BRCD = bal.BRCD(+)
	AND A.DPTPCD = bal.DPTPCD(+)
	AND A.ACCTSEQ = bal.ACCTSEQ(+)
	AND A.FMAT = bal.CLRDT(+)
	AND A.BRCD = lst.BRCD(+)
	AND A.DPTPCD = lst.DPTPCD(+)
	AND A.ACCTSEQ = lst.ACCTSEQ(+)
	AND lst.TRDT(+) BETWEEN &h_trdt AND &h_trdt
	AND lst.TGTFLG(+) = 0
	AND lst.CNCLTRFLG(+) = 0
	AND gen.BRCD = '1000'
	AND A.CUSTSEQ = gen.CUSTSEQ
	AND gen.CUSTTPCD LIKE DECODE('3','1','100','%')
	AND gen.CUSTTPCD not LIKE DECODE('3','1','999','2','100','999')
)
GROUP BY custtpcd, BRCD, CCYCD
