--define h_trdt='20110909'
			
SELECT BRCD, DEPTCD, DEPTNMLOC, T_CIF,  T_TK,  T_SD			
FROM
(
	SELECT BRCD, DEPTCD, DEPTNMLOC, COUNT(CUSTSEQ) T_CIF, SUM(TK) T_TK, SUM(SD) T_SD
	FROM
	(
		SELECT BRCD, DEPTCD, DEPTNMLOC, CUSTSEQ, SUM(TK) TK, SUM(SD) SD
		FROM
		(
			SELECT gen.BRCD, idx.DEPTCD, dep.DEPTNMLOC, gen.CUSTSEQ, idx.ACCTNO, COUNT(*)  TK,
					cs1.excrosscal('1000', 'VND', &h_trdt, ccy, SUM(CLRBAL), '01', 'USD', '01') SD
			FROM TBGL_BALDD bal, TBCM_GENERAL gen, TBCS_DEPTCD dep,
			(	SELECT  BRCD, DPTPCD, ACCTSEQ, ACCTNO,
						DECODE(BRCD,'2103', DECODE(TRIM(DEPTCD),'BNO','',TRIM(DEPTCD)),
									'1004', DECODE(TRIM(DEPTCD),'VHO','',TRIM(DEPTCD)),
									'2102', DECODE(TRIM(DEPTCD),'T1O','',TRIM(DEPTCD)),
									'1403', DECODE(TRIM(DEPTCD),'MHO','',TRIM(DEPTCD)),
									'1400', DECODE(TRIM(DEPTCD),'LNO','','TDO','','VVO','',TRIM(DEPTCD)),
											DECODE(TRIM(DEPTCD),'','',TRIM(DEPTCD))) DEPTCD
				FROM TBDP_IDXACCT
				WHERE BRCD LIKE '%'
			) idx
			WHERE  bal.BRCD like '%'
			AND bal.CCY <> 'VND'
			AND bal.TRDT = &h_trdt
			AND bal.BRCD = gen.BRCD
			AND bal.CUSTSEQ = gen.CUSTSEQ
			AND idx.DEPTCD = dep.DEPTCD
			AND DECODE(dep.BRCD,'','1000','1000','1000',dep.BRCD) <>'1000'
			AND bal.BRCD = idx.BRCD
			AND bal.TRREF = idx.DPTPCD
			AND bal.TRSEQ = idx.ACCTSEQ
			AND gen.CUSTTPCD <> '100'			
			AND ACCTCD IN (	SELECT DISTINCT ACCTCD
							FROM GL1.TBGL_SBVCD
							WHERE SUBSTR(SBVCD,1,2) IN ( '42','43')
						)
			AND TRREF <> 'GEO'
			GROUP BY gen.BRCD, idx.DEPTCD,  dep.DEPTNMLOC, gen.CUSTSEQ, idx.ACCTNO, CCY
		)
		GROUP BY BRCD, DEPTCD, DEPTNMLOC, CUSTSEQ
	)
	GROUP BY BRCD, DEPTCD, DEPTNMLOC

	UNION ALL
	--chi nhanh
	SELECT BRCD, DEPTCD, LCLBRNM, COUNT(CUSTSEQ) T_CIF, SUM(TK) T_TK, SUM(SD) T_SD
	FROM
	(
		SELECT BRCD, DEPTCD, LCLBRNM, CUSTSEQ, SUM(TK) TK, SUM(SD) SD
		FROM
		(
			SELECT gen.BRCD, ' ' DEPTCD, br.LCLBRNM, gen.CUSTSEQ, idx.ACCTNO, COUNT(*)  TK,
					cs1.excrosscal( '1000', 'VND', &h_trdt, ccy, SUM(CLRBAL), '01', 'USD', '01') SD
			FROM TBGL_BALDD bal, TBCM_GENERAL gen, TBCS_DEPTCD dep, TBCS_BRCD br,
			(	SELECT  BRCD, DPTPCD, ACCTSEQ, ACCTNO,
						DECODE(BRCD,'2103', DECODE(TRIM(DEPTCD),'BNO','ACC',TRIM(DEPTCD)),
									'2102', DECODE(TRIM(DEPTCD),'T1O','ACC',TRIM(DEPTCD)),
									'1403', DECODE(TRIM(DEPTCD),'MHO','ACC',TRIM(DEPTCD)),
									'1004', DECODE(TRIM(DEPTCD),'VHO','ACC',TRIM(DEPTCD)),
									'1400', DECODE(TRIM(DEPTCD),'LNO','ACC','TDO','ACC','VVO','ACC',TRIM(DEPTCD)),
											DECODE(TRIM(DEPTCD),'','ACC',TRIM(DEPTCD))) DEPTCD
				FROM TBDP_IDXACCT
				WHERE BRCD LIKE '%'
			) idx
			WHERE  bal.BRCD like '%'
			AND bal.CCY <> 'VND'
			AND bal.TRDT = &h_trdt
			AND bal.BRCD = gen.BRCD
			AND bal.CUSTSEQ = gen.CUSTSEQ
			AND idx.DEPTCD = dep.DEPTCD(+)
			AND bal.BRCD = br.BRCD
			AND DECODE(dep.BRCD,'','1000','1000','1000')='1000'
			and bal.acctcd not in('466400','466200') --npa add 04-08-2011& vi o bang mst da lay tk nay roi
			AND bal.BRCD = idx.BRCD
			AND bal.TRREF = idx.DPTPCD
			AND bal.TRSEQ = idx.ACCTSEQ
			AND gen.CUSTTPCD <> '100'			
			AND ACCTCD IN (	SELECT DISTINCT ACCTCD
							FROM GL1.TBGL_SBVCD
							WHERE SUBSTR(SBVCD,1,2) IN ( '42','43')
						)
			AND TRREF <> 'GEO'
			GROUP BY gen.BRCD, br.LCLBRNM, gen.CUSTSEQ, idx.ACCTNO, CCY
		)
		GROUP BY BRCD, DEPTCD, LCLBRNM, CUSTSEQ

		UNION ALL
		--DN  TKKKH      -- KY QUY
		SELECT BRCD, DEPTCD, LCLBRNM, CUSTSEQ, SUM(TK) TK, SUM(SD) SD
		FROM
		(
			SELECT mst.BRCD, ' ' DEPTCD, br.LCLBRNM, mst.CUSTSEQ, mst.ACCTCD, COUNT(*) TK,
							cs1.excrosscal( '1000', 'VND', &h_trdt, CCY, SUM(TDBAL), '01', 'USD', '01') SD
			FROM GL1.TBGL_MAST mst, TBCS_BRCD br, CM1.TBCM_GENERAL gen
			WHERE mst.TRDT = &h_trdt
			AND br.BRCD=  mst.BRCD
			AND mst.CUSTSEQ = gen.CUSTSEQ
			AND gen.BRCD = '1000'
			AND mst.BRCD LIKE '%'
			AND mst.CCY <> 'VND'
			AND mst.ACCTCD in ('466200', '466400')
			AND gen.CUSTTPCD <> '100'			
			GROUP BY mst.BRCD, br.LCLBRNM, mst.CUSTSEQ, mst.ACCTCD, CCY
		)
		GROUP BY BRCD, DEPTCD, LCLBRNM, CUSTSEQ
	)
	GROUP BY BRCD, DEPTCD, LCLBRNM
)
ORDER BY BRCD, DEPTCD